[레벨 1 글쓰기 미션] 민트(유재민) 미션 제출합니다
woowacourse/woowa-writing-5 pull request #106
Opened 2023-03-19 21:04 UTC by yujamint

안녕하세요 크롱, 아커, 박스터, 엔델, 파인, 빅스.
백엔드 크루 민트입니다!
글을 자주 쓰지 않기 때문에 읽기에 힘드실 수도 있을 것 같습니다..! 미리 감사드리며 가감 없는 리뷰 부탁드리겠습니다!

2023-03-20 05:57 UTC, woowahan-neo reviewed
면담 이후 민트의 생각을 엿볼 수 있어서 좋네요.
조만간 밥 먹으면서 또 얘기 나눠봐요 ㅎㅎ

2023-03-20 06:01 UTC, krrong requested changes
글에서 민트가 느끼는 감정들이 전해지는 것 같았어요. 고민을 거듭해보면서 자신만의 답을 찾는 시간이 되었으면 좋겠습니다.

2023-03-20 06:01 UTC, krrong commented on README.md
> +<ins>A 크루의 지식</ins>, <ins>B 크루의 성실도</ins>와 같은 강점은 **하루아침에 만들어지지 않았다.** 지식을 쌓기 위해 투자한 시간, 매일 성실하게 공부하는 생활 패턴 모두 **나와 다르다**는 것을 인정한다. 그런데도 그들과 나를 비교하고 초조함을 느끼는 이유는 뭘까?
저도 못하지만 다른 사람들과 비교하지 않는 게 가장 중요한 것 같아요.🙃

2023-03-21 07:15 UTC, SproutMJ commented on README.md
> +우테코에서 한 달간 생활하며 많은 고민거리가 생겼다. 그중 절반은 <ins>기술에 대한 고민</ins>이다. 그리고 나머지 절반은 <ins>심리적인 고민</ins>이다. 대표적 예로 위에서 언급한 불안감이 있다. 그리고 이를 해결하고자 고민해본 **개발자로서의 목표와 그에 따른 나만의 기준** 역시 포함된다.
.

2023-03-21 07:45 UTC, jeonjeunghoon commented on README.md
> +사람은 누구나 저마다의 강점을 가지고 있다. 누군가는 <ins>글을 잘 쓸 것</ins>이고, 다른 누군가는 <ins>코드를 작성할 때 클린 코드를 잘 적용할 것</ins>이다. 그리고 그 누군가는 **본인의 강점 앞에서 큰 존재감을 드러낸다**.
밑줄이나 볼드같이 효과를 주는 표현이 되게 좋은 것 같아요. 배워갑니다 ~

2023-03-21 07:47 UTC, jeonjeunghoon commented on README.md
> +## 불안과 초조함 속에서 살아간다는 것
제목을 적어주신 점 너무 좋네요
저는 소제목만 적어놔서 보고 배웠습니다.

2023-03-21 07:49 UTC, nangkyeonglim reviewed
안녕하세요 민트~
제가 하는 고민과 비슷한 고민을 하고 계셔서 많이 공감됐어요
계속해서 고민하고 또, 그 속에서 자신이 발전하고 성장한 점을 찾아본다면 언젠간 **좋은 사람, 좋은 개발자**가 되어 있지 않을까요?
초심을 잘 이어서 10개월을 잘 완주할 수 있도록 저도 응원하겠습니다🙌
방학 잘 보내시고 레벨 2도 화이팅입니다!!

2023-03-21 07:49 UTC, nangkyeonglim commented on README.md
> +
저를 포함해서 많은 크루들이 같은 고민을 하고 있을 거라고 생각해요.
지금 하는 고민들이 밑바탕이 되지 않을까 생각합니다 :)

2023-03-21 07:49 UTC, nangkyeonglim commented on README.md
> +그리고 이런 얘기를 듣다 보면 어느새 **초조함**을 느끼게 된다. 분명 나도 무언가를 열심히 하며 하루를 보냈음에도 노력이 부족했는지 생각하게 된다.
무언가를 열심히 하며 하루를 보냈기에 한 달 동안 성장하고 발전한 점이 있지 않을까요?
그 부분에 대한 민트의 이야기를 듣고 싶네요!

2023-03-21 07:50 UTC, jeonjeunghoon commented on README.md
> +한 분야의 전문가, 예를 들어 백엔드 개발자로서 성장하기 위해 학습할 내용은 **너무나도 많을 것**이다. 그 많은 내용들을 하나하나 다 깊게, 완벽하게 공부할 수 있을까? 그렇지 않다. 그렇다면, **중요도**가 높은 내용을 선별해가며 학습해야 할 것이다.
"완벽하게 공부할 수 있을까?" 부분과 "그렇지 않다." 부분을 개행으로 나누면 더욱 가독성이 좋아지고 글의 리듬이 살 것 같은 느낌이 듭니다!

2023-03-21 07:54 UTC, jeonjeunghoon reviewed
안녕하세요 민트~

글 읽으면서 너무 공감이 됐네요.
저도 우테코에 들어와서 남들과 비교하며 많은 고민과 좌절이 있었어요.
물론 지금은 저만의 방법을 찾아서 괜찮아졌어요
민트도 본인만의 해결 방법을 찾은 것 같아 다행이네요!
앞으로 남은 기간도 열심히 하시면 바라시는 것 처럼 **좋은 사람, 좋은 개발자**가 되어 있을 겁니다!

2023-03-21 07:54 UTC, jeonjeunghoon commented on README.md
> +## 불안과 초조함 속에서 살아간다는 것
제목을 적어주신 점 너무 좋네요
저는 소제목만 적어놔서 보고 배웠습니다.

2023-03-21 08:15 UTC, jeonjeunghoon reviewed
안녕하세요 민트~

글 읽으면서 너무 공감이 됐네요.
저도 우테코에 들어와서 남들과 비교하며 많은 고민과 좌절이 있었어요.
물론 지금은 저만의 방법을 찾아서 괜찮아졌어요
민트도 본인만의 해결 방법을 찾은 것 같아 다행이네요!
앞으로 남은 기간도 열심히 하시면 바라시는 것 처럼 **좋은 사람, 좋은 개발자**가 되어 있을 겁니다!

2023-03-21 08:33 UTC, SproutMJ reviewed
글 자체가 깔끔해서 읽기 좋았던 것 같아요

2023-03-21 08:33 UTC, SproutMJ commented on README.md
> +<ins>A 크루의 지식</ins>, <ins>B 크루의 성실도</ins>와 같은 강점은 **하루아침에 만들어지지 않았다.** 지식을 쌓기 위해 투자한 시간, 매일 성실하게 공부하는 생활 패턴 모두 **나와 다르다**는 것을 인정한다. 그런데도 그들과 나를 비교하고 초조함을 느끼는 이유는 뭘까?
뭘까? 이후의 답이 아래에 있는걸까요? 아니면 모른다는 느낌을 주기 위해서 사용한 장치일까요?
이 자체로도 좋은 느낌이긴 합니다.

2023-03-22 06:05 UTC, drunkenhw reviewed
안녕하세요 박스터입니다
글을 대단히 잘쓰시네요~~
잘 읽었습니다~

2023-03-22 06:05 UTC, drunkenhw commented on README.md
> +### 고민하는 중
위에 쓴 것 처럼 소제목이 문장으로 끝나면 더 좋아보일 것 같아요~~

2023-03-22 10:42 UTC, briandr97 commented on README.md
> +한 분야의 전문가, 예를 들어 백엔드 개발자로서 성장하기 위해 학습할 내용은 **너무나도 많을 것**이다. 그 많은 내용들을 하나하나 다 깊게, 완벽하게 공부할 수 있을까? 그렇지 않다. 그렇다면, **중요도**가 높은 내용을 선별해가며 학습해야 할 것이다.
저도 어느 부분을 깊게 공부해야 할 지가 항상 어렵습니다.
공부해야 할 것은 너무 많은데 시간은 한정되었으니 모든 내용을 깊게 볼 수는 없으니,,,

2023-03-22 10:45 UTC, briandr97 commented on README.md
> +이렇게 자신만의 목표가 있다면 그 목표에 맞는 선택에 큰 가치를 부여할 수 있다. 즉, **목표를 통해 자신만의 기준을 세울 수 있을 것**이다. 그리고 기준이 있다면, 그저 **남들이 많이 하는 공부**라는 이유만으로 학습의 필요성을 느끼지 않을 것이다.
그럼 민트의 목표와 기준은 무엇인가요?
저는 공부하면서 당장 제가 더 궁금한 부분들을 공부 중입니다.

2023-03-26 07:27 UTC, yujamint commented on README.md
> +나에게도 강점이 있을 것이다. 그렇다면, 나는 내 강점 앞에서 큰 존재감을 드러낼 수 있을까? 아닌 것 같다. 내 부족한 점을 누군가의 강점과 비교하고, 내가 가진 강점을 다른 사람의 더 큰 강점과 비교하며 작아지기를 자처한다.
@krrong 제 강점은 무던함인 것 같습니다 ㅎㅎ.. 걱정과 고민이 많아도 크게 휘둘리지 않습니다 그리고, 결국 잘 될 것이라고 믿으며 나아가려고 하는 편입니다!

2023-03-26 07:27 UTC, yujamint commented on README.md
> +나에게도 강점이 있을 것이다. 그렇다면, 나는 내 강점 앞에서 큰 존재감을 드러낼 수 있을까? 아닌 것 같다. 내 부족한 점을 누군가의 강점과 비교하고, 내가 가진 강점을 다른 사람의 더 큰 강점과 비교하며 작아지기를 자처한다.
@drunkenhw 다시 보니 개선할 여지가 있는 것 같네요. 짚어주셔서 감사합니다 :)

2023-03-26 07:28 UTC, yujamint commented on README.md
> +이렇게 자신만의 목표가 있다면 그 목표에 맞는 선택에 큰 가치를 부여할 수 있다. 즉, **목표를 통해 자신만의 기준을 세울 수 있을 것**이다. 그리고 기준이 있다면, 그저 **남들이 많이 하는 공부**라는 이유만으로 학습의 필요성을 느끼지 않을 것이다.
@briandr97 저도 마찬가지입니다. 당장은 목표와 기준이 없기 때문에, 당장 많이 쓰는 기술과 학습을 하다가 막히는 부분에 대해서 공부 중입니다!

2023-03-26 07:30 UTC, yujamint commented on README.md
> +<ins>A 크루의 지식</ins>, <ins>B 크루의 성실도</ins>와 같은 강점은 **하루아침에 만들어지지 않았다.** 지식을 쌓기 위해 투자한 시간, 매일 성실하게 공부하는 생활 패턴 모두 **나와 다르다**는 것을 인정한다. 그런데도 그들과 나를 비교하고 초조함을 느끼는 이유는 뭘까?
@SproutMJ 학습을 하며 남들과 비교하고, 초조함을 느끼는 것은 당연한 것이라고 생각했습니다. 하지만, 당연하다고 생각하면서도 쉽게 떨쳐내기 힘든 초조함을 표현하고 싶었습니다 :) 감사합니다

2023-03-26 07:34 UTC, yujamint commented on README.md
> +그리고 이런 얘기를 듣다 보면 어느새 **초조함**을 느끼게 된다. 분명 나도 무언가를 열심히 하며 하루를 보냈음에도 노력이 부족했는지 생각하게 된다.
@nangkyeonglim 분명 한 달 전의 자신과 비교했을 때 성장한 부분은 있는 것 같습니다! 어떤 부분인지 명확하게 설명은 하기 힘들지만, 전보다 성장했다는 사실 자체는 확실히 뿌듯하네요 :)

2023-03-26 07:35 UTC, yujamint commented on README.md
> +한 분야의 전문가, 예를 들어 백엔드 개발자로서 성장하기 위해 학습할 내용은 **너무나도 많을 것**이다. 그 많은 내용들을 하나하나 다 깊게, 완벽하게 공부할 수 있을까? 그렇지 않다. 그렇다면, **중요도**가 높은 내용을 선별해가며 학습해야 할 것이다.
@jeonjeunghoon 좋은 의견 감사합니다! 반영하도록 하겠습니다 :)

2023-03-26 07:35 UTC, yujamint commented on README.md
> +### 고민하는 중
좋은 의견 감사합니다! 반영하도록 하겠습니다 :)

2023-03-26 09:36 UTC, jeonjeunghoon approved these changes
안녕하세요 민트
프론트엔드 크루 아커입니다!

글쓰기 미션과 레벨 1 마지막 미션을 함께 진행하느라 고생하셨습니다.
글을 너무 재밌게 읽었어요.
또한 민트의 글을 보며 제가 잊고 있던 다짐들도 다시 생각하게끔 하는 시간도 되었어요.
그래서 너무 좋았던 글 읽기 시간이었던 것같아요.

지금 마지막 미션 하시느라 바쁘실 텐데, 마무리 잘하시길 바라겠습니다!
글쓰기 미션은 이만 Approve 할게요!

2023-03-26 09:36 UTC, jeonjeunghoon commented on README.md
> +그렇지 않다. 그렇다면, **중요도**가 높은 내용을 선별해가며 학습해야 할 것이다.
문장을 분리하니 가독성이 더욱 좋아진 것 같아요!
글의 리듬감도 살아나는 것같네요

2023-03-26 11:34 UTC, nangkyeonglim approved these changes
안녕하세요 민트! FE 파인입니다~

마크다운 문법을 굉장히 잘 활용해주시고 글을 잘 쓰셔서 읽으면서 정말 잘 쓴 글이라고 느꼈습니다.
`강점은 다른 사람의 더 큰 강점과 비교하여 작아지기를 자처한다.`는 문장이 인상적이면서 공감이 되는 것 같습니다. 고민하며 나아가다 보면 좋은 개발자가 되지 않을까 생각합니다 :)

레벨 1도 거의 끝나가는데 마지막까지 화이팅입니다💪
미션은 이만 Approve 하겠습니다🤩 미션에 글쓰기, 리뷰까지 고생 많으셨습니다!

2023-03-26 12:44 UTC, briandr97 approved these changes
안녕하세요 안드로이드 과정 빅스입니다.
덕분에 마크 다운 문법에 대해 더 알아갑니다! 감사합니다~!
저와 민트 모두 자신만의 강점을 찾을 수 있기를 바랍니다!

글쓰기 미션 고생하셨어요~!

2023-03-26 14:58 UTC, drunkenhw approved these changes
안녕하세요 민트! 박스터입니다
글을 재밌게 읽었습니다~
민트의 생각이 잘 느껴졌습니다!
글쓰기 미션 수고하셨습니다!

2023-03-27 01:39 UTC, SproutMJ approved these changes
안녕하세요 민트, 백엔드 크루 엔델입니다. 마크다운 문법을 활용한 강조를 잘 사용해서 글의 가독성이 좋았습니다. 내용도 크게 치우치지 않고 구성이 좋았던 것 같아요.  우테코를 시작하기 전에 있었던 고민, 그리고 그것을 잘 해결해나가는 모습이 느껴지는 것 같습니다. 고민을 잘 해결하셔서 좋은 개발자가 되시길 바라며, 마지막으로 Approve 남기고 가도록 하겠습니다. 감사합니다.

2023-03-27 04:31 UTC, krrong approved these changes
멀지 않은 시간 안에 민트의 길을 찾았으면 좋겠어요. 
인상깊은 내용도, 공감되는 내용도 많아서 재밌게 잘 읽었습니다 🙃

2023-04-25 07:03 UTC, merged