[레벨 1 글쓰기 미션] 토마스(김대현) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #138
Opened 2023-03-20 08:22 UTC by ki960213

안녕하세요, 핑구, 로건, 하디, 윤생, 말랑, 엽토! 안드로이드 5기 크루 토마스입니다.
쓰고 보니 정말 재미없네요. 그래도 열심히 썼습니다ㅠㅠ
잘 부탁드립니다!

2023-03-20 14:56 UTC, 2yunseong reviewed
토마스 안녕하세요! 윤생입니다!

간단히 리뷰 남겨보았습니다! 중요한 건 꺾이지 않는 마음입니다! 화이팅!!

2023-03-20 14:56 UTC, 2yunseong commented on README.md
> +우테코 생활을 하면서 나는 인내심이 낮다는 것을 깨달았다. 학창시절 훈련도 해보았고, 운동도 꾸준히 했기 때문에 인내심이 강한 사람인 줄 알았다. 페어 프로그래밍을 하고 나면 힘들어서 생각할 에너지가 없는 것을 느끼며 생각했다. ＂나는 온실 속의 화초였구나.＂ 앞으로는 이전의 나태했던 나 자신을 속죄하며 힘들어도 참고 견뎌야겠다.
어떤 훈련을 하셨나요??? 궁금해요!!

2023-03-20 14:56 UTC, 2yunseong commented on README.md
> +우테코 중 페어 프로그래밍을 했다. 코드 한 줄 한 줄 작성할 때마다 팀원과 의견을 맞춰보아야 했다. 의견을 맞춰보아야 하므로 코드를 작성하기 전에 페어와 설계에 대해 토론을 해야 했다. 레벨 1의 미션들은 크게 복잡하지 않아서 코드로 작성하고 나서 보여주고 싶었다. 코드를 보여주며 설명하는 편이 더 수월하기 때문이다. 하지만 소프트 스킬을 향상하고 싶었
`맞춰보아야` -> `맞춰야` 어떠신가요?

2023-03-20 14:56 UTC, 2yunseong commented on README.md
> +취업 준비하면서 코딩테스트와 cs 지식을 공부했다. 또한 객체지향 프로그래밍, 도메인 주도 설계, 테스트 코드 작성 방법 등을 공부했다. 그러면서 코드의 가독성과 설계에 관심이 생겼다. 인턴을 하면서 팀원들과 이 부분에 관해 토론했다. 빨리 현업자의 코드를 보거나 의견을 듣고 싶었다. 그러던 중 우테코에 합격했다. 안드로이드 분야에 지원한 이유는 현재 백
흥미 굉장히 중요하죠!

2023-03-20 15:55 UTC, shin-mallang commented on README.md
> +취업 준비하면서 코딩테스트와 cs 지식을 공부했다. 또한 객체지향 프로그래밍, 도메인 주도 설계, 테스트 코드 작성 방법 등을 공부했다. 그러면서 코드의 가독성과 설계에 관심이 생겼다. 인턴을 하면서 팀원들과 이 부분에 관해 토론했다. 빨리 현업자의 코드를 보거나 의견을 듣고 싶었다. 그러던 중 우테코에 합격했다. 안드로이드 분야에 지원한 이유는 현재 백
```suggestion
우테코에 합격하기 전에 나는 취업을 준비하면서 코딩테스트와 cs 지식을 공부했다.
또한 객체지향 프로그래밍, 도메인 주도 설계, 테스트 코드 작성 방법 등을 공부했다.
자연스레 코드의 가독성과 설계에 관심이 생겼다. 
이전에 나는 (~~에서 ~~ 인턴을 했었는데,) 인턴을 하면서 팀원들과 이러한 부분에 관해 토론을 나누었다.
(??? ->) 빨리 현업자의 코드를 보거나 의견을 듣고 싶었다. 
그러던 중 우테코에 합격했다. 

안드로이드 분야에 지원한 이유는 현재 백엔드 개발자가 되려는 사람이 많다고 생각했다. (무슨 상관인지 조금 더 자세히 설명해주시면 좋을 것 같아요)

그리고 이전 인턴 경험을 통해 클라이언트 분야도 재미있다는 것을 깨달았기 때문이다. 
(이전 인턴 경험이 뭐였는지 나와있지 않아요!, 이에 대한 설명도 추가해주시면 좋을 것 같아요)

그래서 전망과 흥미를 고려해 안드로이드 분야에 지원했다.
(전망은 빼고, 내가 안드로이드에 흥미가 있었다는 것을 조금 더 드러내면 좋을 것 같아요)

 사실 어떤 분야든 내가 잘하면 전망이 좋다고 생각했다. 
 그래서 좀 더 재미있는 분야의 개발자가 되고 싶었다.
 (이부분도 마찬가지로 안드로이드 개발에 대한 흥미가 조금 더 드러나면 좋겠습니다.)
```

2023-03-20 16:00 UTC, shin-mallang reviewed
조금 어색한 부분을에 대해서 언급했습니다!!

같이 힘내서 우테코 잘 지내봐요!!

2023-03-20 16:00 UTC, shin-mallang commented on README.md
> +취업 준비할 때는 새로운 사람을 만날 일이 거의 없었다. 그래서 사회생활에 대해 불안해했다. 또한, 내가 이렇게 오랫동안 취업 준비를 할지 몰랐다. 그래서 이것에 대한 자격지심도 있었다. 취업 준비를 1년 반이나 했고 나이도 꽤 많이 먹었는데 아직도 취업을 못해서 뒤처져 있다는 느낌이 들었다. 하지만 우테코 생활을 하면서 나의 취업 준비 기간이 헛되지 않
```suggestion
취업 준비할 때는 새로운 사람을 만날 일이 거의 없었다. 그래서 사회생활에 대해 불안해했다. 
(새로운 사람을 만날 일이 없어서 사회생활이 불안했단건가요?)


(또한, 내가 이렇게 오랫동안 취업 준비를 할지 몰랐다. 그래서 이에 대한 자격지심도 있었다. ) -> 아래 문장이랑 중복 느낌이라 없어도 될 것 같아요 

취업 준비를 1년 반이나 했고 나이도 꽤 많이 먹었는데 아직도 취업을 못해서 뒤처져 있다는 느낌이 들었다. 하지만 우테코 생활을 하면서 나의 취업 준비 기간이 헛되지 않았다고 느꼈다. 레벨 1의 수업은 대부분 취업 준비하면서 봤던 것들이었다. 
내가 취업 준비하면서 했던 고민이 레벨 1의 미션에서 도움이 되었다. 그래서 흔들리지 않고 해야 할 것을 우직하게 해나간다면 좋을 것 같다고 생각했다. 
```

2023-03-21 04:38 UTC, yeopto requested changes
안녕하세요 토마스~ 엽토라고 합니다!

글 잘 읽었습니다~ 자신을 돌아보는 내용이 있어서 인상 깊었던 것 같습니다!

다른 분들이 수정사항들을 너무 잘 작성해주셔서 저는 딱히 없는 것 같아요😀
어떤 말인지 알쏭달쏭한 문장이 있어서 하나 정도 있었는데요! 코멘트 남겼습니다
토마스는 어떻게 생각하는지 말씀해주시면 감사하겠습니다!

2023-03-21 05:45 UTC, otter66 commented
토마스의 글 잘 읽었습니다!!! 멋있다 토마스~~~!!!

2023-03-21 08:05 UTC, jundonghyuk approved these changes
안녕하세요 하디입니다.
글이 전반적으로 가독성이 좋네요:)

앞으로의 다짐 부분에 조금 긍정적으로(?) 작성하면 더 좋을 것 같아요!

2023-03-21 12:25 UTC, pingu244 reviewed
토마스 안녕하세요!

글 잘 읽었습니다😊
크게 수정할 부분은 보이지 않아 제가 느끼기에 어색한 부분 하나 코멘트 남겼습니다.

우테코 이전의 걱정들과 과정 중에 느낀 생각들이 진솔하게 잘 드러난 것 같아요!
앞으로도 같이 화이팅해봐요~!ㅎㅎ

2023-03-26 04:28 UTC, shin-mallang approved these changes

2023-03-26 07:14 UTC, ki960213 commented on README.md
> +우테코 생활을 하면서 나는 인내심이 낮다는 것을 깨달았다. 학창시절 훈련도 해보았고, 운동도 꾸준히 했기 때문에 인내심이 강한 사람인 줄 알았다. 페어 프로그래밍을 하고 나면 힘들어서 생각할 에너지가 없는 것을 느끼며 생각했다. ＂나는 온실 속의 화초였구나.＂ 앞으로는 이전의 나태했던 나 자신을 속죄하며 힘들어도 참고 견뎌야겠다.
100m 달리기 훈련했습니다. 약 2달 정도 했습니다!

2023-03-26 07:16 UTC, ki960213 commented on README.md
> +우테코 중 페어 프로그래밍을 했다. 코드 한 줄 한 줄 작성할 때마다 팀원과 의견을 맞춰보아야 했다. 의견을 맞춰보아야 하므로 코드를 작성하기 전에 페어와 설계에 대해 토론을 해야 했다. 레벨 1의 미션들은 크게 복잡하지 않아서 코드로 작성하고 나서 보여주고 싶었다. 코드를 보여주며 설명하는 편이 더 수월하기 때문이다. 하지만 소프트 스킬을 향상하고 싶었
더 좋은 것 같습니다!

2023-03-26 07:17 UTC, ki960213 commented on README.md
> +취업 준비하면서 코딩테스트와 cs 지식을 공부했다. 또한 객체지향 프로그래밍, 도메인 주도 설계, 테스트 코드 작성 방법 등을 공부했다. 그러면서 코드의 가독성과 설계에 관심이 생겼다. 인턴을 하면서 팀원들과 이 부분에 관해 토론했다. 빨리 현업자의 코드를 보거나 의견을 듣고 싶었다. 그러던 중 우테코에 합격했다. 안드로이드 분야에 지원한 이유는 현재 백
프로젝트에 백엔드 개발자로서 참여하려 해도 대부분 자리가 없었어요.ㅠㅠ 그래서 그렇게 생각했습니다!

2023-03-26 08:19 UTC, yeopto approved these changes
토마스! 리뷰 반영 확인했습니다~~!

지금처럼 열심히 하신다면,
남은 8개월 후에는 토마스가 원하는 결과를 얻으실 수 있을거라 생각합니다! 

Level1 얼마 남지 않았는데 마지막까지 화이팅입니다!
고생하셨어요! 이만 approve할게요!

2023-03-26 08:35 UTC, 2yunseong approved these changes
고생하셨습니다! 저는 이만 appove 하겠습니다!!

2023-03-26 10:18 UTC, pingu244 approved these changes
피드백 반영해주신 부분 확인했습니다~!
더는 피드백 해드릴 부분이 보이지 않아 이만 approve 하겠습니다.
앞으로도 지금까지 했던 것처럼 잘 견뎌내봅시다!!💪

2023-03-26 15:39 UTC, 70825 approved these changes
안녕하세요 토마스!
모든 글쓰기 미션을 리뷰한줄 알았는데, 토마스 리뷰를 확인 못했었네요. 죄송합니다 😭
다른 분들이 수정할만한 부분은 다 수정해서 간단한 코멘트만 남겼습니다!
남은 미션도 화이팅입니다!

2023-03-26 15:39 UTC, 70825 commented on README.md
> +그래서 내게 좀 더 친숙한 안드로이드 분야에 지원했다.
엄청 다양한 분야를 도전하셨네요!

2023-03-26 15:39 UTC, 70825 commented on README.md
> +"개발자에게 어떤 것이 더 나은지 논리적으로 설명할 수 있는 능력은 매우 좋은 능력이다"라고.
좋은 문장이네요 👍

2023-04-25 07:00 UTC, gracefulBrown approved these changes
👍

2023-04-25 07:00 UTC, merged