[조이] 레벨1 글쓰기 제출합니다.
woowacourse/woowa-writing-5 pull request #15
Opened 2023-03-13 13:54 UTC by yeonkkk

2023-03-14 02:04 UTC, beer-2000 requested changes
안녕하세요 조이~!
군더더기 없는 글이라 뭘 수정하면 좋을지 모르겠네요!
고민도 담기고 감상도 담겨서, 여러모로 공감하면서 재밌게 읽을 수 있었네요.
리뷰인지 감상평인지 모를 코멘트들도 몇 개 남겨두었으니 참고만 해주시고,
다가올 체스 미션도 파이팅하세요 ! 👍
(수정할 내용이 크지 않다 판단해서 Approve하고 싶지만, 미션 설명에 1회 Request change 후 Approve하는 것으로 나와 있다고 이해했습니다. 그래서 Request change 보냄을 양해부탁드려요 :)  )

2023-03-14 02:04 UTC, beer-2000 commented on Level1.md
> +시작할 때는 추운 겨울이었는데 벌써 봄의 초입에 있다.
표현이 너무 예쁘네요!

2023-03-14 02:04 UTC, beer-2000 commented on Level1.md
> +이미 흘러간 시간은 붙잡을 수 없으니, 기억이라도 글자로 눌러 써서 잡아보려고 한다.
완전 공감합니다..

2023-03-14 02:04 UTC, beer-2000 commented on Level1.md
> +그렇게 한 달 동안 인사 봇이 되었다.
ㅋㅋㅋㅋ 왜 저는 인사를 못 받아본 것 같죠ㅜ ..

2023-03-14 02:04 UTC, beer-2000 commented on Level1.md
> +인간 관계 뿐만 아니라 캠퍼스 생활이 고등학교 생활과 유사하다고 느껴졌다.
ㅋㅋㅋㅋ그니까요 재밌습니다 아주~

2023-03-14 02:04 UTC, beer-2000 commented on Level1.md
> +다른 크루들과 함께하고 알아가는 과정에서 나에 대해서도 알아가게 된다.
오 맞아요.. 사람들 속의 나에 대해서도 생각을 많이 하게 되는 것 같아요

2023-03-14 02:04 UTC, beer-2000 commented on Level1.md
> +‘우테코에서 이런 메타 인지 향상을 꾀하고 우리에게 은밀하게 환경을 제공하는 것은 아닐까?’ 하는 생각도 든다.
이 문장이 조금 이해하기 어렵게 느껴졌어요!
쉼표로 끊거나, 문장을 분리하거나 등.. 조금 더 이해하기 쉬우면 좋을 것 같다는 생각이 들었습니다!

2023-03-14 02:06 UTC, beer-2000 approved these changes

2023-03-17 07:57 UTC, rawfishthelgh commented on Level1.md
> +이미 흘러간 시간은 붙잡을 수 없으니, 기억이라도 글자로 눌러 써서 잡아보려고 한다.
시인인 줄 알았습니다

2023-03-18 07:34 UTC, wugawuga reviewed
안녕하세요 조이 🤗 우가입니다 ㅎㅎ

글이 너무 깔끔해서 제 생각을 조금 적어보았습니다. 너무 재밌게 읽었어요 감사합니다

2023-03-20 07:43 UTC, re4rk reviewed
공감가는 부분들이 많아서 재밌게 잘 읽은 것같습니다!
좋은 글 남겨주셔서 감사합니다!

2023-03-20 07:43 UTC, re4rk commented on Level1.md
> +고등학생 때 이후로는 이런 관계를 만들기 힘들다고 생각했는데 여기서는 가능한 것 같아서 신기하다.
이 부분 많은 공감이 가는 것 같습니다!!

2023-03-20 07:43 UTC, re4rk commented on Level1.md
> +모르는 것을 말하기 부끄러웠는데 이제는 모르는 것을 말하지 못하는 게 더 부끄러운 것 같다.
이 부분도 제가 우테코를 하면서 크게 느낀 부분인 것같습니다!

2023-03-20 14:25 UTC, seokjin8678 commented
안녕하세요 조이!
이미 제출하신 걸 뒤늦게 봤네요 ㅠㅠ
글을 담백하게 잘 쓰셔서 재밌게 잘 읽었어요!
그래서 그런지 피드백 할 부분은 제가 찾지 못했네요..
다른 분들 피드백을 주신걸 보면 전부 꼼꼼하게 해주셔서 죄송하네요 ㅋㅋ..

2023-03-20 14:25 UTC, seokjin8678 approved these changes

2023-03-20 14:25 UTC, seokjin8678 commented on Level1.md
> +그런데 지금은 온보딩 조, 레벨1 데일리 조 모두 가족 같이 편하다.
동감합니다 👍

2023-03-21 05:19 UTC, yeonkkk commented on Level1.md
> +그렇게 한 달 동안 인사 봇이 되었다.
ㅋㅋㅋㅋ아마도 못 만났던 것 같아요🥲

2023-03-21 13:06 UTC, jeomxon approved these changes
안녕하세요 조이 :) 저문입니다.
전반적으로 글을 깔끔하게 작성해주셔서 따로 코멘트를 달 부분이 거의 없네요~
많은 생각을 하시면서 지낸다는 것을 엿볼 수 있는 글이었습니다 ㅎㅎ
좋은 글 잘 읽고 갑니다!

2023-03-21 16:51 UTC, no1msh approved these changes
안녕하세요 `조이`! 안드로이드의 `반달`입니다. 
아마 제일 `우아한테크코스 한 달 생활기`라는 주제에 적합한 글이지 않나 생각합니다. 저 또한 우테코를 다니게 되면서 한 생각들인데 이렇게 정리가 되어있으니 신기할 따름입니다. 글 너무 잘 보았고요. 특별히 수정 사항 말씀드릴 게 없는 글이었네요! 잘 읽고 갑니다!

2023-03-22 04:41 UTC, yeonkkk commented on Level1.md
> +본인에 대해서 아는 것이 생각보다 어려운 일인데 자연스럽게 알게 되는 것이 신기하다.
안녕하세요 우가!
피드백 해주신 내용 반영하였습니다. 
혹시 추가로 수정해야 할 부분이 있다면 말해주세요!

없다면 approve 부탁드립니다🙂

2023-03-22 04:42 UTC, yeonkkk commented on Level1.md
> +모르는 것을 말하기 부끄러웠는데 이제는 모르는 것을 말하지 못하는 게 더 부끄러운 것 같다.
안녕하세요 아크!
공감해주셔서 감사합니다 ㅎㅎ
혹시 수정해야 할 부분이 있다면 말해주세요!

없다면 approve 부탁드립니다🙂

2023-03-25 11:16 UTC, re4rk commented
다른 분들의 피드백한 것들을 읽어봤습니다! 좋은글 써주셔서 감사합니다!

2023-03-25 11:17 UTC, re4rk approved these changes
다른 분들의 피드백을 반영한 것들을 읽어보았습니다! 좋은 글 써주셔서 감사합니다!

2023-04-25 07:11 UTC, gracefulBrown approved these changes
👍

2023-04-25 07:11 UTC, merged