[레벨 2 글쓰기 미션] 에이든(박경현) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #185
Opened 2023-05-16 15:48 UTC by gyeongza

안녕하세요 ~ `윤생`, `해온`, `둘리` 

에이든입니다!

지난번 글쓰기 워크숍 때 정했던 주제와 같이 `우테코 전의 삶에 대한 회고`에 대한 글을 써보았습니다!

많이 부족한 글이지만 잘 부탁드립니다 :)

### [👀 글 편하게 읽기](https://github.com/gyeongza/woowa-writing-5/blob/gyeongza/level2.md)

2023-05-17 01:25 UTC, pobiconan commented
에이든보다 삶을 쬐금(?) 더 살아보니 우리 삶에 있어서 의미없는 경험은 없더라고요.
아니 어떤 경험이든 찐하게 몰입한 경험은 삶을 살아가는데 긍정적인 효과가 나는 경험을 많이 했어요.
지금까지의 에이든의 경험도 긍정적으로 다가올 것 같은 느낌이 드네요.

2023-05-19 12:10 UTC, 2yunseong reviewed
안녕하세요 에이든~ 초안 잘 읽었습니다!

모르고 레벨1 문서도 읽었는데 쭉 이어지는 느낌이라 몰입하면서 읽었습니다! 

주말 잘 보내세요!

2023-05-19 12:10 UTC, 2yunseong commented on level2.md
> +사용자가 어떻게하면 불편함을 겪지 않고 서비스를 이용할 수 있는가에 대한 고민도 많이 했습니다.
추가로 FE가 천직이시군요!ㅋㅋ

2023-05-19 12:10 UTC, 2yunseong commented on level2.md
> +### 지난 시간에 후회하며 보낸 일은 없습니다.
요건 어떠신지요!
```suggestion
### 지난 시간을 후회하며 보낸 적은 없습니다.
```

2023-05-22 04:44 UTC, hyemdooly commented on level2.md
> +하지만 누군가가 저에게 "무슨 일 하세요?" 라고 물어보면 저는 항상 어려움을 겪었습니다.
```suggestion
하지만 누군가가 "무슨 일 하세요?" 라고 물어보면 저는 항상 어려움을 겪었습니다.
```
저에게, 저는 이라는 '나'의 의미가 많이 들어가있어서 하나는 지워도 좋을 것 같습니다!

2023-05-22 04:58 UTC, hyemdooly requested changes
안녕하세요, 에이든! 전체적으로 문장을 짧게 끊어주셔서 읽기 편했습니다☺️
하던 일을 관두고 프론트엔드 개발자가 되기 위해 공부하는 모습이 대단하게 느껴지네요.ㅎㅎ
창업 경험에 대한 이야기가 흥미로웠습니다.
더 코멘트 드리고 싶었지만 윤생과 거의 동일해서 이번 리뷰는 여기까지 하겠습니다!

2023-05-22 04:58 UTC, hyemdooly commented on level2.md
> +하지만 누군가가 저에게 "무슨 일 하세요?" 라고 물어보면 저는 항상 어려움을 겪었습니다.
```suggestion
하지만 누군가가 "무슨 일 하세요?" 라고 물어보면 저는 항상 어려움을 겪었습니다.
```
저에게, 저는 이라는 '나'의 의미가 많이 들어가있어서 하나는 지워도 좋을 것 같습니다!

2023-05-22 12:24 UTC, hae-on reviewed
안녕하세요 에이든!
문장의 길이가 짧고 잘 나누어져 있어서 금방 읽어내려갈 수 있었습니다~~
다른 크루들이랑 달리 경어체로 쓰여져 있어 더 신선했어요!
특히 제목에 이모지가 제목에 맞아서 재미있었습니다 ❗️❓
다양한 경험을 해본 에이든 부러워요~~

2023-05-22 12:24 UTC, hae-on commented on level2.md
> +그래서 이 글을 통해 우테코에 들어오기 전의 저의 삶을 되돌아보고, 저에게 어떤 변화가 있었는지 정리해보고자 합니다.
여기에 `저에게`가 없어도 좋을 거 같습니다!

2023-05-22 12:24 UTC, hae-on commented on level2.md
> +창업을 하기도 했고 기획자와 디자이너로서의 역할도 해왔습니다.
다재다능하시군여 😎

2023-05-22 12:24 UTC, hae-on commented on level2.md
> +다양한 일을 하면서 느낀 공통점은 저는 무언가를 만들어내는 것에 대해 큰 성취감을 느낀다는 것이었습니다.
`무언가를 만들어내는 것` 이부분에 볼드처리를 하는건 어떠신가요?!?!

2023-05-22 12:24 UTC, hae-on commented on level2.md
> +창업을 할 당시 저는 골프 프로와 회원을 연결해주는 플랫폼 서비스를 기획하였습니다.
위 두줄에도 `저는`이 있어서 이 문장에서는 `저는`을 빼도 좋을 것이라 생각합니다!

2023-05-23 06:39 UTC, gyeongza commented on level2.md
> +사용자가 어떻게하면 불편함을 겪지 않고 서비스를 이용할 수 있는가에 대한 고민도 많이 했습니다.
ㅋㅋㅋㅋㅋ 직접 해보니 쉽지 않네요

2023-05-23 06:48 UTC, gyeongza commented on level2.md
> +함께 성장하면서, 저만의 전문성을 더욱 키워나갈 수 있도록 노력하고 또 노력할 것입니다.
넵! 남은 기간 동안 화이팅입니다 !!

2023-05-23 06:49 UTC, gyeongza commented on level2.md
> +하지만 **어떤 일을 하고 싶은지**에 대해서 새로운 목표가 생겼습니다.
맞습니다,, ㅎㅎ

2023-05-23 06:51 UTC, gyeongza commented on level2.md
> +창업을 하기도 했고 기획자와 디자이너로서의 역할도 해왔습니다.
메뉴가 너무 많은 집은 음식이 맛이 없다라는 소문이..

2023-05-27 15:02 UTC, hyemdooly approved these changes

2023-05-30 08:39 UTC, whk06061 commented
에이든 수정하신 글 잘 봤습니다! 더 이상 수정할 부분이 보이지 않아 approve 하겠습니다👍

2023-09-25 07:14 UTC, gracefulBrown approved these changes

2023-09-25 07:14 UTC, merged