[레벨 2 글쓰기 미션] 황펭(양이진) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #213
Opened 2023-05-19 00:55 UTC by Leejin-Yang

엽토, 애슐리, 반달 안녕하세요!

호롱이와 함께하면서 든 생각을 작성해 보았습니다.
리뷰 잘 부탁드립니다 👍

2023-05-19 01:51 UTC, hae-on commented
你好。我读了你的文章。 真是感人的文章啊。

2023-05-19 04:55 UTC, HyeryongChoi commented
好文章，王峰。 企鹅有猫真是太神奇了。👍

2023-05-21 10:22 UTC, ashleysyheo requested changes
안녕하세요 황펭 😊 애슐리입니다! 

글 잘 읽었습니다! 호롱이 너무 귀여워요!!!! 그리고 글에서 읽은 것만으로도 정말로 독특하고 재미있는 고양이라는 것이 느껴졌어요. 전체적으로 기승전결 흐름이 smooth하게 쫘아악 이루어져서 좋았습니다.

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +고양이 좋아하시나요? 고양이를 키우고 싶나요? 저는 지난 일년 반동안 고양이 호롱이와 함께 했습니다.
위에 제목이 다시 한 번 나와도(?) 좋을 것 같아요. `고양이 좋아하시나요? 고양이를 키우고 싶나요? 고양이 키우는 것, 쉽지 않습니다...`이렇게요?!

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +이사를 가게 되어 현재 호롱이는 본가에 있지만, 호롱이와 함께 하면서 든 생각이 많아 글을 적어봅니다.
여기서는 존댓말을 사용하다가 아래서는 안 사용하는 이유가 있나요? 🤔

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +
고양이 너무 귀여워요!!! 😂

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +## 호롱이랑 생활하기
제목에서 호롱이가 고양이 아닌 고양이(?)라는 것을 알려주는 것도 좋을 것 같아요! `호롱이랑 생활하기: (some 부제)`?

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +
백번 말하는 것보다는 역시 사진이죠 ㅋㅋㅋㅋ

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +호롱이는 어디에도 비집고 들어가지 않는다. 이 사진들 또한 직접 놓은 호롱이다. 그렇지 않으면 절대 들어가지 않는다. 이 때문인지 몰라도 화장실에도 들이지 않으면 들어가지 않는다. 그리고 한번 들이면 절대 나오지 않는다. 사진을 보면 꺼내달라는 불만 가득한 표정이다.
엄청 독특한 고양이네요 ㅋㅋㅋㅋㅋ

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +호롱이에게 밥은 무엇인가? 잘 모르겠다. 한 번 밥을 먹기 시작하면 5시간 정도 먹을 때도 있고, 사진과 같이 주먹밥을 만들 때도 있다. 밥을 정상적으로 먹은 적이 없는 것 같다. 조금씩 먹여주어야 정상적으로 먹는다. 호롱이에게 밥은 장난감일까? 아직도 잘 모르겠다.
저희 집 강아지들이랑 비슷한 거 같네요 ㅋㅋ

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +
마치 강아지를 키우는 듯한 느낌이군요 😂 그래도 산책은 안 시켜도 된다...?

2023-05-21 10:22 UTC, ashleysyheo commented on level2.md
> +만약 고양이를 키우고 싶은 마음이 있다면, 신중하게 생각하고 결정했으면 한다.
결말 좋아요! 기승전결이 딱딱 맞는 것 같아서 좋았습니다.

2023-05-22 11:44 UTC, yeopto requested changes
왕펑~
글 잘 읽었습니다~
평소에 호롱이 이야기를 많이 듣기도하고, 글 내용보니 호롱이는 참 독특한 것 같아요.
근데 그만큼 귀엽네요 ㅋㅋㅋ

반려묘 키울 사람들에게 도움이 될 글이네요.
기승전결 좋습니다!

간단하게 바꿔보면 어떨까 싶은 것에 대해 코멘트 남겼습니다~
확인해주십쇼~

2023-05-22 11:44 UTC, yeopto commented on level2.md
> +이사를 가게 되어 현재 호롱이는 본가에 있지만, 호롱이와 함께 하면서 든 생각이 많아 글을 적어봅니다.
애슐리말에 한표~

2023-05-22 11:44 UTC, yeopto commented on level2.md
> +대학 생활이 끝나고 정들었던 동네를 떠났다. 새로운 동네에서 반려동물에 대한 마음이 다시 살아났다. 매일 잠들기 전 유기 동물 홈페이지를 확인하고, 고양이 관련 유튜브를 시청했다. `21년 6월 7일` 드디어 마음을 먹고 밖을 나선다. 경기도 부천에 도착해 호롱이와 처음 마주한다. 1개월 된 아기 고양이를 처음 품에 안았을 때, 이만큼 소중하고 사랑스러운
감격의 순간이군요..

2023-05-22 11:44 UTC, yeopto commented on level2.md
> +호롱이는 어디에 올라가는 것도 내려가는 것도 못 한다. 호롱이를 위해 캣타워를 장만했지만, 캣타워에 스스로 올라간 적이 없다. 그래서 올려두면 내려오기 위해 안간힘을 쓰지만 한 번도 내려온 적이 없다. 이런 기괴한 포즈를 볼 수 있다. 하지만 좋은 점도 있다. 호롱이가 뛰어다닐 때, 캣타워에 올려두면 진정이 된다.
고양이가 막 뛰어다니기도 하는군요?

2023-05-22 11:44 UTC, yeopto commented on level2.md
> +### 밥에 대한 생각을 모르겠는 고양이다.
제목을 `호롱이에게 밥이란?`으로 바꿔보면 더 재밌어질것같은데 어떤가요 왕펑~

다른 제목들도 마찬가지입니당

2023-05-22 13:05 UTC, no1msh approved these changes
전체적으로 읽기 편하게 구성되어 있고 사진도 있어 보기 좋았습니다.!
고양이 너무 귀여워요 ㅎ🐱

2023-05-22 13:05 UTC, no1msh commented on level2.md
> +대학 생활이 끝나고 정들었던 동네를 떠났다. 새로운 동네에서 반려동물에 대한 마음이 다시 살아났다. 매일 잠들기 전 유기 동물 홈페이지를 확인하고, 고양이 관련 유튜브를 시청했다. `21년 6월 7일` 드디어 마음을 먹고 밖을 나선다. 경기도 부천에 도착해 호롱이와 처음 마주한다. 1개월 된 아기 고양이를 처음 품에 안았을 때, 이만큼 소중하고 사랑스러운
어 저 부천 삽니다 ㅎㅎ 반갑군요

2023-05-22 13:05 UTC, no1msh commented on level2.md
> +만약 고양이를 키우고 싶은 마음이 있다면, 신중하게 생각하고 결정했으면 한다.
귀여운 모습 그런 것만 보고 입양하고 싶다는 생각을 가진 사람이 많던데 황펭 말대로 신중하게 생각했으면 좋겠네요 ㅎㅎ

2023-05-28 15:23 UTC, Leejin-Yang commented on level2.md
> +### 밥에 대한 생각을 모르겠는 고양이다.
오 사실 소제목을 어떻게 할지 고민이었는데
좋은 의견 감사해요 😊

2023-05-28 15:28 UTC, Leejin-Yang commented on level2.md
> +호롱이에게 밥은 무엇인가? 잘 모르겠다. 한 번 밥을 먹기 시작하면 5시간 정도 먹을 때도 있고, 사진과 같이 주먹밥을 만들 때도 있다. 밥을 정상적으로 먹은 적이 없는 것 같다. 조금씩 먹여주어야 정상적으로 먹는다. 호롱이에게 밥은 장난감일까? 아직도 잘 모르겠다.
애슐리네 강아지도 밥을 재밌게(?) 먹나 보네요 😅

2023-05-28 15:38 UTC, Leejin-Yang commented on level2.md
> +이사를 가게 되어 현재 호롱이는 본가에 있지만, 호롱이와 함께 하면서 든 생각이 많아 글을 적어봅니다.
의문문을 작성하는데 반말로 하면 좀 그래서.. 서론은 존댓말로 작성했어요 😅
질문과 아래 내용을 분리해 보았습니다.!

2023-05-28 16:29 UTC, Leejin-Yang commented on level2.md
> +대학 생활이 끝나고 정들었던 동네를 떠났다. 새로운 동네에서 반려동물에 대한 마음이 다시 살아났다. 매일 잠들기 전 유기 동물 홈페이지를 확인하고, 고양이 관련 유튜브를 시청했다. `21년 6월 7일` 드디어 마음을 먹고 밖을 나선다. 경기도 부천에 도착해 호롱이와 처음 마주한다. 1개월 된 아기 고양이를 처음 품에 안았을 때, 이만큼 소중하고 사랑스러운
오 부천 사람이시군요!
사실 전 인천 사람입니다 😅

2023-05-28 16:32 UTC, Leejin-Yang commented on level2.md
> +고양이 좋아하시나요? 고양이를 키우고 싶나요? 저는 지난 일년 반동안 고양이 호롱이와 함께 했습니다.
좋은 의견 감사합니다~!

2023-05-29 12:48 UTC, ashleysyheo approved these changes

2023-05-29 13:55 UTC, yeopto approved these changes

2023-05-30 08:16 UTC, gyeongza approved these changes
황펭 피드백 반영한 글 잘 봤습니다~

2023-09-25 07:12 UTC, gracefulBrown approved these changes

2023-09-25 07:12 UTC, merged