[레벨 2 글쓰기 미션] 오도(문민혁) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #233
Opened 2023-05-19 05:32 UTC by odo27

안녕하세요! 오도입니다 ☺️
저번에 함께 얘기했던 목차를 바탕으로 글쓰기 진행해봤습니다~
리뷰 잘 부탁드립니다! 😁

2023-05-20 05:48 UTC, Choi-JJunho reviewed
낯선 스프링과 친해질 수 있는 과정을 배워갑니다 👍
잘보고갑니다 🏃💨

2023-05-22 10:22 UTC, jundonghyuk approved these changes
안녕하세요 오도! 하디입니다.
글 잘 읽었어요. 오도의 스프링 학습 과정에서 겪은 어려움이 저도 많이 공감이 됩니다:)

코멘트 남겼으니 확인 부탁드릴게요 !

2023-05-22 10:22 UTC, jundonghyuk commented on LEVEL2.md
> +처음부터 스프링의 원리와 동작 방식을 완벽히 이해하려고 하지 않고, 우선은 돌아가는 기능을 구현하는 데에 초점을 두기로 했습니다.
`우선은 기능작동에 초점을 두어 구현하기로 다짐했습니다`는 어떠신가요 !?
(개인적인 생각입니다..ㅋㅋ)

2023-05-22 10:22 UTC, jundonghyuk commented on LEVEL2.md
> +학습 테스트를 먼저 하자는 페어의 제안에 학습 테스트를 먼저 구현하게 되었습니다.
`하지만`과 같은 단어를 붙이는건 어떨까요 ?
`구현부터 하려했다.` -> `페어의 제안에 학습테스트를 먼저 구현했다.`가 자연스럽게 이어지면 좋을 것 같아요.

2023-05-22 10:22 UTC, jundonghyuk commented on LEVEL2.md
> +특히 테스트 작성에서 어려움을 겪었는데 테스트를 어떻게 구성해야 하는지에 대한 감이 없었고, 각 계층에서의 테스트 작성 방법을 몰라서 막막함을 느꼈습니다.
테스트 작성에서 막막함을 느낀게 공감이 되네요...:)
(저도 많이 막혔습니다,,)

2023-05-23 00:30 UTC, MoonJeWoong requested changes
안녕하세요 오도! 히이로입니다.

전체적으로 많이 공감하면서 읽을 수 있었던 글이었습니다. 아마 저희가 레벨2를 진행하면서 공통적인 어려움을 함께 겪었기 때문이 아닐까 싶네요 ㅎㅎ

아직 최종 피드백이 아니기 때문에 최대한 가볍게 코멘트를 남겨봤습니다. 남은 얘기는 글쓰기 워크숍 데이2때 더 해봐요~ 😄

2023-05-23 00:30 UTC, MoonJeWoong commented on LEVEL2.md
> +그렇게 미션 제출에만 초점을 두고 진행했음에도 쉽지만은 않았습니다.
포기할 거 포기한다고 하더라도 미션이 쉬워지지는 않더라구요... ㅎㅎ 격하게 공감합니다!

2023-05-23 00:30 UTC, MoonJeWoong commented on LEVEL2.md
> +시간이 부족하면 어쩌냐는 걱정이 있었지만, 학습 테스트를 먼저 진행한 것이 더 빠른 길이었음을 미션을 진행한 후 깨닫게 되었습니다.
```suggestion
시간 부족에 대한 걱정이 있었지만, 학습 테스트를 먼저 진행한 것이 더 빠른 길이었음을 미션을 진행한 후 깨닫게 되었습니다.
```

요 쉼표 앞 문장을 좀 더 자연스럽게 바꿔보았습니다...!

---
이 부분도 정말 많이 공감가는 부분이네요! 
학습테스트를 통해 필요한 스프링의 기능과 친숙해진 상태로 미션을 진행하는게 가장 빠른 길이었던 것 같아요.

2023-05-23 00:30 UTC, MoonJeWoong commented on LEVEL2.md
> +시간이 부족하면 어쩌냐는 걱정이 있었지만, 학습 테스트를 먼저 진행한 것이 더 빠른 길이었음을 미션을 진행한 후 깨닫게 되었습니다.
전체적으로 해당 문단은 스프링을 학습하면서 오도가 느낀 문제점이나 어려움을 제기하는 것이 중심이라고 생각이 듭니다. 그런데 페어프로그래밍을 통해 학습테스트를 진행해서 미션 진행에 원활함을 느낄 수 있었던 것은 어떻게 보면 오도가 찾으신 해결책에 더 가까울 것 같다는 생각이 들었어요. 그래서 해당 내용을 뒷 문단으로 넣으시고 여기에서는 어려움에 조금 더 초점을 맞춰서 얘기를 해보시는 건 어떠실지 제안드려봅니다!

2023-05-23 12:24 UTC, Songusika commented on LEVEL2.md
> +또한 내가 빠르게 습득하기 위해 감으로만 알고 있던 개념에 대해 명확히 이해할 기회가 된다는 것입니다.
좋은 팁 감사합니다 오도!
확실히 감으로만 알고 있던 개념을 책이나, 전문가를 통해 짚고 넘어가면 더 오래 기억에 남는거 같아요!

2023-05-30 06:06 UTC, odo27 commented on LEVEL2.md
> +처음부터 스프링의 원리와 동작 방식을 완벽히 이해하려고 하지 않고, 우선은 돌아가는 기능을 구현하는 데에 초점을 두기로 했습니다.
너무 좋습니다~ 반영했습니다 😊

2023-05-30 06:10 UTC, odo27 commented on LEVEL2.md
> +학습 테스트를 먼저 하자는 페어의 제안에 학습 테스트를 먼저 구현하게 되었습니다.
반영했습니다! 추가하니 글이 더 자연스럽게 읽히네요~

2023-05-30 06:12 UTC, odo27 commented on LEVEL2.md
> +시간이 부족하면 어쩌냐는 걱정이 있었지만, 학습 테스트를 먼저 진행한 것이 더 빠른 길이었음을 미션을 진행한 후 깨닫게 되었습니다.
너무 좋습니다! 반영했습니다 ☺️

2023-05-30 06:14 UTC, odo27 commented on LEVEL2.md
> +시간이 부족하면 어쩌냐는 걱정이 있었지만, 학습 테스트를 먼저 진행한 것이 더 빠른 길이었음을 미션을 진행한 후 깨닫게 되었습니다.
좋은 제안 감사합니다 👍

2023-05-30 06:15 UTC, odo27 commented on LEVEL2.md
> +그렇게 미션 제출에만 초점을 두고 진행했음에도 쉽지만은 않았습니다.
반영했습니다 😁

2023-05-30 06:59 UTC, MoonJeWoong approved these changes

2023-09-25 07:11 UTC, gracefulBrown approved these changes

2023-09-25 07:11 UTC, merged