[레벨2 글쓰기] 주드 글 제출합니다
woowacourse/woowa-writing-5 pull request #252
Opened 2023-05-19 06:32 UTC by kevstevie

안녕하세요 tmi가 참 많네요

2023-05-19 06:39 UTC, cpot5620 reviewed
축구를 좋아하는 저로써, 너무 매력적인 주제라서 읽어보러 왔습니다.
즐겁게 읽고 갑니다 주드 ㅎㅎ

2023-05-19 06:39 UTC, cpot5620 commented on README.md
> +마지막으로 `스티븐 제라드`라는 아이덴티티가 강한 리더가 있는 점이 나를 리버풀로 이끌었다.
스티븐 제라드라는 축구선수가 있나요 ?
훔바훔바 아닌가요 ??

2023-05-19 06:39 UTC, cpot5620 commented on README.md
> +축구를 모르는 사람도 알 법한 가장 대중적인 별명인 `리중딱`이 탄생한 것도 이 시기이다.
신나는 노래네요

2023-05-19 06:39 UTC, cpot5620 commented on README.md
> +원래부터 열정적인 클롭은 리버풀과 너무나 잘 어울렸고 리버풀 팬들의 큰 지지를 받았다.
너무나 열정적인 감독이여서, 2경기 출장 정지를 받았죠 지금 ?

2023-05-19 06:43 UTC, carsago commented
나도 한번 불러본다

2023-05-19 06:44 UTC, carsago commented on README.md
> +축구를 모르는 사람도 알 법한 가장 대중적인 별명인 `리중딱`이 탄생한 것도 이 시기이다.
나도 한 번 불러본다.

2023-05-19 06:47 UTC, bjk1649 requested changes
안녕하세요 주드 글 잘읽어습니다.
좋은 글 감사합니다.

축구를 좋아하던 시절 왜 좋아하는 지 생각해본적이 없었는데 같은 이유 였던 것 같아요.

몇가지 피드백 남겼으니 시간 나실 때 확인해주시면 감사할 것 같습니다. 오늘도 좋은 하루 보내세요 🙇

2023-05-19 06:47 UTC, bjk1649 commented on README.md
> +리버풀의 홈 구장인 `안필드`는 규모가 크진 않지만 특유의 열정적인 팬들과 분위기로 원정 팀을 압도한다.
`적절한 백틱` 💯

2023-05-19 06:47 UTC, bjk1649 commented on README.md
> +국가대표팀에서 크게 활약한 박지성을 싫어하지는 않았지만 대중적인 인기는 나의 반골기질을 자극했다.
제가 맨유 좋아하지 않았던 이유랑 똑같네요 🧷

2023-05-19 06:47 UTC, bjk1649 commented on README.md
> +리버풀이라는 도시가 가진 열정을 동경하며 글을 마무리한다.
마무리가 좋네요. 그런데 주제가 리버풀의 열정인만큼 관련 조금 더 보충해주시면 좋을 것 같아요

2023-05-19 08:15 UTC, Choi-JJunho reviewed
잘보고갑니다 
저는 축구를 잘 모르지만 리중딱은 알고있는걸 보니 틀림없이 좋은 팀인것 같네요 🏃💨

2023-05-19 08:15 UTC, Choi-JJunho commented on README.md
> +Hey Jude를 부른 비틀즈의 고향,
:헤이주드:

2023-05-19 08:20 UTC, younghoondoodoom requested changes
안녕하세요 주드햄
주드의 리중.. 아니 리버풀에 대한 사랑이 느껴지는 좋은 글이었습니다.
근데 주드와 리버풀의 관련성에 대해서 좀 더 썼으면 좋겠다는 생각이 듭니다! 
코멘트 몇개 남겼으니 참고 부탁 드립니다~

2023-05-19 08:20 UTC, younghoondoodoom commented on README.md
> +나는 자연스럽게 그 팀을 싫어하게 되었고 맨유의 최대 라이벌인 리버풀이 눈에 들어왔다.
주드의 마음 속 깊은 곳에 맨유가 있다는 사실을 증명하는 문장이네요!

2023-05-19 08:20 UTC, younghoondoodoom commented on README.md
> +> 팀이 힘들 때 응원하지 않을 거라면 이길 때도 응원하지 말라
mood..

2023-05-19 08:20 UTC, younghoondoodoom commented on README.md
> +마지막으로 `스티븐 제라드`라는 아이덴티티가 강한 리더가 있는 점이 나를 리버풀로 이끌었다.
저번에 얘기했을 때 주드가 사실은 열정적이고 싶다와 관련해서 얘기 했던 것 같은데 그 얘기도 풀어주면 더 좋을 것 같아요!

2023-05-20 13:02 UTC, be-student reviewed
역시 글을 재미있게 써주시는군요 👍 
왜 리버풀인가를 잘 느낄 수 있었떤 것 같아요
재밌게 읽었습니다!

2023-05-20 13:02 UTC, be-student commented on README.md
> +첫째로 `이스탄불의 기적`과 같은 낭만적인 스토리가 있다는 점,
축구를 잘 아시는 분에게는 아주 좋은 것 같아요 👍 
축구를 진짜 모르는 입장에서, 이스탄불의 기적에 대한 간단한 내용이 있었으면 좋겠어요~!

2023-05-20 13:02 UTC, be-student commented on README.md
> +축구를 모르는 사람도 알 법한 가장 대중적인 별명인 `리중딱`이 탄생한 것도 이 시기이다.
```우리는 우승하기 싫어```
하면 되는건가요?

2023-05-20 13:02 UTC, be-student commented on README.md
> +Hey Jude를 부른 비틀즈의 고향,
헤이 주드가 노래였군요?! 진짜 전혀 몰랐어요 😮

2023-05-31 07:30 UTC, be-student approved these changes

2023-09-25 07:08 UTC, gracefulBrown approved these changes

2023-09-25 07:11 UTC, gracefulBrown approved these changes

2023-09-25 07:24 UTC, gracefulBrown approved these changes

2023-09-25 23:36 UTC, gracefulBrown approved these changes

2023-09-25 23:36 UTC, merged