[레벨 2 글쓰기 미션] 밀리(김미성) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #293
Opened 2023-05-19 10:54 UTC by miseongk

안녕하세요 우가, 오션, 아마란스! 
쓰다보니 워크샵 때 이야기한 방향과는 조금 달라졌어요🥲
비유하는게 쉽지 않네요..

편하게 읽으시고 리뷰 남겨주세요~!
감사합니다👍

2023-05-19 14:09 UTC, amaran-th requested changes
글 잘 읽었어요 밀리~!

문장이 간결하고 깔끔해서 좋았어요ㅎㅎ
피드백 남겼으니 확인해주시고 필요에 따라 반영해주세요!

2023-05-20 06:50 UTC, Choi-JJunho reviewed
밀리의 마라톤 완주를 기원합니다 🙏
잘보고갑니다 🏃💨

2023-05-20 06:50 UTC, Choi-JJunho commented on level2.md
> +나에게 재밌는 일을 찾아 의식적으로라도 학습 외적인 무언가에 시간을 쓰는 것도 스트레스 해소에 좋을 것 같다. <br>
저도 정말 공감하는 내용이에요 🥲
저는 주변 크루들의 취미를 물어보면서 취미를 찾아가는중이랍니다

2023-05-20 06:50 UTC, Choi-JJunho commented on level2.md
> +분명히 나는 휴식을 취했고 결과적으로 공부를 하지 않았다. 그런데 쉰 만큼의 체력적, 정신적 회복도 되지 않았다면 정말 시간을 낭비한 것 뿐이다. <br>
현실은 게임과 많이 달라서 휴식과 그에 따른 회복이 항상 절대적인 수치로 정의되지 않는다는 부분이 어려운 것 같아요 🥲
그래서 저는 요즘 코어타임에 집중하기 시작했어요!

`해가 떠있을 때 빡세게 집중하고 해가 지면 되는만큼만하고 놀자!`가 요새 롱런하기 위한 저의 학습 방식인 것 같아요🙂

2023-05-21 07:53 UTC, donghae-kim commented on level2.md
> +사실 이 생활을 지속할 자신이 있었기 때문이다. <br>
사실 ~ 라는 문장이 문맥상 조금 어색한 것 같아서 제거했더니 위에 문장과 합칠 수 있을 것 같아서

`처음에는 이 생활을 지속할 자신이 있었기 때문에, '아직 반도 안왔는데 지쳤다'라는 생각이 너무 충격적이었다.` 로 한번 수정해보았어요!

2023-05-21 07:55 UTC, donghae-kim commented on level2.md
> +그렇게 무리해서 나중에 어떻게 버틸래? 라는 말을 엄마께 종종 들었다. <br>
직접인용을 큰따옴표를 통해 표현하는 것도 좋을 것 같아요 !
```suggestion
"그렇게 무리해서 나중에 어떻게 버틸래?" 라는 말을 엄마께 종종 들었다.
```

2023-05-21 07:57 UTC, donghae-kim commented on level2.md
> +쉬어도 쉬는 것 같지 않은 마음. 다들 공감할 것 같다. <br>
저도 요즘 쉬어도 마음한켠에는 공부,미션 등 잡념이 있어서 쉬는 것 같지 않더라고요 .. 너무 공감됩니다 😢

2023-05-21 08:03 UTC, donghae-kim commented on level2.md
> +지난 레벨1 기간 동안은 그게 가능했고 힘들지만 재미있었다. <br>
기간과 동안은 같은 말로 조금 어색한 것 같아요 ! 

```suggestion
지난 레벨1 기간은 그게 가능했고 힘들지만 재미있었다. <br>
```

2023-05-21 08:05 UTC, donghae-kim commented on level2.md
> +다들 취미가 하나씩은 있는데 나는 왜 없을까, 이상했다. <br>
저도 취미가 없다고 생각하지만 그렇다고 이상하다고 생각하지 않기로 했어요 !
괜히 이상하다고 생각하면 저만 조급해질 것 같아서 .. 😂

2023-05-21 08:07 UTC, donghae-kim requested changes
안녕하세요 밀리! 오션🌊입니다!

밀리의 우테코 마라톤 이야기 잘 읽었습니다! 글도 잘 작성해주시고 저와 비슷한 감정을 가지고 있는 것 같아서 더욱 공감되더라고요. 밀리의 우테코 마라톤 화이팅입니다~~~

작성해주신 글에 몇가지 피드백 남겨놨습니다! 천천히 읽어봐주세요 !

2023-05-23 11:42 UTC, wugawuga approved these changes
밀리 가깝게 있으면서도 이런 깊은 고민을 가지고 있는 줄은 몰랐어요ㅠㅠ 미안합니다.

앞으로 함께 열심히 꾸준히 완주해봐요. 좋은 글 잘 읽었습니다.

밀리는 전혀 부족하지 않고 저에게 항상 배울점만 알려주는 멋진 크루입니다 😎

2023-05-23 11:42 UTC, wugawuga commented on level2.md
> +집중을 하지 못하고 그냥 앉아있는 날이 늘었고, 머릿속에 '쉬고 싶다'라는 생각이 문득 문득 떠올랐다. <br>
흔들리고 있다는 걸 느끼지 못해서 미안해요!! 앞으로 함께 더 열심히 해봐요!!

2023-05-23 11:42 UTC, wugawuga commented on level2.md
> +아직 우테코에서의 생활은 반 이상이 남았다. <br>
마라톤에 비유를 조금 더 한다면
```suggestion
아직 우테코에서의 생활은 반 이상 더 달릴 수 있다. <br>
```
이렇게도 바꿀 수 있을 것 같아요 ㅎㅎㅎ

2023-05-23 11:42 UTC, wugawuga commented on level2.md
> +지금까지의 생활을 생각해보면, 나는 현재 중요한 일 외에 다른 일을 잘 못하는 것 같다. <br>
```suggestion
지금까지의 생활을 돌이켜보면, 나는 현재 중요한 일 외에 다른 일을 잘 못하는 것 같다. <br>
```
돌이켜보면이 더 자연스러울 것 같습니다!!

2023-05-23 11:42 UTC, wugawuga approved these changes
밀리 가깝게 있으면서도 이런 깊은 고민을 가지고 있는 줄은 몰랐어요ㅠㅠ 미안합니다.

앞으로 함께 열심히 꾸준히 완주해봐요. 좋은 글 잘 읽었습니다.

밀리는 전혀 부족하지 않고 저에게 항상 배울점만 알려주는 멋진 크루입니다 😎

2023-05-23 11:42 UTC, wugawuga approved these changes
밀리 가깝게 있으면서도 이런 깊은 고민을 가지고 있는 줄은 몰랐어요ㅠㅠ 미안합니다.

앞으로 함께 열심히 꾸준히 완주해봐요. 좋은 글 잘 읽었습니다.

밀리는 전혀 부족하지 않고 저에게 항상 배울점만 알려주는 멋진 크루입니다 😎

2023-05-24 02:05 UTC, nuyh99 commented on level2.md
> +그리고 무엇보다 나는 너무 부족하기 때문에 그래야 한다. <br>
잘하시잖아요ㅜ

2023-05-24 02:05 UTC, nuyh99 commented on level2.md
> +다들 취미가 하나씩은 있는데 나는 왜 없을까, 이상했다. <br>
저도 취미가 없어요!

2023-05-24 02:05 UTC, nuyh99 commented on level2.md
> +나의 목표는 우테코 마라톤에서 완주하는 것이다.
화이팅👍

2023-05-27 06:32 UTC, swonny commented
가장 가까이서 밀리를 지켜본 사람으로서 밀리가 충분히 잘 해낼거라는 확신이 들어요
끝까지 응원합니다🩷

2023-05-29 14:55 UTC, miseongk commented on level2.md
> +그리고 무엇보다 나는 너무 부족하기 때문에 그래야 한다. <br>
우리 처음 봤잖아요..

2023-05-29 14:57 UTC, miseongk commented on level2.md
> +지난 레벨1 기간 동안은 그게 가능했고 힘들지만 재미있었다. <br>
그렇네요! 반영했습니다.

2023-05-29 14:58 UTC, miseongk commented on level2.md
> +집중을 하지 못하고 그냥 앉아있는 날이 늘었고, 머릿속에 '쉬고 싶다'라는 생각이 문득 문득 떠올랐다. <br>
뭐가 미안해요!! 같이 열심히 해봅시다 😁

2023-05-29 14:58 UTC, miseongk commented on level2.md
> +사실 이 생활을 지속할 자신이 있었기 때문이다. <br>
오 좋은 것 같아요. 반영했습니다!

2023-05-29 15:00 UTC, miseongk commented on level2.md
> +사실 이 생활을 지속할 자신이 있었기 때문이다. <br>
문장이 확실히 어색한 것 같네요..!
근데 충격적이였다를 강조하고 싶어서 문장을 나누어서 써봤어요!

2023-05-29 15:01 UTC, miseongk commented on level2.md
> +지금까지의 생활을 생각해보면, 나는 현재 중요한 일 외에 다른 일을 잘 못하는 것 같다. <br>
오 좋아요! 반영했습니다.

2023-05-29 15:02 UTC, miseongk commented on level2.md
> +다들 취미가 하나씩은 있는데 나는 왜 없을까, 이상했다. <br>
취미가 없는 분들도 생각보다 많군요..!
너무 이상하게 생각하지 않아도 될 것 같네요!

2023-05-29 15:03 UTC, miseongk commented on level2.md
> +나에게 재밌는 일을 찾아 의식적으로라도 학습 외적인 무언가에 시간을 쓰는 것도 스트레스 해소에 좋을 것 같다. <br>
오 그것도 좋은 방법이네요👍

2023-05-29 15:04 UTC, miseongk commented on level2.md
> +이는 마치 마라톤과 비슷하다. <br>
맞아요.. 사실 마라톤 이야기를 초반부터 하고 싶었는데 생각보다 쉽지 않더라구요..🥲 
조금 더 고민해볼게요!

2023-05-29 15:06 UTC, miseongk commented on level2.md
> +나의 목표는 우테코 마라톤에서 완주하는 것이다.
연어도 화이팅하세요👊

2023-05-30 14:41 UTC, donghae-kim approved these changes

2023-05-30 15:12 UTC, amaran-th approved these changes

2023-09-25 06:51 UTC, gracefulBrown approved these changes

2023-09-25 06:51 UTC, merged