[키아라] 레벨1 글쓰기 제출합니다.
woowacourse/woowa-writing-5 pull request #30
Opened 2023-03-18 07:11 UTC by kiarakim

안녕하세요 키아라입니다🦁
평소의 필체로 써보았는데 잘 읽혔으면 좋겠네요^^

한 달간의 생활에 대한 제 생각과 감정들을 적어봤습니다.
공감되거나 조언하고자 하는 부분이 있다면 코멘트로 남겨주세요ㅎㅎ

제 글 읽어주셔서 감사합니다.
잘 부탁드려요><

2023-03-21 07:52 UTC, GC-Park reviewed
저의 유머가 궁금하다고 하여 코멘트에 조금 녹여 보았는데 어떠셨을지 모르겠습니다 !

글쓰기 미션을 같이 할 수 있어 저도 영광입니다 ㅎㅎ

2023-03-21 07:52 UTC, GC-Park commented on level-1.md
> +이 모든 것들의 뜻을 알게 된 건 정말 소중한 경험이었다.
처음 캐나다에 갔던 때가 생각나네요 ! 저도 캐나다에서 잠깐 살며 영어를 배우고 학교 부전공으로 일본어를 선택할 정도로 언어에 관심이 많습니다. 키아라의 글을 통해 왜 언어에 관심이 생겼었는지 다시 한번 생각해볼 수 있었습니다 ~!~ 멋지십니다 😊

2023-03-21 07:52 UTC, GC-Park commented on level-1.md
> +매 학기 장학금을 받았기에 똑똑한 줄 알았다.
똑똑.. 계신가요 ? 이 정도면 똑똑한거 아닌가요 ? 😂

2023-03-21 07:52 UTC, GC-Park commented on level-1.md
> +그들은 1080p, 나는 144p의 해상도를 가진 것 같다.
우테코를 같이 준비하던 친구들이 백엔드였는데 다들 떨어졌...
우테코에 계시는 키아라는 적어도 정~~~말 적어도 480p는 줘야 한다고 생각합니다 !! 🙆‍♂️
반영하시는 것은 키아라 마음입니다 ㅎㅎ

2023-03-21 07:52 UTC, GC-Park commented on level-1.md
> +여기에 와서 깨달을 것이 하나 있다.
'깨달을' 오타가 있는 것 같습니다 ! '깨달은' 맞을까요 ?!

2023-03-22 00:57 UTC, yoondgu reviewed
안녕하세요 키아라!!
도시락 타임이 아니라 글쓰기 리뷰로도 만나게 돼서 반갑네요 ㅋ.ㅋ
진솔한 내용에 공감도 가고, 각 문장이 간결하고 리듬감이 있어서 재밌게 읽을 수 있던 것 같아요.
좋았던 부분, 소단원 분리 제안 코멘트 남겨드려요!

2023-03-22 00:57 UTC, yoondgu commented on level-1.md
> +# “공부란 세상의 해상도를 올리는 행위”
해상도라는 키워드로 전체 글을 이끌어나가서 재밌게 읽을 수 있었어요!
표현이 너무 좋네요 👍

2023-03-22 00:57 UTC, yoondgu commented on level-1.md
> +
간단한 본론(변하고 싶다 / 조언이 필요하다 / 노력하다)과 그에 대한 부연 설명이 들어가서 읽기 좋았어요.

2023-03-22 00:57 UTC, yoondgu commented on level-1.md
> +글로 직접 내 감정을 마주하니 갑자기 용기가 생겼다.
용기가 생겨 다짐을 하는 내용으로 글의 흐름이 바뀌는 것 같은데, 이 부분에서 소단원으로 나눠보는 것은 어떨까요?

2023-03-22 10:47 UTC, ashleysyheo requested changes

2023-03-22 10:47 UTC, ashleysyheo commented on level-1.md
> +그러다 스페인어가 가져다준 감동 이후에 약간의 변화가 생겼다.
그 변화가 뭔지에 대해 조금만 더 말해줘도 좋을 것 같아요! 그럼 개발 얘기로 더 자연스럽게 넘어갈 것 같아요.

2023-03-22 10:47 UTC, ashleysyheo commented on level-1.md
> +나는 한 번도 고민해보지 않은 것들이 궁금하다고 한다.
완전 공감이에요... 🥲 모두들이 한 번쯤은 공감할 수 있는 내용이 담겨 있어서 좋아요.

2023-03-22 10:47 UTC, ashleysyheo commented on level-1.md
> +# 업그레이드
위에 소제목(?)을 144p로 하신 게 정말 임팩트 있었어요. 업그레이드도 좋은데 아예 해상도 ex. 270px, 360px, 720px 이렇게 제목을 짓는 것은 어떠세요?

2023-03-22 10:47 UTC, ashleysyheo commented on level-1.md
> +글로 직접 내 감정을 마주하니 갑자기 용기가 생겼다.
저도 도이의 커멘트에 동감합니다!

2023-03-22 10:47 UTC, ashleysyheo commented on level-1.md
> +앞으로 남은 우테코, 그리고 나의 삶.
이 부분이 최종 결론같이 느껴지는데, 소단원까지는 아니더라도 뭔가 좀 위와 구분 지어주면 좋을 것 같습니다.

2023-03-22 12:41 UTC, kiarakim commented on level-1.md
> +이 모든 것들의 뜻을 알게 된 건 정말 소중한 경험이었다.
저는 일본어를 공부 한 후에 새로운 언어로 스페인어를 선택했는데 외국어가 주는 감동이 저에겐 크게 다가오는 것 같아요ㅎㅎ

2023-03-22 12:43 UTC, kiarakim commented on level-1.md
> +매 학기 장학금을 받았기에 똑똑한 줄 알았다.
경기도 오산입니다😜

2023-03-22 12:44 UTC, kiarakim commented on level-1.md
> +그들은 1080p, 나는 144p의 해상도를 가진 것 같다.
그런가요? 생각해보니 480p... 줘도 될 것 같습니다! 그치만 아직 갈 길이 머네요^^ 감사합니당!

2023-03-22 12:45 UTC, kiarakim commented on level-1.md
> +여기에 와서 깨달을 것이 하나 있다.
'깨달아야 할' 의 의미로 '깨달을'이라고 작성했습니다!
그런데 '깨달은'이 읽을 때 더 자연스럽긴 하네요ㅎㅎ

2023-03-22 12:48 UTC, kiarakim commented on level-1.md
> +# “공부란 세상의 해상도를 올리는 행위”
제 마음 속에 새겨둔 말이라 슥삭 쓸 수 있었어요ㅎㅎ

2023-03-22 12:53 UTC, kiarakim commented on level-1.md
> +그러다 스페인어가 가져다준 감동 이후에 약간의 변화가 생겼다.
오 감사합니다! 두 줄 추가했어요!

2023-03-22 12:56 UTC, kiarakim commented on level-1.md
> +나는 한 번도 고민해보지 않은 것들이 궁금하다고 한다.
저만의 걱정이 아니었군요..!

2023-03-22 12:58 UTC, kiarakim commented on level-1.md
> +# 업그레이드
그 부분을 고민했었는데 딱 짚어주셨네요~ 감사합니다! 저는 480p 가 좋으니 480p로 하겠어요><

2023-03-22 13:02 UTC, kiarakim commented on level-1.md
> +글로 직접 내 감정을 마주하니 갑자기 용기가 생겼다.
감사합니다! 반영했어요ㅎㅎ

2023-03-22 13:05 UTC, kiarakim commented on level-1.md
> +앞으로 남은 우테코, 그리고 나의 삶.
읽다보니 이 두 문장이 없어도 될 것 같다는 느낌을 받았어요... 그래서 삭제했습니당

2023-03-24 05:55 UTC, hyunji1203 commented
안녕하세요! 
안드로이드의 뽀또입니다!
글 너무 잘읽고 가요~!
공감가는 부분들도 많아서 공감하며 읽었어요ㅎㅎ 나중에 만나면 인사해요!!

2023-03-26 10:33 UTC, bassyu approved these changes
안녕하세요! 글 잘 읽었습니다!
계속 정진하셔서 우테코의 해상도를 4K까지 올리시길 바랄게요 :)

2023-03-26 10:33 UTC, bassyu commented on level-1.md
> +네트워크 환경이 좋아야 해상도의 성능을 온전히 발휘한다.
실제로 영상을 볼 때랑 비유한 것이었군요!
`영상을 볼 때도 네트워크 환경이 좋아야 해상도의 성능을 온전히 발휘한다.`는 어떤지 제안해 봅니다 :)

2023-03-26 10:59 UTC, GC-Park approved these changes

2023-03-26 12:43 UTC, yoondgu approved these changes

2023-03-26 15:50 UTC, swonny reviewed
안녕하세요 키아라!
백엔드 메리입니다!
지나가다 인사를 몇 번 했지만 많은 이야기를 나눠보진 못했었는데, 
리뷰를 통해 키아라의 이야기를 조금 더 들어볼 수 있었던 것 같아 정말 좋았어요!

저도 평소 배우는 것의 즐거움을 정말 좋아하지만 한번도 '해상도를 높이는 일'과 같이 생각해보지 않은 것 같아요! 멋진 표현 배워갑니다 감사해요 ㅎㅎ
글도 정말 잘 쓰시는 것 같아요! 처음부터 끝까지 흥미롭게 잘 읽히는 글이었어요!
앞으로도 키아라가 세상을 바라보는 해상도가 4K 이상이 될 수 있기를 응원하겠습니다!!

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +세상을 비추는 해상도가 업그레이드된다고 생각하기 때문이다.
배움의 즐거움을 멋진 문장으로 표현해주셔서 글에 더 흥미가 생기는 것 같습니다 ㅎㅎ

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +# 144p
144p가 해상도라는 것을 명시해주지 않아도 괜찮을까요?!

해상도를 조금씩 높여가며 이야기를 풀어내는 아이디어가 좋은 것 같아요 ㅎㅎ

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +제대로 된 의견 하나 내지 못하는 사람이라 평가받을 것 같았다.
너무너무 공감이 됩니다! 저도 다른 사람들이 저를 못하는 사람이라고 평가하는 게 무서웠어요..!!

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +전공자로서의 4년이 쓸모없다는 것을 인정해버릴까 무서웠다.
이 부분도 정말 공감이 됩니다..! 
저는 전공자는 아니지만 프로그래밍을 공부한 약 2년 정도의 시간이 무의미한 시간이었다는 생각이 들 때 힘들었던 것 같아요

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +이 모든 것은 해상도를 높이면 해결될 일이다.
멋진 마인드입니다!!

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +# 네트워크
이야기의 흐름이 바뀌면서 소제목을 추가해 흐름을 나눠준 부분이 좋은 것 같아요!

2023-03-26 15:50 UTC, swonny commented on level-1.md
> +네트워크 환경이 좋아야 해상도의 성능을 온전히 발휘한다.
오 저도 쵸파의 댓글에 동의합니다! 실제 영상을 볼 때를 비유했다고 생각하면 더 잘 와닿는 문장인 것 같아요!

2023-03-27 04:18 UTC, hyunji1203 approved these changes

2023-04-25 07:09 UTC, gracefulBrown approved these changes
👍

2023-04-25 07:09 UTC, merged