[레벨 2 글쓰기 미션] 제레미(김민석) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #311
Opened 2023-05-19 11:55 UTC by shackstack

부족한 글 실력이지만 잘 부탁드리겠습니다.

2023-05-23 10:41 UTC, rhkrwngud445 approved these changes
제레미가 어떤 심경의 변화가 일어났는지 잘 느껴졌습니다!👍
전체적으로 잘 써주셔서 딱히 리뷰드릴게 없네요😂
고생 많으셨어요!!

2023-05-23 10:41 UTC, rhkrwngud445 commented on LEVEL2.md
> +공식문서보다 유튜브를 먼저 찾게되는 이유가 이런 나의 전사떄문이지 않은가 싶다.
```suggestion
공식문서보다 유튜브를 먼저 찾게되는 이유가 이런 나의 전사 떄문이지 않은가 싶다.
```

띄어쓰면 좋을 것 같아요!

2023-05-23 10:41 UTC, rhkrwngud445 commented on LEVEL2.md
> +과연 나는 바뀔 수 있을까?
여운이 남는 마무리네요👍👍

2023-05-23 10:41 UTC, rhkrwngud445 commented on LEVEL2.md
> +마치 당구를 배우는 사람이 우라마시나 대회전같은 기술들을 쳐보지도 않고 원리를 먼저 공부하는 것처럼.
오 전문용어.. 다음에 당구 한 번 치러 가시죠!

2023-05-23 12:06 UTC, krrong requested changes
안녕하세요 제레미! 글 잘 읽었습니다ㅎㅎ
그 때 이야기했던 부분들을 잘 적어주신 것 같아 피드백을 드릴 부분을 찾기 어렵네요!
그럼에도 어느정도 코멘트를 남겨봤어요. 참고해주시면 좋을 것 같습니다 :)

2023-05-23 12:06 UTC, krrong commented on LEVEL2.md
> +부엉이가 그냥 책 한권 정독하면 되는데 뭐하러 강의를 사냐라는 말에 내가 너무 쉽게 공부하려고 하나라는 생각이 들었다.
그 때 이야기했던 것처럼 사람마다 스타일이 모두 다르기 때문에 자신에게 맞는 공부 방법도 다양할 것이라고 생각해요.
그러니 `너무 쉽게 공부하려고 하나?`라고 생각하기보다 `나에게 효과적인 공부 방법이다`라고 생각하시는 게 어떨까 감히 의견을 남겨봅니다🙃

2023-05-23 12:06 UTC, krrong commented on LEVEL2.md
> +앞으로 공식문서 열심히 읽어보고 방학 떄 코어 자바스크립트 같은 얇은 책을 도전하면서 나를 개선시켜볼 계획이다.
자기 자신을 개선하려는 모습이 정말 보기 좋은 것 같아요!!

2023-05-23 12:06 UTC, krrong commented on LEVEL2.md
> +## 개발을 하기전에 효과를 보았던 학습방법
소제목을 나눠 내용을 기술하면 어떨까 하는 생각이 들어요!
참고만 해주시면 좋겠습니다 :)

2023-05-23 12:06 UTC, krrong commented on LEVEL2.md
> +그 당시 많은 불안감이 들었는데 인간은 망각의 동물이라서 그런지 방학을 보내고나서 그러한 불안감을 잊게 되었다.
레벨 2가 끝나가는 지금은 어떤 생각을 가지고 계신지 궁금하네요🙃

2023-05-23 13:27 UTC, solo5star reviewed
안녕하세요 제레미! 초반에 흥미를 끌만한 내용이 있어 전체적으로 재밌게 읽었습니다. 특히 `개발을 하기전에 효과를 보았던 학습방법` 문단에서 의식의 흐름처럼 서술해주셨는데, 어색하지 않고 술술 읽혀서 정말 신기했어요 ㅎㅎ

전체적으로 어떤 내용을 전달하고자 하는 글인지 나타내는 제목이 최상단에 있으면 좋을 것 같아요! `현재 나의 학습방법`이 글의 제목인 것 같은데 중간에 있어서 마치 부제목인것 처럼 보이고, 전체 제목이 없는 것 처럼 보여요.

가볍게 읽을 수 있어 좋은 글이었습니다. 글쓰기 미션 진행하느라 수고 많으셨습니다~!

2023-05-30 18:31 UTC, krrong approved these changes

2023-05-31 01:57 UTC, solo5star approved these changes

2023-05-31 10:42 UTC, shackstack commented on LEVEL2.md
> +과연 나는 바뀔 수 있을까?
감사합니다ㅎㅎ

2023-05-31 10:43 UTC, shackstack commented on LEVEL2.md
> +마치 당구를 배우는 사람이 우라마시나 대회전같은 기술들을 쳐보지도 않고 원리를 먼저 공부하는 것처럼.
좋습니다ㅋㅋㅋ 조만간 프론트 안드 4구 대전 추진하겠습니다!

2023-05-31 10:46 UTC, shackstack commented on LEVEL2.md
> +부엉이가 그냥 책 한권 정독하면 되는데 뭐하러 강의를 사냐라는 말에 내가 너무 쉽게 공부하려고 하나라는 생각이 들었다.
감사합니다...ㅎㅎ

2023-05-31 10:47 UTC, shackstack commented on LEVEL2.md
> +## 개발을 하기전에 효과를 보았던 학습방법
오호... 좋습니다!!

2023-05-31 10:48 UTC, shackstack commented on LEVEL2.md
> +그 당시 많은 불안감이 들었는데 인간은 망각의 동물이라서 그런지 방학을 보내고나서 그러한 불안감을 잊게 되었다.
슬슬 레벨2인터뷰가 다가오면서 불안감이 엄습해오는 듯 하네요.

2023-09-25 06:33 UTC, gracefulBrown approved these changes

2023-09-25 06:33 UTC, merged