[아크] 레벨1 글쓰기 제출합니다.
woowacourse/woowa-writing-5 pull request #38
Opened 2023-03-18 11:16 UTC by re4rk

2023-03-18 11:41 UTC, yeonkkk commented
안녕하세요 아크! 백엔드 조이🎶입니다.  
개발을 시작하게 된 배경부터 우테코에 지원까지의 내용을 잘 담아주셨네요!  
그리고 감정을 잘 담아서 글을 작성해주신 것 같아요. 

글을 읽으면서 느낀점들을 조금 작성해보았습니다.  
개인적인 의견이니 필요한 부분만 참고해주시면 되겠습니다.  

좋은 글 잘 읽고 갑니다! 고생하셨습니다 🙂

2023-03-18 11:42 UTC, yeonkkk commented on README.md
> +고등학교 때부터 보안을 공부하고 싶었다. 당시에는 무엇이 되고 싶었던 걸까? 단순히 멋있어 보였던 생각도 해 보았다. 그 후 보안을 공부하기 위해 보안학과에 들어갔었고, 나의 적성과 잘 맞았던 것 같다. 동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다. 막상 공부하면서 내가 하고 싶던 게 무엇이었던가 생각에 잠기는 일이 많았다. 보안관제를 공부
`단순히 멋있어 보였던 생각도 해 보았다.` 이 부분이 조금 어색한 것 같아요!  
만약 `멋있어 보여서 보안을 공부해보고 싶었다`는 의미를 내포하고 있다면 아래와 같이 작성해봐도 좋을 것 같아요.
1. `단순히 멋있어 보였던 것 같다.`
2. `단순히 멋있어 보인다는 생각이 들었던 것 같다.`

2023-03-18 11:42 UTC, yeonkkk commented on README.md
> +고등학교 때부터 보안을 공부하고 싶었다. 당시에는 무엇이 되고 싶었던 걸까? 단순히 멋있어 보였던 생각도 해 보았다. 그 후 보안을 공부하기 위해 보안학과에 들어갔었고, 나의 적성과 잘 맞았던 것 같다. 동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다. 막상 공부하면서 내가 하고 싶던 게 무엇이었던가 생각에 잠기는 일이 많았다. 보안관제를 공부
`고등학교 때 당시 컴퓨터를 마음대로 조종한다는 것들이 너무 멋있었다.` →  `고등학교 때는 컴퓨터를 마음대로 조종한다는 것이 너무 멋있었다.`  

이렇게 변경해보면 어떨까요?

2023-03-18 11:42 UTC, yeonkkk commented on README.md
> +고등학교 때부터 보안을 공부하고 싶었다. 당시에는 무엇이 되고 싶었던 걸까? 단순히 멋있어 보였던 생각도 해 보았다. 그 후 보안을 공부하기 위해 보안학과에 들어갔었고, 나의 적성과 잘 맞았던 것 같다. 동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다. 막상 공부하면서 내가 하고 싶던 게 무엇이었던가 생각에 잠기는 일이 많았다. 보안관제를 공부
이 문장은 2개로 나눠봐도 좋을 것 같아요!  
> 열정적이던 저학년에서 현실과 타협하는 고학년으로 올라가면서 내가 하고 싶은 일로 살기에는 힘들다는 것이 사실이 나를 괴롭게 했다.  

`고학년으로 올라가면서 현실과 타협하게 되었다. 내가 하고 싶은 일을 하며 살기에는 힘들다는 사실이 나를 괴롭게 했다. ` 라고 변경해보면 어떨까요?:)

2023-03-18 11:42 UTC, yeonkkk commented on README.md
> +개발을 도전하기 위해 길을 찾는 중에 에브리타임에서 AOS 초보 개발자를 모집한다는 소식이 들렸다. 그중에서 "안드로이드와 코틀린을 몰라도 되지만 코딩 경험이 있는 사람"이라는 문구가 이건 나를 말하는 거구나 생각이 들었다. 그렇게 프로젝트 중간에 투입하여 AOS를 처음 배우기 시작했다. AOS를 시작하고 2달이 지났을까 우테코의 안드로이드 과정이 있다는
이 문장을 2개로 나눠보면 어떨까요?
> 그중에서 "안드로이드와 코틀린을 몰라도 되지만 코딩 경험이 있는 사람"이라는 문구가 이건 나를 말하는 거구나 생각이 들었다.

예를 들면 아래와 같이 나눠볼 수 있겠네요! ㅎㅎ  
`모집 공고에서 "안드로이드와 코틀린을 몰라도 되지만 코딩 경험이 있는 사람"이라는 문구를 보았다. '이건 나를 말하는 거구나'하는 생각이 들었다.`

2023-03-18 11:42 UTC, yeonkkk commented on README.md
> +우테코를 시작하면서 느끼는 것은 이렇게 모두가 다 열심히 하는 모습을 지금까지 본 적이 없었다. 크루 한 명 한 명 이야기를 들어보면 대단하다고 느꼈으며 모두 열정적이었다. 주변에는 개발을 잘하는 사람들이 많이 있었다. 크루들이 자신들이 만든 앱들을 보여줬다.
> 우테코를 시작하면서 느끼는 것은 이렇게 모두가 다 열심히 하는 모습을 지금까지 본 적이 없었다.

`우테코를 시작하면서 크루 모두가 다 열심히 한다고 느꼈다. 이런 모습은 지금까지 본 적이 없었다.` 
크루들이 모두 열심히 한다고 느꼈고, 모든 사람이 열심히 하는 것을 처음 경험했다는 의미를 전달하고 싶었다면 이렇게 변경해 보면 어떨까요?

2023-03-18 12:27 UTC, seokjin8678 reviewed
안녕하세요 아크!
제 생각의 기준으로 피드백 드렸어요!
저의 주관적인 기준이니 다른 사람의 의견도 보시고 반영해주세요!

보안 전공이셨다니, 백엔드로 오셨어도 엄청 잘 하셨을 것 같아요!

2023-03-18 12:27 UTC, seokjin8678 commented on README.md
> +고등학교 때부터 보안을 공부하고 싶었다. 당시에는 무엇이 되고 싶었던 걸까? 단순히 멋있어 보였던 생각도 해 보았다. 그 후 보안을 공부하기 위해 보안학과에 들어갔었고, 나의 적성과 잘 맞았던 것 같다. 동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다. 막상 공부하면서 내가 하고 싶던 게 무엇이었던가 생각에 잠기는 일이 많았다. 보안관제를 공부
해당 부분의 길이가 다른 글에 비해 길어보여요!
적당히 줄 바꿈을 해주는 건 어떠세요?

2023-03-18 12:27 UTC, seokjin8678 commented on README.md
> +보안 수업 중에서도 코딩으로 무언가를 만드는 것에 흥미가 많았던 것 같다. C언어로 2048bit 제곱 구현하기, 커스텀 malloc 구현하기, 모두의 마블 게임 만들기 등등...
리뷰와 관련은 없지만, 백엔드 오셨어도 굉장히 잘 하셨겠네요!

2023-03-18 12:27 UTC, seokjin8678 commented on README.md
> +그렇게 우테코에 합격하고 나서 고민이 빠졌다. 우테코를 선택한다는 것은 나의 모든 보안 경력을 버린다는 것이다. 그래서 합격하고 나서도 고민하는 시간을 많이 가졌다. 결국에는 나의 적성이 맞는 개발에 도전해보도록 했다. 보안에서 하던 프로젝트를 모두 나왔다. 교수님 밑에서 하던 연구도 나왔다.
`한 문장에는 하나의 정보만 담도록 한다.` 라는 글쓰기 규칙이 있었는데, 뒷 부분이 조금 신경쓰이네요!

2023-03-18 12:27 UTC, seokjin8678 commented on README.md
> +그 크루들이 너무나 멋있게 보였다. 나도 노력해서 저렇게 만들어 보자고 생각하면서 지내고 있었다.
`~했다.` 라는 말이 중복돼서 나오는 것 같아요.

2023-03-19 00:58 UTC, beer-2000 requested changes
안녕하세요 아크 👋
우테코에 오시기 전의 치열했던 고민과, 후회 없는 한 해를 보내고자 하는 비장한 마음이 잘 느껴져 재밌게 읽은 글이었습니다.
다른 분들께서 많은 좋은 코멘트 남겨주셔서, 간단한 코멘트와 감상평(?)만을 남겼으니 참고만 부탁드립니다.

감사합니다 😊

2023-03-19 00:58 UTC, beer-2000 commented on README.md
> +우테코를 시작하면서 느끼는 것은 이렇게 모두가 다 열심히 하는 모습을 지금까지 본 적이 없었다. 크루 한 명 한 명 이야기를 들어보면 대단하다고 느꼈으며 모두 열정적이었다. 주변에는 개발을 잘하는 사람들이 많이 있었다. 크루들이 자신들이 만든 앱들을 보여줬다.
맞아요.. 같이 열심히 한다는 것이 가장 큰 강점이고 메리트인 것 같아요!

2023-03-19 00:58 UTC, beer-2000 commented on README.md
> +4년이라는 시간 동안 보안을 공부했다. 하지만 현재 선택에는 후회보다는 잘 선택했다는 생각이 들었다. 여기서 느끼는 학습 분위기, 배우는 문화, 늘어가는 실력 모두 나를 행복하게 한다.
저도 부족하지만 나름대로 쌓아온 것들을 두고 지금의 길로 오게 되었는데요,
가졌던 경험들은 지금의 저를 만들었고, 생각보다 많은 부분에서 영향을 주고 있음을 요즘 더욱 느끼고 있어요.

보안 지식과 컴퓨터 과학 지식, 무언가에 몰두하며 길러진 지적 체력, 모두 남아 아크의 폭발적 성장에 영향을 주고 있으리라 생각합니다.

더불어 저는 우테코에서 배우는 지식에 크루들과 함께 몰입하는 이 경험이, 개발자로서 그리고 인간으로서 어떤 환경에서 어떤 분야를 공부하고 써먹든 엄청난 자산이 되어줄 것이라고 확신해요.

비슷한 경험과 생각을 가진 크루를 만나 반갑네요!

2023-03-19 00:58 UTC, beer-2000 commented on README.md
> +이번 연도에는 우테코에만 집중하여 후회하지 않는 한 해를 보냈다고 당당히 말할 수 있도록 하고 싶다.
저도.. 치열하게 살고, 밀도 있게 쉬고, 후회가 남지 않는 한 해를 보내고 싶네요!

2023-03-19 00:58 UTC, beer-2000 commented on README.md
> +그렇게 우테코에 합격하고 나서 고민이 빠졌다. 우테코를 선택한다는 것은 나의 모든 보안 경력을 버린다는 것이다. 그래서 합격하고 나서도 고민하는 시간을 많이 가졌다. 결국에는 나의 적성이 맞는 개발에 도전해보도록 했다. 보안에서 하던 프로젝트를 모두 나왔다. 교수님 밑에서 하던 연구도 나왔다.
`교수님 밑에서 하던 연구도 나왔다` -->
`나왔다`라는 표현보다 조금 더 직관적인 표현이면 어떨까요? `관두다`, `그만두다` 등..
앞의 단어와 함께 흘겨 보면, `연구 결과가 나왔다` 등의 표현이 조금 겹쳐 보이는 것 같아요!

2023-03-19 09:16 UTC, wugawuga reviewed
안녕하세요 아크! 백엔드 우가입니다.
먼저 글을 너무 잘 써주셔서 정독했습니다. 감사합니다 🤗

한달 생활기에 있어서 시작 전 동기부분에 대해 궁금한 점이 있습니다.
우테코 생활을 하면서 '이 이유' 때문에 왔다. 라고 느꼈을 부분이 있을까요? 첫 번째 소제목인 시작 전 여기 내용을 생활에 빗대어 설명을 하면 조금 더 한 달 생활기 주제에 적합할 것 같습니다!!

글을 잘 못 쓰는 저지만 의견을 읽어봐 주셔서 감사합니다 ㅎㅎㅎ

2023-03-19 09:16 UTC, wugawuga commented on README.md
> +4년이라는 시간 동안 보안을 공부했다. 하지만 현재 선택에는 후회보다는 잘 선택했다는 생각이 들었다. 여기서 느끼는 학습 분위기, 배우는 문화, 늘어가는 실력 모두 나를 행복하게 한다.
> 하지만 현재 선택에는 후회보다는 잘 선택했다는 생각이 들었다.

이 부분이 조금 어색한 것 같아요.

2023-03-21 13:30 UTC, jeomxon reviewed
안녕하세요 아크 :) 백엔드 저문입니다!
저도 보안을 공부하고 싶었던 사람으로서 공감가는 부분이 많은 글이었습니다~
다른 크루분들이 이미 좋은 코멘트를 남겨주셨고, 추가적으로 필요하다고 느끼는 부분에만 코멘트를 작성해보았습니다.
글 재밌게 잘 읽었습니다 ㅎㅎ

2023-03-21 13:30 UTC, jeomxon commented on README.md
> +고등학교 때부터 보안을 공부하고 싶었다. 당시에는 무엇이 되고 싶었던 걸까? 단순히 멋있어 보였던 생각도 해 보았다. 그 후 보안을 공부하기 위해 보안학과에 들어갔었고, 나의 적성과 잘 맞았던 것 같다. 동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다. 막상 공부하면서 내가 하고 싶던 게 무엇이었던가 생각에 잠기는 일이 많았다. 보안관제를 공부
`동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다.`에서 `동아리로 열심히 보안을 공부했다`라는 부분이 어색하게 느껴지네요!
수정해보는 것은 어떨까요?

2023-03-21 13:30 UTC, jeomxon commented on README.md
> +이번 연도에는 우테코에만 집중하여 후회하지 않는 한 해를 보냈다고 당당히 말할 수 있도록 하고 싶다.
집중을 할 수 있는 기회가 인생에서 흔치 않다고 생각하는데,
올해는 좋은 기회가 될 것 같습니다!
아크도 후회없는 2023년이 되었으면 좋겠습니다~

2023-03-21 13:30 UTC, jeomxon commented on README.md
> +그렇게 우테코에 합격하고 나서 고민이 빠졌다. 우테코를 선택한다는 것은 나의 모든 보안 경력을 버린다는 것이다. 그래서 합격하고 나서도 고민하는 시간을 많이 가졌다. 결국에는 나의 적성이 맞는 개발에 도전해보도록 했다. 보안에서 하던 프로젝트를 모두 나왔다. 교수님 밑에서 하던 연구도 나왔다.
추가로 `보안에서 하던 프로젝트를 모두 나왔다.`라는 문장도 어색함이 느껴지네요.
`보안에서`라는 말보다 구체적으로 작성하면 좋을 것 같아요!

2023-03-21 16:40 UTC, no1msh reviewed
아크 공감되는 글 잘 보았습니다.
한 가지 정도 의견 남겼으니 수정고려해보시 바랍니다!

2023-03-21 16:40 UTC, no1msh commented on README.md
> +개발을 도전하기 위해 길을 찾는 중에 에브리타임에서 AOS 초보 개발자를 모집한다는 소식이 들렸다. 그중에서 "안드로이드와 코틀린을 몰라도 되지만 코딩 경험이 있는 사람"이라는 문구가 이건 나를 말하는 거구나 생각이 들었다. 그렇게 프로젝트 중간에 투입하여 AOS를 처음 배우기 시작했다. AOS를 시작하고 2달이 지났을까 우테코의 안드로이드 과정이 있다는
`AOS` 라는 말은 우리나라에서만 사용하는 말이라고 하네요. Android Native를 줄인 `AN`이나 `안드로이드 앱`이라는 말을 쓰는게 어울려 보이네요.

2023-03-21 16:40 UTC, no1msh commented on README.md
> +이번 연도에는 우테코에만 집중하여 후회하지 않는 한 해를 보냈다고 당당히 말할 수 있도록 하고 싶다.
저도 나중에 다시 뒤를 돌아 본다면 적어도 우테코를 한 기간 만큼은 누구보다 열심히 했다고 당당하게 말할 수 있었음 하네요. ㅎㅎ
아크는 충분히 누구보다 빠르게 달리고 있으니까 좋은 결과가 있을겁니다.😁

2023-03-25 11:26 UTC, re4rk commented on README.md
> +고등학교 때부터 보안을 공부하고 싶었다. 당시에는 무엇이 되고 싶었던 걸까? 단순히 멋있어 보였던 생각도 해 보았다. 그 후 보안을 공부하기 위해 보안학과에 들어갔었고, 나의 적성과 잘 맞았던 것 같다. 동기들과 학교 공부 외에도 동아리로 열심히 보안을 공부했다. 막상 공부하면서 내가 하고 싶던 게 무엇이었던가 생각에 잠기는 일이 많았다. 보안관제를 공부
지금보니 어색한 부분들이 많았네요!! 예제와 함께 코멘트 달아주셔서 감사합니다!

2023-03-25 11:26 UTC, re4rk commented on README.md
> +4년이라는 시간 동안 보안을 공부했다. 하지만 현재 선택에는 후회보다는 잘 선택했다는 생각이 들었다. 여기서 느끼는 학습 분위기, 배우는 문화, 늘어가는 실력 모두 나를 행복하게 한다.
@beer-2000 다른 도메인에서 넘어오고 불안한 마음이 있었는데 위안이 되는 말을 남겨주셔서 감사합니다!

2023-03-25 11:29 UTC, re4rk commented
> 안녕하세요 아크! 백엔드 우가입니다. 먼저 글을 너무 잘 써주셔서 정독했습니다. 감사합니다 🤗
> 
> 다른 분들이 리뷰를 너무 잘해주셔서 따로 드릴게 없네요ㅠㅠ
> 
> 한달 생활기에 있어서 시작 전 동기부분에 대해 궁금한 점이 있습니다. 우테코 생활을 하면서 '이 이유' 때문에 왔다. 라고 느꼈을 부분이 있을까요? 첫 번째 소제목인 시작 전 여기 내용을 생활에 빗대어 설명을 하면 조금 더 한 달 생활기 주제에 적합할 것 같습니다!!
> 
> 글을 잘 못 쓰는 저지만 의견을 읽어봐 주셔서 감사합니다 ㅎㅎㅎ

많은 사람들이 목표를 위해 이렇게 열심히 무언가를 공부한다는 환경이 제가 온 이유인 것같습니다! 달아주신 좋은 리뷰 또한 빠르게 반영하겠습니다!

2023-03-25 13:31 UTC, no1msh approved these changes
미션하느라 바쁠텐데 글쓰기 고생하셨습니다. 아크 ㅎㅎ

2023-03-25 13:35 UTC, wugawuga approved these changes
수정하고 글이 너무 많이 깔끔해졌네요!!
좋은 글 감사합니다. 잘 읽었습니다 🤗

2023-03-26 05:42 UTC, yeonkkk approved these changes
안녕하세요 아크! 조이입니다🙂
이전에도 좋은 글이었는데, 크루들의 피드백을 통해 더 깔끔하게 수정해주셨네요👍
저는 더 이상 수정할 부분이 없다고 판단해서 approve 하겠습니다 ㅎㅎ
고생하셨습니다 !!

2023-03-26 11:07 UTC, jeomxon approved these changes
안녕하세요 아크 :)
수정하느라 고생많으셨습니다~
다시 읽어봐도 좋은 글이네요!

2023-03-26 15:18 UTC, seokjin8678 approved these changes
안녕하세요 아크!
피드백 반영한 뒤 다시 보니 더욱 글이 좋아졌어요!
원하는 무언가를 이루기 위해 배웠던 것을 버릴 수 있는 용기가 정말 대단한 것 같아요!
후회하지 않는 시간이 됐으면 좋겠네요!

2023-03-27 04:00 UTC, beer-2000 approved these changes

2023-04-25 07:09 UTC, gracefulBrown approved these changes
👍

2023-04-25 07:09 UTC, merged