[레벨 4 글쓰기 미션] 비버(전인표) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #401
Opened 2023-10-22 06:22 UTC by ingpyo

안녕하세요 혜다, 슬링키, 글렌, 말랑, 깃짱, 멘델!

벌써 4렙이 끝났네요.
제가 현제 어떤 개발자가 되고 싶은지 써봤습니다. 재밌게 봐주세요.😃

2023-10-23 03:47 UTC, yujamint reviewed
비버가 우테코에서 보여준 성장세를 쭉 이어가기를 응원합니다.

2023-10-23 03:47 UTC, yujamint commented on level4.md
> +나는 좋게 말해서 다른 사람들에게 도움을 주는 것, 다르게 말하면 지식을 뽑내기 위해 공부를 할 때 원동력을 찾았다.
`뽑내기 위해` -> 오타가 있는 거 같습니다.

2023-10-24 07:07 UTC, seokjin8678 requested changes
안녕하세요 비버!
글 잘 읽었습니다!!
애자일 한 모습 멋있네요.
몇 가지 피드백 남겼어요!
고생하셨습니다!

2023-10-24 07:07 UTC, seokjin8678 commented on level4.md
> +다른 사람들과 함께 공유하고 그 지식을 통해 토론을 하는 과정이 너무 재밌고 공부하는 원동력이였다.
애자일 하군요. 👍👍👍

2023-10-24 07:07 UTC, seokjin8678 commented on level4.md
> +다른 사람들과의 토론을 통해 함께 성장하는 것의 가치를 알게 되었다.
> 하지만 우테코에서의 경험을 통해 깨달았다.
> 지식을 공유하고, 다른  사람들과 ~

줄바꿈을 다음과 같이 해도 좋을 것 같네요!

2023-10-24 09:42 UTC, shin-mallang requested changes
글 잘 읽었습니다~
수학 잘한 것 빼고는 저랑 비슷한 부분이 많아서 공감하며 읽었네요:)

2023-10-24 09:42 UTC, shin-mallang commented on level4.md
> +어릴 때 나는 수학에 흥미를 느꼈다.
첫줄부터 그저 갓

2023-10-24 09:42 UTC, shin-mallang commented on level4.md
> +답을 알려주고 풀어주는 순간에 나는 만족감을 느꼈다.
떡잎부터 남달랐군요

2023-10-24 09:42 UTC, shin-mallang commented on level4.md
> +그 때 떠올랐던 이미지는 해커였다. 모니터 앞에서 코드 한 줄, 한 줄 타이핑하며,
전공 선택 시점에 이르렀는데 해커 이미지를 떠올렸다...?
중간에 컴공에 대한 얘기가 빠진 것 같아요!

2023-10-24 09:42 UTC, shin-mallang commented on level4.md
> +다른 사람들과 함께 공유하고 그 지식을 통해 토론을 하는 과정이 너무 재밌고 공부하는 원동력이였다.
인정. 토론 너무 재미있습니다

2023-10-24 09:42 UTC, shin-mallang commented on level4.md
> +과거에는 지식을 뽐내는 데 중점을 뒀지만, 지금은 사용자의 관심 속에서 토론을 통해 성장하는 개발자를 꿈꾼다.
👍

2023-10-24 11:06 UTC, Dahyeeee approved these changes
비버 안녕하세요! 글 잘 읽었습니다! 
지식을 드러내는 원동력에서 지식을 공유하는 공동체적 원동력으로 바뀐게 인상깊네요~~

술술 잘 읽히는 글이었습니다.

코멘트는 참고만 하셔도 좋습니다 :)

2023-10-24 11:06 UTC, Dahyeeee commented on level4.md
> +
요기 좀 불필요한 개행인 것 같습니다. 문장마다 개행이 있는 것 같은데 ,(콤마)로 연결된 문장은 개행이 없어도 되지 않을까요?

2023-10-24 11:06 UTC, Dahyeeee commented on level4.md
> +영화에서 보여지는 해커의 모습은 내게는 정말 멋지게 보였다. 이런 꿈을 향해, 컴퓨터 학과를 선택하게 됐다.
이런 꿈, 이 조금 모호한것같아요! 해커가 되고 싶었다는 걸까요?

2023-10-24 11:06 UTC, Dahyeeee commented on level4.md
> +다른 사람들과 함께 공유하고 그 지식을 통해 토론을 하는 과정이 너무 재밌고 공부하는 원동력이였다.
```suggestion
다른 사람들과 함께 공유하고 그 지식을 통해 토론을 하는 과정이 너무 재밌고 공부하는 원동력이 되었다
```

가 자연스러운 것 같아요

2023-10-24 11:06 UTC, Dahyeeee commented on level4.md
> +다른 사람들과의 토론을 통해 함께 성장하는 것의 가치를 알게 되었다.
아주 멋진 것을 깨달으셨군요~~ 👍🏻👍🏻👍🏻

2023-10-27 00:49 UTC, eunkeeee approved these changes
지식을 뽐내고 싶어 시작하다가 지식을 공유하는 재미를 알게 되었다는 서사가 좋네요!

2023-10-27 00:49 UTC, eunkeeee commented on level4.md
> +답을 알려주고 풀어주는 순간에 나는 만족감을 느꼈다.
욜

2023-10-27 00:49 UTC, eunkeeee commented on level4.md
> +어릴 때 나는 수학에 흥미를 느꼈다.
영재네요

2023-10-27 00:49 UTC, eunkeeee commented on level4.md
> +그 때 떠올랐던 이미지는 해커였다. 모니터 앞에서 코드 한 줄, 한 줄 타이핑하며,
앞에서는 수학이 좋다 지식 공유가 좋다했는데 갑자기 해커로 뭔가 감정선을 따라갈수가 없어요ㅜㅜ

2023-10-27 00:49 UTC, eunkeeee commented on level4.md
> +과거에는 지식을 뽐내는 데 중점을 뒀지만, 지금은 사용자의 관심 속에서 토론을 통해 성장하는 개발자를 꿈꾼다.
멋져요!

2023-10-28 11:00 UTC, dladncks1217 approved these changes
안녕하세요 비버!
비버가 개발자의 길을 걷게 된 서사가 있는 글이라 재미있었습니다👏👏
재미있게 잘 읽었습니다~!

2023-10-29 08:15 UTC, seokjin8678 approved these changes
고생하셨습니다!!!!

2023-10-29 19:51 UTC, rhthrhrl0 approved these changes
비버의 진정성이 잘 드러난 글 같네요! 재밌게 잘읽었습니다! 우테코에서 멋진 가치관을 찾아가신 것 같네요 👍

2023-10-29 19:51 UTC, rhthrhrl0 commented on level4.md
> +다른 사람들과의 토론을 통해 함께 성장하는 것의 가치를 알게 되었다.
저도 레벨3부터 자식 공유, 그리고 함께 성장하는 것의 가치를 느낀 것 같아요!

2023-10-29 19:51 UTC, rhthrhrl0 commented on level4.md
> +과거에는 지식을 뽐내는 데 중점을 뒀지만, 지금은 사용자의 관심 속에서 토론을 통해 성장하는 개발자를 꿈꾼다.
사용자의 관점에서 토론한다는 말 멋있네요!

2023-11-08 04:29 UTC, merged