[레벨 4 글쓰기 미션] 하디(전동혁) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #408
Opened 2023-10-22 10:52 UTC by jundonghyuk

안녕하세요 여러분(바론, 성하, 리오, 레오, 베베, 연어)

우테코도 끝나가네요. 

여러분의 우테코 생활은 어땠나요?

저는 꽤 좋았던 것 같아요. 

여기와서 좋은 사람들을 많이 만났기 때문입니다.

마지막 글쓰기 미션까지 같이 화이팅해봅시다 ! AZA AZA FIGHTING !

2023-10-22 12:48 UTC, youngh0 approved these changes
글 잘봤습니다 하디! 코딩이 재밌어서 하는 사람은 성장하는 속도가 진짜 무서운 거 같아요!! 하디씨의 미래가 기대되네요

그리고 최종목표 심플하니 멋있네요!  ㅋㅋㅋ

2023-10-22 12:48 UTC, youngh0 commented on level4.md
> +그러던 중 카카오 알고리즘 코딩테스트를 보았다. 부끄럽게도, 사실 지원하면서 백엔드/프론트엔드의 개념을 알게되었다.
이런거 몰라도 1차는 뚫으시네요 ㄷㄷ

2023-10-22 12:48 UTC, youngh0 commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
군대에서도 공부하다니 대단하시네요

2023-10-22 12:48 UTC, youngh0 commented on level4.md
> +주절주절 쓰다보니 글이 길어졌는데, 한마디로 요약하면 그냥 재밌어서 프로그래머가 되고 싶었다.
코딩이 재밌어서 개발자가 되고 싶으셨다니 멋있네요

2023-10-22 12:48 UTC, youngh0 commented on level4.md
> +사실 나는 감정의 스펙트럼이 일관되어서 크게 재미를 느껴본적이 없는데, 유일하게 2가지가 꼽자면 바로 수학문제풀기와 프로그래밍이다.
'2가지가' 오타난 것 같습니다!

2023-10-22 12:48 UTC, youngh0 commented on level4.md
> +이것이 지금의 전동혁이 생각하는 최종 목표이다.
멋있네요 동혁씨

2023-10-22 13:18 UTC, carsago approved these changes

2023-10-22 13:18 UTC, carsago commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
지금 돌아가시면 제가 이런 말씀 해드릴텐데, 죽으라고 말하긴 그러네요..

2023-10-23 08:45 UTC, eunkeeee approved these changes
감동이에요

2023-10-23 08:45 UTC, eunkeeee commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
ㅋㅋㅋ목소리가 들리네요

2023-10-23 08:45 UTC, eunkeeee commented on level4.md
> +우연히 백준이라는 알고리즘 문제 사이트를 접헀다.
햿

2023-10-23 08:45 UTC, eunkeeee commented on level4.md
> +사실 나는 감정의 스펙트럼이 일관되어서 크게 재미를 느껴본적이 없는데, 유일하게 2가지가 꼽자면 바로 수학문제풀기와 프로그래밍이다.
저같은 경우엔.. 9점이요
를 맨날 말하는 하디...

2023-10-23 08:45 UTC, eunkeeee commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
꽤괜〰️

2023-10-23 12:11 UTC, sh111-coder requested changes
글에서 하디의 마인드를 잘 느낄 수 있어서 좋았습니다 ㅎㅎㅎㅎ 👍🏻👍🏻👍🏻
코딩을 재밌게 느끼셔서 그렇게 잘 하시는 거였군요,,, 👍🏻

띄어쓰기 부분만 제안드렸는데 수정해주시면 바로 Approve 하겠습니다!!

2023-10-24 01:53 UTC, nuyh99 approved these changes
안녕하세요 하디!
오션이랑 팀플하면서 자주 봤던 것 같아요ㅋㅋㅋㅋㅋ
수학, 프로그래밍의 대가시군요...멋집니다!
approve 할게요!!

개인적으로 궁금한 거 하나만 더 남기자면...남은 기간 동안은 어떤 것에 열중하실 계획이신가요??

2023-10-24 01:53 UTC, nuyh99 commented on level4.md
> +자신의 10년 뒤 모습을 그리면서 일하는 사람이 얼마나 될까..
ㅋㅋㅋㅋㅋㅋㅋ공감합니다

2023-10-24 01:53 UTC, nuyh99 commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
개인적인 궁금증인데요...!
군대에서 c언어를 접하게 되신 계기가 뭔가요??!

2023-10-24 01:53 UTC, nuyh99 commented on level4.md
> +주절주절 쓰다보니 글이 길어졌는데, 한마디로 요약하면 그냥 재밌어서 프로그래머가 되고 싶었다.
다들 개발을 재밌어하는 사람들이 온 것 같아요. 좋습니당

2023-10-24 01:53 UTC, nuyh99 commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
최종 목표 달성 여부는 알 수 없겠군요

2023-10-25 10:31 UTC, wonyongChoi05 approved these changes
하디 글 잘 읽었습니다. 페어도 안해보고 팀프로젝트도 같이 안해봤는데, 왠지 모르게 저희 굉장히 자주 만나는 것 같다는 생각이 드네요 ㅎㅎ

솔직한 글 굉장히 인상 깊게 읽었습니다. 개발자가 된 이유, 어떠한 개발자가 되고 싶은지를 알 수 있었어요. 

이후의 전동혁이 이 글을 봐도 지금의 전동혁이 멋있게 느껴질 것 같네요. 앞으로 우테코가 얼마 남지 않았는데, 잘 마무리하시구 우테코를 들어오며 하디가 세웠던 목표와 결과를 이루셨다고 생각하시면 좋겠어요. 파이팅입니다!!

2023-10-25 10:31 UTC, wonyongChoi05 commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-10-25 10:31 UTC, wonyongChoi05 commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
저는 수학을 되게 싫어했는데 수학문제를 푸는게 재미있으시군요,, 우테코에는 대단한 사람이 너무 많아요 ㅠ ㅠ

2023-10-25 10:31 UTC, wonyongChoi05 commented on level4.md
> +그냥 한 번 사는거, 하고 싶은 일을 하면서 살고싶다.
크.. 그쵸 한 번 사는거 하고 싶은거 하면서 살아야 하는데, 대체하기 쉬울 수록 가치가 낮아지니 하고 싶은 일이라도 강박적으로 느껴질 때도 있다고 생각합니다. 근데 하고 싶은일이 뭔가요?

2023-10-25 10:31 UTC, wonyongChoi05 commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
배달 시간 예측도 하는데, 이거라고 예측 못할까요..?

2023-10-26 01:37 UTC, somsom13 approved these changes
안녕하세요 하디~~~~~
하디 음성지원이 되는 듯한 하디다운 글이었다고 생각합니다. 
정말 한결같고 솔직하신 점이 멋지다고 생각해요 ^__^ 

솔직한 글이라 정말 재밌게 잘 읽었슴니다 ㅎ.ㅎ 앞으로도 화이팅해요 꽤괜하디~~~~ 👍

2023-10-26 01:37 UTC, somsom13 commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ하디는 정말,, 한결같으시네요,,, 칭찬입니다,,

2023-10-26 01:37 UTC, somsom13 commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
역시 수학천재? 🐯

2023-10-26 01:37 UTC, somsom13 commented on level4.md
> +뭐 코딩테스트는 2차에서 떨어졌고, 그 때부터 본격적으로 진로를 찾기 시작했는데 운이 좋게도 우테코 백엔드에 합격할 수 있었다.
이 사람,,, 재능이 어마어마할지도?

2023-10-26 01:37 UTC, somsom13 commented on level4.md
> +인생의 반은 일을 하면서 살텐데, 오직 돈과 명예 등을 위해 재미도 없는 일을 한다는 것은 용납할 수 없었다.
멋진데요~!~!~!!!!! 저는 요즘 돈만 많이 주면 뭐든 상관없다는 마인드라서 부럽네용

2023-10-26 01:37 UTC, somsom13 commented on level4.md
> +그렇다면 꽤 괜찮은 프로그래머로 기억되는게 프로그래머로서의 최종 목표가 될 것 같다.
하디 꽤 괜찮은 프로그래먼데요~? 앞으로 마주치면 꽤괜하디라고 불러도 될까요?

2023-10-28 10:44 UTC, jundonghyuk commented on level4.md
> +그러던 중 카카오 알고리즘 코딩테스트를 보았다. 부끄럽게도, 사실 지원하면서 백엔드/프론트엔드의 개념을 알게되었다.
운이 좋았습니다.

2023-10-28 10:45 UTC, jundonghyuk commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
병장 때 시간이 남아서요..ㅋㅋ

2023-10-28 10:45 UTC, jundonghyuk commented on level4.md
> +주절주절 쓰다보니 글이 길어졌는데, 한마디로 요약하면 그냥 재밌어서 프로그래머가 되고 싶었다.
고맙습니다 ㅎㅎ

2023-10-28 10:47 UTC, jundonghyuk commented on level4.md
> +사실 나는 감정의 스펙트럼이 일관되어서 크게 재미를 느껴본적이 없는데, 유일하게 2가지가 꼽자면 바로 수학문제풀기와 프로그래밍이다.
유일하게와 두 가지.. ㅋㅋㅋㅋ 부끄럽네요..

2023-10-28 10:47 UTC, jundonghyuk commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
저 아직 젊어요

2023-10-28 10:47 UTC, jundonghyuk commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
말투가 글에도 묻어나나요..?

2023-10-28 10:47 UTC, jundonghyuk commented on level4.md
> +사실 나는 감정의 스펙트럼이 일관되어서 크게 재미를 느껴본적이 없는데, 유일하게 2가지가 꼽자면 바로 수학문제풀기와 프로그래밍이다.
습관인가봐요

2023-10-28 10:49 UTC, jundonghyuk commented on level4.md
> +그냥 한 번 사는거, 하고 싶은 일을 하면서 살고싶다.
고맙습니다 !

2023-10-28 10:50 UTC, jundonghyuk commented
> 안녕하세요 하디! 오션이랑 팀플하면서 자주 봤던 것 같아요ㅋㅋㅋㅋㅋ 수학, 프로그래밍의 대가시군요...멋집니다! approve 할게요!!
> 
> 개인적으로 궁금한 거 하나만 더 남기자면...남은 기간 동안은 어떤 것에 열중하실 계획이신가요??

남은 우테코기간은 평소에 미뤄두었던 공부를 좀 해보려고합니다..ㅋㅋ CS 등등.. 아직 모르는거 투성이라서요 ㅠ

2023-10-28 10:53 UTC, jundonghyuk commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
사실 컴퓨터 쪽에도 고등학교 때 관심이 있었어서 어떨까? 라는 생각에 한 번 책을 펼쳐봤습니다.

이 쪽 지식이 전무해서 근본 언어라 불리는 c언어를 했던 것 같아요 ㅋㅋ

2023-10-28 10:53 UTC, jundonghyuk commented on level4.md
> +주절주절 쓰다보니 글이 길어졌는데, 한마디로 요약하면 그냥 재밌어서 프로그래머가 되고 싶었다.
정말 공감합니다 ㅎㅎ 다들 개발을 좋아해서 이야기 나눌 때도 재밌습니다 ㅋㅋ

2023-10-28 10:54 UTC, jundonghyuk commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
죽어서야 알겠군요.. 사후세계에서 지켜보겠습니다

2023-10-28 10:54 UTC, jundonghyuk commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
공감하시나요?ㅋㅋ

2023-10-28 10:55 UTC, jundonghyuk commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
수학 자체를 좋아한다기 보다는 수학 문제 푸는걸 좋아하는 것 같아요 ㅋㅋㅋ
저는 베베가 더 대단해보이던데요..?

2023-10-28 10:56 UTC, jundonghyuk commented on level4.md
> +그냥 한 번 사는거, 하고 싶은 일을 하면서 살고싶다.
바로 이거입니다.. 개발자..

2023-10-28 10:56 UTC, jundonghyuk commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
칭찬 맞으시죠 ?

2023-10-28 10:57 UTC, jundonghyuk commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
좋아 O 잘 X ㅠㅠㅋ

2023-10-28 10:58 UTC, jundonghyuk commented on level4.md
> +뭐 코딩테스트는 2차에서 떨어졌고, 그 때부터 본격적으로 진로를 찾기 시작했는데 운이 좋게도 우테코 백엔드에 합격할 수 있었다.
사실 어떻게 붙은건지 아직도 이해 불가입니다ㅋㅋ
선발 기준이 궁금해지는..

2023-10-28 10:58 UTC, jundonghyuk commented on level4.md
> +인생의 반은 일을 하면서 살텐데, 오직 돈과 명예 등을 위해 재미도 없는 일을 한다는 것은 용납할 수 없었다.
또 일해보면 달라질 수도 있을 것 같아요ㅋㅋㅋㅋㅋㅋㅋㅋ

돈의 무서움을 느끼는 순간..

2023-10-28 10:58 UTC, jundonghyuk commented on level4.md
> +그렇다면 꽤 괜찮은 프로그래머로 기억되는게 프로그래머로서의 최종 목표가 될 것 같다.
부끄럽네요

2023-10-29 02:56 UTC, sh111-coder approved these changes
안녕하세요 하디!! 띄어쓰기 부분 잘 반영해주셔서 Approve 할게요!!!

바쁠텐데 수정해주셔서 감사합니다 ㅎㅎㅎㅎ 레벨 4 진짜 수고 많으셨어요 
같이 화이팅해봅시당 ㅎㅎㅎ

2023-10-29 04:15 UTC, wonyongChoi05 approved these changes
고생하셨습니다 하디 ㅎㅎ 
이만 Approve 하겠습니다!

2023-10-30 07:50 UTC, Jaeyoung22 approved these changes
하디 글 잘 읽었어요 저랑 비슷한 부분이 많네요 화이팅합시다

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +당장 올해 취업이 될지 안될지도 모르는데 10년 뒤의 모습을 왜 물어보는가..
점 세개씩 찍어주세요 국룰이니까

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +굉장히 단순했다. 나에겐 본전공이 재미가 없었고, 수학문제를 푸는 것을 좋아했고, 군대에서 우연히 c언어라는 것을 접했고,
와 C!

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +그냥 수학문제 풀듯이 알고리즘 문제를 푸는 것이 재밌었고, 그래서 이 분야를 복수전공으로 선택했다.
ㅋㅋ나랑 똑같네

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +대학생 3학년이 되어서야 처음으로 알고리즘, 자료구조, 이산수학이라는 수업을 수강했다.
이건 다르네

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +그러던 중 카카오 알고리즘 코딩테스트를 보았다. 부끄럽게도, 사실 지원하면서 백엔드/프론트엔드의 개념을 알게되었다.
오 나돈데

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +뭐 코딩테스트는 2차에서 떨어졌고, 그 때부터 본격적으로 진로를 찾기 시작했는데 운이 좋게도 우테코 백엔드에 합격할 수 있었다.
나는 이 때 API라는 게 있는 줄 처음 알았음

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +인생의 반은 일을 하면서 살텐데, 오직 돈과 명예 등을 위해 재미도 없는 일을 한다는 것은 용납할 수 없었다.
반 이상 일할수 있도록 기도 1일차

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +"그 사람? 꽤 괜찮은 사람이었어" 라고 말해주는 사람이 있으면 그걸로 족한다.
하디? 제가 아는 프로그래머 중 탑이었어요

2023-10-30 07:50 UTC, Jaeyoung22 commented on level4.md
> +이후의 나는 지금의 나와는 또 다르니.
darni

2023-11-08 04:30 UTC, merged