[레벨 4 글쓰기 미션] 참새(김규) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #413
Opened 2023-10-22 12:41 UTC by WaiNaat

썬샷 패트릭 우스 오리 야미 크롱 안녕하세요? 🐦 

벌써 마지막 미션이라니 믿기지가 않네요.. 시간을 도난당한 기분입니다
흘러가는 대로 쓰고 싶은 내용을 썼더니 반성문이 되어버렸네요 👀
바쁜 와중에도 읽어주셔서 미리 감사해요. 잘 부탁드립니다!

[즉시이동](https://github.com/WaiNaat/woowa-writing-5/blob/level4/level4.md)

2023-10-22 13:33 UTC, carsago reviewed
잘읽었습니다. 제 리뷰는 단어나 문장에 대한 코멘트라기 보다는 느낀점에 가까울 거에요.

제가 글을 읽고 느끼게 된 건 참새가 '저점'이라는 가치를 중요시 여긴다는 것이였습니다.

글 내용도 그러한 가치관을 프로그래밍을 통해 실현하는 여러 소과정들이 포함되어 있었구요.
하지만 제게 있어서 더 궁금했던 건 "이 분은 왜 그런 가치관을 가지게 됐을까?" 라는 부분이에요.

이를 알게되면 전 글을 더 몰입하고, 공감하면서 읽었을 것 같아요. 

아마 참새가 추구하는 저점이라는 가치를 프로그래밍적으로 구현하는 방법은 실력과 경험이 축적됨에 따라 지속적으로 바뀔거에요. 계속 실력이 쌓임에 따라 지금 코드적인 부분에서 고민했던 부분은 점차 체화되고 나중엔 당연한걸로 여겨질 거 잖아요?

다만 참새가 저점이라는 가치를 추구한다는 사실은 상대적으로 쉽게 바뀌지 않을 것 같네요. 그래서 그러한 생각을 왜 가지게 됐을까 라는 부분이 전 더 궁금했어요.

2023-10-23 03:51 UTC, feb-dain commented
안녕하세요 참새! 글 재밌게 잘 읽었습니다. 비유도 잘 해주셔서 소설 책 읽듯이 술술 읽었어요. 딱히 고칠 점은 없어 보입니다 ㅎㅎ

그리고 참새의 글을 읽으면서 참새의 프로젝트가 궁금해졌습니다😂 웹 접근성... 정말 잘 지키기 어려운 부분인 것 같아요. 설령 참새가 잘 지키지 못했다고 하더라도 염두에 두고 코드를 작성했다면 이미 좋은 시작을 했다고 생각합니다. 

참새는 점점 더 좋은 개발자가 될 것 같아요. 참새의 발전을 응원합니다!! 👍

2023-10-23 03:52 UTC, feb-dain approved these changes

2023-10-24 04:50 UTC, Gilpop8663 approved these changes
안녕하세요 참새

글 정말 잘 작성 하시네요 원래도 글 작성하는 것을 좋아한다고 알곤 있었지만 상상 이상이에요 😎

글 보면서 이해하기 어렵거나 추가되었으면 하는 부분에 코멘트 남겨보았습니다

코멘트 남긴 부분은 이상하거나 수정되었으면 하는 것까진 아니고 제안이라서 어프로브 하도록 하겠습니다

2023-10-24 04:50 UTC, Gilpop8663 commented on level4.md
> +저를 조류로 만들어 버린 바로 그 질문이에요. 하지만 당시에 뭐라 했는지는 기억나지 않았고 그 대답은 이곳이 아닌 인천에 잠들어 있다는 걸 알았습니다. 그때 말렸어야 했을까요? 제가 깨운 기억은 저 하늘 위 뜬구름이었거든요.
인천이 고향이신가요? 인천에 잠들어 있다는 설명이 듣고 싶어요

2023-10-24 04:50 UTC, Gilpop8663 commented on level4.md
> +제가 개발자를 선택한 이유도 저점 때문이에요. 개발자는 하나의 세계를 만들 수 있어요. 코드로 써 내려간 서사시는 산과 들, 강과 바다, 신과 악마, 왕과 영웅을 노래할 수 있죠. 토마스 아퀴나스의 말을 빌리자면 세계가 개발자의 의지에 맞춰지는 셈입니다. 이미 만들어진 세상을 바꾸는 것보다는 만들 수 있는 세상에서 조절하는 게 더 쉽겠다고 생각했어요.
사이트를 왜 이렇게 만들었을까 불평하는 것이 아니라 직접 좋게 만들고 싶으셨나봐요 🔥

2023-10-24 04:50 UTC, Gilpop8663 commented on level4.md
> +제가 생각하기에 개발자로서 작업하면서 고려할 만한 구체적인 저점은 크게 네 가지입니다. 첫째는 웹 표준과 접근성 지키기에요. 구름을 피울 때는 생각하지 못했었는데 그 모양을 현실에 빗대 보면 이게 아닌가 싶네요. 둘째는 테스트를 통해서 코드의 저점을 증명해야 합니다. 작은 함수를 미리 검증했었다면 금방 찾았을 텐데 하는 아쉬움이 남아요. 세 번째도 비슷하
사용자 경험─당연히 돼야 하는 게 되는─ 에서 조금 헷갈렸어요

-예상한 동작이 작동하는- 으로는 어떨까요?

2023-10-24 04:50 UTC, Gilpop8663 commented on level4.md
> +이상은 제가 서 있는 곳 이상에 있어서 이상입니다. 다행인 점은 초과가 아니라 이상이라는 거예요. 제 옆구리까지 끌어내릴 수는 있다는 말이겠죠? 제가 꿈꾸는 프로그래머로는 이 구름을 제 옆으로 끌어내리는 삶입니다. 떼를 좀 쓰자면 앞서 말한 것들을 벗어나 더 높은 구름을 원하긴 합니다. 이제 저에게는 코끼리를 삼킨 보아뱀이 아니라 모자만 보이지만 그래도
> 이상은 제가 서 있는 곳 이상에 있어서 이상입니다

이해하기가 어려워서 조금 풀어서 작성해주셔도 좋을 것 같아요

2023-10-24 06:33 UTC, GC-Park approved these changes
레벨 1 방학식 때 누구의 글이 가장 인상 깊었냐는 질문에 "참새의 글이요!"라고 대답했었는데요.

그때의 제가 왜 그렇게 말을 했는지 오늘 또 깨달아 버렸습니다. 참새의 작문, 딱 제 스타일이에요!!

너무 재미있게 읽었습니다! 바로 approve 할게요 !!!

2023-10-24 06:33 UTC, GC-Park commented on level4.md
> +> … 흔히 '사이버펑크'라고 하면 화려한 밤의 네온사인을 떠올립니다. 하지만 높은 마천루 뒤에는 가로등의 불빛조차 닿지 않는 슬럼가가 있습니다. 저는 '저점'을 굉장히 중요하게 생각합니다. 저는 저의 두 손으로 세상의 저점을 올려 뒤처지는 사람 없이 모두가 평등하게 웹에 접근하여 정보를 얻을 수 있는 프로그래밍을 하고 싶습니다.
진짜 그냥 글 리뷰하러 왔다가 감동 먹고 가버립니다 🥹 👍

2023-10-24 06:33 UTC, GC-Park commented on level4.md
> +하늘을 올려다봅니다. 구름은 때맞춰 불어오는 소슬바람에 흩어져 없어지고 떨어질 것처럼 깊은 하늘만이 보이네요. 스스로 저점이 되겠다고 그렇게 맹세했건만. 지금의 저에게선 저점도 고점도 잊고 그저 달리다 지쳐버린 경주마만 보이네요. 물론 이해합니다. 우아한테크코스의 모 크루가 했던 말이 기억나네요. '코드는 0과 1만 남을 때까지 분석할 수 있다.' 였던가
맞바람에 휩쓸리지 않은 참새..  칭찬합니다 !!  🐦

2023-10-24 06:33 UTC, GC-Park commented on level4.md
> +저점을 뭐라 설명하면 좋을까요? 어렵네요. '평등'이랑은 거리가 좀 있어요. 좀 오래 생각해 봤는데 '개똥밭에 굴러도 이승이 낫다'라는 말에서 '개똥밭'이랑 비슷해요. 온 세상 어디에도 개똥밭이 없다면 굴러도 진흙탕에서 구르겠죠? 진흙탕도 없다면 거기보단 좀 더 나은(?) 곳에서 구를 수 있을 거예요. 그런 느낌입니다.
조금 추상적일 수 있는 '저점'을 '개똥밭'에 비유해 주어서 이해하기 쉬운 것 같아요! 좀 더 나은 곳에서 구를 수 있는 세상이 오길... ~

2023-10-24 06:33 UTC, GC-Park commented on level4.md
> +이상은 제가 서 있는 곳 이상에 있어서 이상입니다. 다행인 점은 초과가 아니라 이상이라는 거예요. 제 옆구리까지 끌어내릴 수는 있다는 말이겠죠? 제가 꿈꾸는 프로그래머로는 이 구름을 제 옆으로 끌어내리는 삶입니다. 떼를 좀 쓰자면 앞서 말한 것들을 벗어나 더 높은 구름을 원하긴 합니다. 이제 저에게는 코끼리를 삼킨 보아뱀이 아니라 모자만 보이지만 그래도
> 이상은 제가 서 있는 곳 이상에 있어서 이상입니다.

> 코끼리를 삼킨 보아뱀이 아니라 모자만 보이지만 그래도 그것이 한때는 보아뱀이었음을 잊지 않는 삶을 살고 싶어요.

저도 이런 말 장난 무지 좋아하는데요... 😉

2023-10-24 08:38 UTC, krrong approved these changes
안녕하세요 참새! 크롱입니다.🦖

만나게 되어 반가워요! :)

참새의 글을 읽으면서 본인의 생각과 감정을 표현하는데 굉장한 능력이 있는 사람이구나 라고 계속 느꼈어요.  

세상의 저점을 올려 뒤처지는 사람 없이 모두가 평등해지는 것을 바란다는 말에서 많은 것들이 느껴지네요.

본인이 중요하게 생각하는 저점들을 알고 있고, 어떤 점들이 부족했는지를 많이 고민해보신 것 같아 충분히 좋은 방향으로 나아갈 수 있겠다는 생각이 듭니다!🤠

2023-10-24 08:38 UTC, krrong commented on level4.md
> +저를 조류로 만들어 버린 바로 그 질문이에요. 하지만 당시에 뭐라 했는지는 기억나지 않았고 그 대답은 이곳이 아닌 인천에 잠들어 있다는 걸 알았습니다. 그때 말렸어야 했을까요? 제가 깨운 기억은 저 하늘 위 뜬구름이었거든요.
어떤 표현을 하고 싶으셨던걸까요? 궁금하네요!🤔

2023-10-24 08:38 UTC, krrong commented on level4.md
> +저점을 뭐라 설명하면 좋을까요? 어렵네요. '평등'이랑은 거리가 좀 있어요. 좀 오래 생각해 봤는데 '개똥밭에 굴러도 이승이 낫다'라는 말에서 '개똥밭'이랑 비슷해요. 온 세상 어디에도 개똥밭이 없다면 굴러도 진흙탕에서 구르겠죠? 진흙탕도 없다면 거기보단 좀 더 나은(?) 곳에서 구를 수 있을 거예요. 그런 느낌입니다.
본인이 생각하는 저점과 독자가 생각하는 저점이 다를 수 있음에 설명을 해주셔서 좋았습니다!  

> 개발자는 하나의 세계를 만들 수 있어요.

굉장한 표현이네요..👍

2023-10-25 02:09 UTC, Ohjintaek requested changes
글을 굉장히 잘 쓰시네요!!! 글쓰기에 되게 익숙한 분이라고 짐작할 정도로 수려한 글이라고 느꼈습니다. 만약 참새에 대해 잘 알고 평소에 참새와 많이 대화를 나눴다면 훨씬 더 재밌게 글을 읽었을 수 있을 거 같은데 아쉬웠습니다😂

2023-10-28 12:30 UTC, carsago approved these changes

2023-10-30 07:06 UTC, WaiNaat commented on level4.md
> +저를 조류로 만들어 버린 바로 그 질문이에요. 하지만 당시에 뭐라 했는지는 기억나지 않았고 그 대답은 이곳이 아닌 인천에 잠들어 있다는 걸 알았습니다. 그때 말렸어야 했을까요? 제가 깨운 기억은 저 하늘 위 뜬구름이었거든요.
마음의 고향입니다ㅎㅎ 본가가 인천이에요

2023-10-30 07:07 UTC, WaiNaat commented on level4.md
> +제가 생각하기에 개발자로서 작업하면서 고려할 만한 구체적인 저점은 크게 네 가지입니다. 첫째는 웹 표준과 접근성 지키기에요. 구름을 피울 때는 생각하지 못했었는데 그 모양을 현실에 빗대 보면 이게 아닌가 싶네요. 둘째는 테스트를 통해서 코드의 저점을 증명해야 합니다. 작은 함수를 미리 검증했었다면 금방 찾았을 텐데 하는 아쉬움이 남아요. 세 번째도 비슷하
사용자 입장에서는 '당연히 되어야 하는 게 되는' 것이고 개발자 입장에서는 '예상한 동작이 작동하는' 것이라 생각합니다
사용자 쪽에 무게를 둔 표현이에요 👍

2023-10-30 07:10 UTC, WaiNaat commented on level4.md
> +이상은 제가 서 있는 곳 이상에 있어서 이상입니다. 다행인 점은 초과가 아니라 이상이라는 거예요. 제 옆구리까지 끌어내릴 수는 있다는 말이겠죠? 제가 꿈꾸는 프로그래머로는 이 구름을 제 옆으로 끌어내리는 삶입니다. 떼를 좀 쓰자면 앞서 말한 것들을 벗어나 더 높은 구름을 원하긴 합니다. 이제 저에게는 코끼리를 삼킨 보아뱀이 아니라 모자만 보이지만 그래도
이상(꿈)과 이상(A <= B)의 한글이 같다는 걸 이용한 장난이었습니다 😅
꿈은 저보다 높이 있지만 닿을 수 없지는 않다는 의미였어요

2023-10-30 07:12 UTC, WaiNaat commented on level4.md
> +> … 흔히 '사이버펑크'라고 하면 화려한 밤의 네온사인을 떠올립니다. 하지만 높은 마천루 뒤에는 가로등의 불빛조차 닿지 않는 슬럼가가 있습니다. 저는 '저점'을 굉장히 중요하게 생각합니다. 저는 저의 두 손으로 세상의 저점을 올려 뒤처지는 사람 없이 모두가 평등하게 웹에 접근하여 정보를 얻을 수 있는 프로그래밍을 하고 싶습니다.
1년 전 자소서 원문이라..부끄럽네요

2023-10-30 07:14 UTC, WaiNaat commented on level4.md
> +저를 조류로 만들어 버린 바로 그 질문이에요. 하지만 당시에 뭐라 했는지는 기억나지 않았고 그 대답은 이곳이 아닌 인천에 잠들어 있다는 걸 알았습니다. 그때 말렸어야 했을까요? 제가 깨운 기억은 저 하늘 위 뜬구름이었거든요.
'뜬구름 잡는 소리 한다'의 '뜬구름'처럼 허황된 꿈이었다는 말이었습니다!
작년 우테코 자소서에 썼던 내용이 기억나지 않아서 찾아봤는데 막연한 꿈을 꾸고 있었다는 내용입니다 👍

2023-10-30 07:15 UTC, WaiNaat commented on level4.md
> +그런데 웬걸? 이 꿈은 이상이자 욕심이 아니었나 싶어요. 프로젝트에서도, 미션에서도 저는 저점을 고려하지 않았거든요. 하다 보니 대략 끼워서 맞춰진 경우도 있어요. 하지만 마음속에서 외치는 소리에 따라 움직였던 적은 없었어요. '다음 시간에 계속'이라는 말만 되뇌면서 계속 미뤘습니다. 기약 없는 기다림이 얼마나 잔인한 건지 알면서도 말이죠. 누가 제 시간
😢

2023-10-30 07:23 UTC, WaiNaat commented on level4.md
> +제가 생각하기에 개발자로서 작업하면서 고려할 만한 구체적인 저점은 크게 네 가지입니다. 첫째는 웹 표준과 접근성 지키기에요. 구름을 피울 때는 생각하지 못했었는데 그 모양을 현실에 빗대 보면 이게 아닌가 싶네요. 둘째는 테스트를 통해서 코드의 저점을 증명해야 합니다. 작은 함수를 미리 검증했었다면 금방 찾았을 텐데 하는 아쉬움이 남아요. 세 번째도 비슷하
1. 문단이 바뀌면서 `실제 세상을 살아가는 사람들의 저점` 에서 `참새가 개발자로서 만드는 세상의 저점`으로 넘어간 게 맞습니다! 예전에는 막연한 꿈이었다면 지금은 제 능력의 한계로 인해 넓은 의미의 저점이 아니라 제가 걷는 길 위에서 만들 수 있는 저점을 추구하자는 생각으로 바뀌면서 의미가 좀 좁혀진 것 같아요. 저점이 중요한 이유는 글에 추가하겠습니다!!
2. 뜬구름(작년에 쓴 자소서의 사이버펑크 어쩌구 하는 부분)이랑 연결되어서 `모두가 평등하게 웹에 접근하여 정보를 얻을 수 있는` 이라는 말을 개발자식으로 옮기면 `웹 표준과 접근성 지키기`에 가깝겠다는 의미입니다 👍 
3. 제가 코드를 리팩터링할 때 항상 고민하는 '도대체 어디까지 추상화를 하는 게 좋은지'에 대한 고민을 담았습니다 😅 과도한 추상화랑 추상화를 아예 하지 않는 것 사이에서 갈등하는 모습이에요

2023-10-30 08:13 UTC, Ohjintaek commented on level4.md
> +제가 생각하기에 개발자로서 작업하면서 고려할 만한 구체적인 저점은 크게 네 가지입니다. 첫째는 웹 표준과 접근성 지키기에요. 구름을 피울 때는 생각하지 못했었는데 그 모양을 현실에 빗대 보면 이게 아닌가 싶네요. 둘째는 테스트를 통해서 코드의 저점을 증명해야 합니다. 작은 함수를 미리 검증했었다면 금방 찾았을 텐데 하는 아쉬움이 남아요. 세 번째도 비슷하
질문이 너무 많았는데 하나하나 다 잘 답변해주셔서 감사합니다!!

2023-10-30 08:14 UTC, Ohjintaek approved these changes
글쓰기 미션 수고하셨습니다!!! 한 문단을 추가하는 건 쉽지 않은 일이었을텐데 대단하시네요 👍👍

2023-11-08 04:30 UTC, merged