[레벨 4 글쓰기 미션] 가브리엘(윤주현) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #426
Opened 2023-10-22 19:40 UTC by gabrielyoon7

2023-10-24 00:17 UTC, Choi-JJunho approved these changes
가브리엘 안녕하세요!
우테코 마지막 미션을 함께하게되어 영광입니다 🥹
전체적으로 글을 깔끔하게 작성해주셔서 Approve 하겠습니당~
몇가지 코멘트만 확인 부탁드릴게욥

2023-10-24 00:17 UTC, Choi-JJunho commented on level-4.md
> +`다양한 도메인에 도전`할 수 있다는 것이 프로그래머의 매력이라고 생각했고, 지금도 그런 것 같습니다.
완전 공감해요!!😆

2023-10-24 00:17 UTC, Choi-JJunho commented on level-4.md
> +하지만 `문제를 인지할 수 있는 능력은 특별하다고 생각`합니다.
프로불편러가 크레딧을 만든다는 말이 생각나는군요 😊

2023-10-24 00:17 UTC, Choi-JJunho commented on level-4.md
> +전 세계 프로그래머들이 더 나은 방법으로 개발하는 분위기라면 그 분위기에 맞춰야 합니다.
공부에 왕도가 없다는 문단의 흐름에서 봤을 때 약간 어색한 문장같아요!

해당 줄과 다음줄에있는 
`나 홀로 잘났다고 생각하며 과거에 머무를 수 없습니다.`
라는 문장들은 생략해도 좋아보여요!

2023-10-24 00:17 UTC, Choi-JJunho commented on level-4.md
> +특히 모던 프런트엔드 개발을 하다 보면 중요한 것을 놓칠 때가 많습니다.
뭔가 **프론트엔드**로 많이 사용했다보니 다소 어색하게 느껴지는 감이 있어 찾아봤는데 국립국어원에 따르면 **프런트엔드**가 적합한 표현이였군요!

하나 알아갑니다👍

https://www.inflearn.com/blogs/2544

2023-10-24 00:17 UTC, Choi-JJunho commented on level-4.md
> +어떤 회사가 제 첫 직장이 될지 알 수 없지만, 앞서 언급한 꿈들이 이뤄질 수 있는 곳이 마지막 회사였으면 좋겠습니다.
**앞서 언급한 꿈**에 대해 간략하게라도 요약해주면 좋을 것 같아요!

2023-10-24 01:28 UTC, TaeyeonRoyce approved these changes
안녕하세요, 가브리엘!
구체적인 꿈에 가브리엘의 깊은 가치관이 잘 드러나서 인상깊네요!
잘 읽었습니다

2023-10-24 01:28 UTC, TaeyeonRoyce commented on level-4.md
> +제 꿈을 제대로 펼치기 위한 곳에 취업하려면 정말 많은 노력이 필요한데요, 그렇다면 제 꿈은 무엇일까요?
```suggestion
제 꿈을 제대로 펼치기 위한 곳에 취업하려면 정말 많은 노력이 필요한데, 그렇다면 제 꿈은 무엇일까요?
```

혹은 

```suggestion
제 꿈을 제대로 펼치기 위한 곳에 취업하려면 정말 많은 노력이 필요한데요.
그렇다면 제 꿈은 무엇일까요?
```
<br>
이렇게 변경해보시는건 어떠신가요?

2023-10-24 01:28 UTC, TaeyeonRoyce commented on level-4.md
> +`다양한 도메인에 도전`할 수 있다는 것이 프로그래머의 매력이라고 생각했고, 지금도 그런 것 같습니다.
저도 이 매력을 많이 느낍니다!!
프로그래밍은 어느 도메인에서도 가치를 지니며 존재할 수 있다는 점이 다방면에 관심이 많은 사람들에겐 정말 매력적이더라고요!

2023-10-24 01:28 UTC, TaeyeonRoyce commented on level-4.md
> +그 꿈이 아직 유효하지만, 지금은 그 생각이 조금 바뀌어 `한가지 도메인 안에서도 여러 방향으로 활약할 수 있다고 생각`하게 되었습니다.
"그 꿈"은 `다양한 도메인에 도전` 일까요?
갑자기 꿈이라는 단어가 등장해서 파악하기 조금 어려웠습니다!

2023-10-24 01:28 UTC, TaeyeonRoyce commented on level-4.md
> +저의 꿈은 `다른 개발자들에게 영감을 주고 협력하여 혁신적이고 의미 있는 소프트웨어를 만드는 것`입니다.
구체적이고 명확한 꿈이네요👍

2023-10-24 16:11 UTC, gabrielyoon7 commented on level-4.md
> +제 꿈을 제대로 펼치기 위한 곳에 취업하려면 정말 많은 노력이 필요한데요, 그렇다면 제 꿈은 무엇일까요?
반영했습니다!

2023-10-24 16:12 UTC, gabrielyoon7 commented on level-4.md
> +전 세계 프로그래머들이 더 나은 방법으로 개발하는 분위기라면 그 분위기에 맞춰야 합니다.
반영했습니다!

2023-10-24 16:16 UTC, gabrielyoon7 commented on level-4.md
> +어떤 회사가 제 첫 직장이 될지 알 수 없지만, 앞서 언급한 꿈들이 이뤄질 수 있는 곳이 마지막 회사였으면 좋겠습니다.
반영했습니다!

2023-10-26 18:20 UTC, n0eyes requested changes

2023-10-26 18:20 UTC, n0eyes commented on level-4.md
> +세상의 거의 모든 일들이 소프트웨어와 강하게 결합 되었다고 생각했기에 프로그래머가 되고 싶었고, 컴퓨터공학을 전공했습니다.
혹시 그렇게 느낀 계기가 있을까요!?

만약 그렇다면 계기도 함께 작성해 주시면 훨씬 자연스럽고 설득력 있을 것 같아요 😄

2023-10-26 18:20 UTC, n0eyes commented on level-4.md
> +없는 문제를 만들고 싶다는 것은 아니지만, 완벽에 가까워지기 위해서는 `진정한 문제가 무엇인지 인지할 수 있는 능력`을 갖춰야 할 것입니다.
감명입니다..👍

2023-10-26 18:20 UTC, n0eyes commented on level-4.md
> +개발 공동체에 기여하는 것은 개발자로서의 삶을 더욱 의미 있게 만든다고 생각하며, 다양한 아이디어와 통찰력을 공유하는 것은 언제나 즐겁습니다.
저도 공동체에 기여하는 것이 목표인데 가브리엘도 같은 생각이시군요!

2023-10-26 18:21 UTC, n0eyes commented
안녕하세요, 가브리엘!

좋은 글 잘 읽었습니다!
간단한 코멘트 정도 남겼는데 확인 부탁드려요!

2023-10-28 11:26 UTC, echo724 approved these changes
안녕하세요 가브리엘! 레벨 3,4때 옆 팀으로서 지켜보기만 했었는데 이렇게 글로 만날 수 있게 되었네요 ㅎㅎ 생각하시는 바를 문단을 나누어 전달해주셔서 잘 이해가 됐던것 같습니다! 미션 화이팅 하세요~~!

2023-10-28 11:26 UTC, echo724 commented on level-4.md
> +어렸을 때부터 세상에 관심이 너무 많았습니다.
너무라는 표현은 빼거나 다른 표현으로 바꿔도 좋을 것 같습니다~

2023-10-28 11:26 UTC, echo724 commented on level-4.md
> +매일 같이 세상 사람들 사는 이야기에 관심을 가졌기에 하고 싶은 일이 너무 많았습니다.
이부분도요!

2023-10-28 11:26 UTC, echo724 commented on level-4.md
> +없는 문제를 만들고 싶다는 것은 아니지만, 완벽에 가까워지기 위해서는 `진정한 문제가 무엇인지 인지할 수 있는 능력`을 갖춰야 할 것입니다.
좋은 인사이트를 주시네요! ㅎㅎ

2023-10-28 11:26 UTC, echo724 commented on level-4.md
> +그러기 위해서는 누군가가 만족하고 있는지, 불편함은 없는지 인지 하면서 해결을 하고 싶습니다.
```suggestion
그러기 위해서는 누군가가 만족하고 있는지, 불편함은 없는지 등 문제를 명확히 정의하여 해결하고 싶습니다.
```
인지라는 중복 표현을 제거하고 위의 예시를 묶어 표현해봤습니다!

2023-10-28 11:26 UTC, echo724 commented on level-4.md
> +### 협력
각 문단의 크기를 비슷하게 맞춰주면 좋을꺼 같아요! 문단 길이에 따라 전달력도 조금 달라진다고 생각합니다!

2023-10-28 12:58 UTC, jw-r approved these changes
가브리엘 안녕하세요~!
이미 너무 좋은 리뷰들이 많이 달려서 거의 감상하듯 읽었네요🤣

주제에 알맞게 프로그래머로서의 꿈과 희망이 굉장히 잘 표현된 것 같아요!
각 문단에서 말하고자 하는 바가 명확해서 읽기 편안했습니다👍

바쁜 와중에 고생하셨어요!!!

2023-10-28 12:58 UTC, jw-r commented on level-4.md
> +### 협력
팀워크의 중요성과 협력을 통한 성장의 중요성에 대해 잘 작성된 문단인 것 같아요👍

2023-10-28 13:53 UTC, gabrielyoon7 commented on level-4.md
> +어렸을 때부터 세상에 관심이 너무 많았습니다.
반영하였습니다

2023-10-28 13:53 UTC, gabrielyoon7 commented on level-4.md
> +매일 같이 세상 사람들 사는 이야기에 관심을 가졌기에 하고 싶은 일이 너무 많았습니다.
반영하였습니다

2023-10-28 13:54 UTC, gabrielyoon7 commented on level-4.md
> +세상의 거의 모든 일들이 소프트웨어와 강하게 결합 되었다고 생각했기에 프로그래머가 되고 싶었고, 컴퓨터공학을 전공했습니다.
앞으로의 진로를 선택할 때 이것 저것 다 할 수 있는 사람이 되고 싶었습니다..ㅎㅎ
수정하였습니다

2023-10-28 13:58 UTC, gabrielyoon7 commented on level-4.md
> +그러기 위해서는 누군가가 만족하고 있는지, 불편함은 없는지 인지 하면서 해결을 하고 싶습니다.
반영하였습니다

2023-10-28 14:04 UTC, gabrielyoon7 commented on level-4.md
> +### 협력
반영했습니다

2023-10-29 12:47 UTC, ezzanzzan approved these changes
안녕하세요 가브리엘 ! 백엔드 토리입니다 ˙ᵕ˙ 
글의 양이 조금 있는데도 빠져서 읽느라 세부 코멘트 다는 것도 잊었네요 ...🥲
소제목으로 나눠진 문단들에서 가브리엘이 어떤 프로그래머가 되고 싶은지, 어떤 부분을 중요하게 생각하는지 잘 이해할 수 있었어요.
앞으로의 가브리엘의 프로그래머로서의 길을 응원합니다 !! 👍

2023-10-29 12:47 UTC, ezzanzzan commented on level-4.md
> +저의 꿈은 `다른 개발자들에게 영감을 주고 협력하여 혁신적이고 의미 있는 소프트웨어를 만드는 것`입니다.
멋있어요 👍

2023-10-29 13:24 UTC, n0eyes approved these changes
안녕하세요, 가브리엘 😄

코멘트 확인해 주셔서 감사합니다.

좋은 글 잘 읽었습니다!

2023-11-08 04:30 UTC, merged