[레벨 4 글쓰기 미션] 토마스(김대현) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #458
Opened 2023-10-23 06:40 UTC by ki960213

안녕하세요, 베르, 베로, 파워, 황펭, 블랙캣, 센트!
리뷰어로 만나게 되어 반갑습니다 😄 
부족한 점이 있다면 따끔한 지적 부탁드립니다! 🙏 
[읽으러 가기](https://github.com/ki960213/woowa-writing-5/blob/level4/level4.md)

2023-10-23 11:53 UTC, SeongHoonC requested changes
안녕하세요. 토마스!
글 잘 봤습니다. 저도 빠르고 정확하게 개발하는 개발자가 되고싶네요!
같이 화이팅해봐요~

2023-10-23 11:53 UTC, SeongHoonC commented on level4.md
> +레벨 4 때는 우리가 만든 앱에 대한 피드백을 받고 기능 추가 및 리팩토링 경험을 했다.
정말 많은 경험을 했네요ㅎㅎ

2023-10-23 11:53 UTC, SeongHoonC commented on level4.md
> +레벨 4 때는 우리가 만든 앱에 대한 피드백을 받고 기능 추가 및 리팩토링 경험을 했다.
각 문장의 끝맺음을 통일했으면 더 좋겠어요! 명사 or 동사

2023-10-23 11:53 UTC, SeongHoonC commented on level4.md
> +그래도 나는 빠르고 정확하게 원하는 기능을 개발할 수 있는 프로그래머가 되고 싶다.
빠르고 정확하게 구현하는 것이 경험이 많이 필요로해서 어렵더라구요..

2023-10-25 00:43 UTC, thdwoqor approved these changes
안녕하세요. 토마스!
저도 가치있는 프로그램을 만드는 개발자가 되고싶네요
수고하셨습니다 👍

리뷰는 필요하다고 생각하시면 반영해주세요

2023-10-25 00:43 UTC, thdwoqor commented on level4.md
> +우아한테크코스에서는 많은 것들을 배웠다.
> 이 생각이 가장 먼저 떠오르고 가장 중요하다고 생각한다.

중요하다고 생각하는 생각이 다음 문장에 나올거같은데

> 우아한 테크코스에서는 많은 것들을 배웠다.

라는 문장이 나와서 조금 부자연스러운것 같아요 🥲

2023-10-25 00:43 UTC, thdwoqor commented on level4.md
> +협업하면서 동료의 통찰력을 얻는 것도 좋은 프로그래머가 되기에 도움이 된다고 생각한다.
'동료의 통찰력을 얻는다' 가 어떤 의미인가요?

2023-10-25 00:43 UTC, thdwoqor commented on level4.md
> +동료에게 좋은 정보를 공유하는 것은 동료가 빠르고 정확하게 프로그래밍할 수 있게 만든다.
좋은 정보를 공유하는것도 중요하죠 👍

2023-10-28 14:03 UTC, Cyma-s approved these changes
안녕하세요 토마스! 토마스의 가치관이 담긴 글 잘 보았습니다 👍 수정하면 더 매끄러워질 부분은 커멘트로 남겨두었어요! 납득할만한 피드백이라고 생각하시면 반영해주세요 :) 
우테코에서 배웠던 것처럼, 개발자로 살아갈 인생에서 토마스가 멋진 가치를 발견하기를 바랄게요! 앞으로의 우테코 생활도 파이팅이에요 🚀

2023-10-28 14:03 UTC, Cyma-s commented on level4.md
> +누군가의 아이디어를 빠르게 구현해 가치를 만들고 싶다.
조금 더 자세히 설명해주시면 이해가 더 잘 될 것 같아요!

2023-10-29 06:57 UTC, kyw0716 approved these changes
글 정말 재밌게 잘 읽었습니다!! 전문성이 뛰어난, 빠르고 정확하게 원하는 기능을 구현할 수 있는 개발자가 되시길 응원하겠습니다👍

2023-10-29 06:57 UTC, kyw0716 commented on level4.md
> +레벨 4 때는 우리가 만든 앱에 대한 피드백을 받고 기능 추가 및 리팩토링 경험을 했다.
각 레벨에 어떤걸 했는지 정리한 부분 좋네요 👍

2023-10-29 06:57 UTC, kyw0716 commented on level4.md
> +그래도 나는 빠르고 정확하게 원하는 기능을 개발할 수 있는 프로그래머가 되고 싶다.
확고한 목표가 있는게 멋지십니다!!

2023-10-29 09:46 UTC, Leejin-Yang approved these changes
안녕하세요 토마스.! 리뷰가 늦어 죄송합니다 🥲
토마스가 이루고자 하는 목표 꼭 이루시길 바랍니다.!
레벨 4까지 고생했어요 👍

2023-10-29 09:46 UTC, Leejin-Yang commented on level4.md
> +이 모든 것들은 사실 실용적인 프로그램을 빠르고 정확하게 만들기 위해 필요한 것들이라고 생각한다.
토마스가 우테코 과정을 진행하며서 든 생각을 정리해주어서 좋아요 👍

2023-10-29 09:46 UTC, Leejin-Yang commented on level4.md
> +나도 그렇다.
저도 그렇습니다 😂

2023-10-29 14:36 UTC, Songusika approved these changes
안녕하세요 토마스!

글 잘 읽었습니다!
저도 빠르고 정확한 프로그래머가 되고 싶은데
너무 어렵네요 ㅜㅠ

간단한 리뷰 남겼어요!
보시고 괜찮다고 생각드시면 적용하면 좋을 것 같습니다!

우테코 마지막까지 화이팅입니다!

2023-10-29 14:36 UTC, Songusika commented on level4.md
> +이 모든 것들은 사실 실용적인 프로그램을 빠르고 정확하게 만들기 위해 필요한 것들이라고 생각한다.
```suggestion
이 모든 것들은 실용적인 프로그램을 빠르고 정확하게 만들기 위해 필요한 것들이라고 생각한다.
```
토마스의 생각이어서 사실을 빼도 좋을 것 같아요!
문장을 읽기에도 더 쉬워지고요!!

2023-10-29 14:36 UTC, Songusika commented on level4.md
> +즉, 실용적인 프로그램을 빠르고 정확하게 만들기 위한 수단이다.
바로 윗줄과 내용이 겹치기 때문에 제거해도 좋을 것 같아요!

2023-10-29 14:36 UTC, Songusika commented on level4.md
> +동료에게 좋은 정보를 공유하는 것은 동료가 빠르고 정확하게 프로그래밍할 수 있게 만든다.
```suggestion
동료에게 좋은 정보를 공유하는 것은 동료가 빠르고 정확한 프로그래밍할 수 있게 만든다.
```

이렇게 고치면 조금 더 읽기에 편해지네요!

2023-10-29 17:21 UTC, SeongHoonC approved these changes
글쓰기 미션 고생하셨어요!
레벨 5 화이팅입니다!

2023-11-08 04:31 UTC, merged