[레벨 4 글쓰기 미션] 센트(김영우) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #466
Opened 2023-10-23 07:00 UTC by kyw0716

안녕하세요 베로 베르 파워 황펭 블랙캣 토마스!
내가 꿈꾸는 프로그래머로서의 삶을 주제로 글을 써보다가 왜 개발자를 꿈꾸게 됐는지로 다소 변질된 것 같은데 열심히 적어 봤습니다!
마지막 글쓰기 미션 리뷰 잘 부탁 드릴게요 👍👍

[편하게 보기](https://github.com/kyw0716/woowa-writing-5/blob/level-4/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4%20%ED%95%9C%20%EB%8B%AC%20%EC%83%9D%ED%99%9C%EA%B8%B0.md)

2023-10-23 12:27 UTC, SeongHoonC requested changes
안녕하세요. 센트! 
솔직한 글 읽어서 너무 좋네요!
감사합니다ㅎㅎ

2023-10-25 01:05 UTC, thdwoqor approved these changes
안녕하세요. 센트!
저도 크롤링 하기위해서 웹을 공부해서 공감도 많이가고 재밌게 잘읽었습니다.
수고하셨습니다 👍

리뷰는 필요하다고 생각하시면 반영해주세요

2023-10-25 01:05 UTC, thdwoqor commented on 레벨4.md
> +지금까지 재미 주도 인생을 살아서 어쩌면 이 분야에 대한 흥미가 식는다면 개발자가 더 이상 내 꿈이 아니지 않을까 하는 생각도 든다.
재미 주도 개발 공감 가네요!

2023-10-28 12:59 UTC, ki960213 requested changes
반갑습니다, 센트!
센트의 솔직함 덕분에 지금까지 읽은 글 중 가장 재미있게 읽었습니다 👍 
글을 잘 쓰셔서 리뷰 할 게 많이 없네요 😊

2023-10-28 12:59 UTC, ki960213 commented on 레벨4.md
> +이번 글의 주제는 앞으로 내가 꿈꾸는 프로그래머로서의 삶인데 지금까지 구구절절 개발자를 꿈꾸게 된 과정을 얘기해 의아했을 것이다. 일단 주제에 대한 답을 먼저 하자면 솔직하게 `아직 없다`가 내 답이다.
위의 글을 읽을 때 의아하지 않게 하는 글을 위에 추가하면 좋을 것 같아요.

2023-10-28 13:54 UTC, Cyma-s approved these changes
안녕하세요 센트! 지금까지 프로그래밍을 어떻게 공부해오셨고, 어떤 마음으로 개발자를 했는지 잘 적어주셔서 재밌게 읽었습니다 :)
센트는 우아한테크코스를 진행하시면서 지금 되고 싶으시다고 하셨던 '주변 사람들에게 도움을 줄 수 있을만한 능력 있는 개발자' 에 한 발짝 가까워지고 계신가요? 개발자로서의 삶이 우리의 인생에 어떤 영향을 미치고 있을지에 대해 생각해보신다면 인생을 좀 더 재밌게 살아갈 수 있지 않을까요? ㅎㅎ 개인적인 생각입니다 😄

얼마 남지 않은 우테코 생활도 파이팅입니다!

2023-10-28 13:54 UTC, Cyma-s commented on 레벨4.md
> +생각보다 별로 인기가 없던 이 동아리의 활동은 다른 친구들에게는 상당히 생소해서 사소한 코드 한 줄도 자랑거리가 될 수 있었다.
'생각보다' 라는 표현이 반복되는 것 같아서, 이렇게 바꿔보면 어떨까 싶어요!

```suggestion
처음 만난 프로그래밍은 되게 별로였다. 별 찍기 문제를 풀다 내가 왜 이걸 하고 있지 싶었다.

생각했던 것보다 별로 인기가 없던 이 동아리의 활동은 다른 친구들에게는 상당히 생소해서 사소한 코드 한 줄도 자랑거리가 될 수 있었다.
```

2023-10-28 13:54 UTC, Cyma-s commented on 레벨4.md
> +그렇게 놀다 보니 인생의 큰 시련(군대...)이 찾아왔고 왜인지 모르겠지만 괜한 반항심이 들어 더 놀았던 것 같다.
~ 같다라는 어미가 반복되어서, `더 놀았다` 같이 간결하게 적어보는 건 어떨까요?

2023-10-28 13:54 UTC, Cyma-s commented on 레벨4.md
> +크롤러를 만들자고 시작한 공부가 html 태그 공부로 변질되었고 그러다 단순 페이지 레이아웃 만들기가 재미있어졌다. 그렇게 구글, 네이버 메인 페이지의 레이아웃을 따라 만들어 보고 뿌듯한 마음에 구현한 페이지를 캡쳐해 인스타 스토리로 올려보았다.
저도 프로그래밍 처음 배우면서 html 태그 공부했던 게 기억나네요 ㅋㅋㅋ

2023-10-28 13:54 UTC, Cyma-s commented on 레벨4.md
> +지금까지 재미 주도 인생을 살아서 어쩌면 이 분야에 대한 흥미가 식는다면 개발자가 더 이상 내 꿈이 아니지 않을까 하는 생각도 든다.
재미 주도 인생 공감합니다 👍🏻

2023-10-29 07:01 UTC, kyw0716 commented on 레벨4.md
> +별거 없는 활동에도 친구들에게 자랑하면서 이 분야에 재미를 느끼게 되었다. 이때부터 막연하게 개발자를 꿈꿨던 것 같다.
진짜 개발자를 꿈꿨던게 저 시기인지 확신이 없어서 저렇게 적어봤습니다 ㅠㅠ

2023-10-29 07:04 UTC, kyw0716 commented on 레벨4.md
> +아직 멋진 꿈은 없어 `아직 없다`로 내가 꿈꾸는 프로그래머로서의 삶에 대해 답변했지만, 최근 들어 작은 목표 한 가지가 생겼다.
감사합니다 👍👍

2023-10-29 09:56 UTC, Leejin-Yang approved these changes
센트 안녕하세요~
레벨1때 페어를 했었는데 벌써 레벨5네요.. 시간이 참 빨리간거 같아요
센트가 프로그래밍 시작하게 된 계기를 재밌게 읽을 수 있었습니다.!
남은 기간 파이팅이고 앞으로도 응원하겠습니다 😊

2023-10-29 09:56 UTC, Leejin-Yang commented on 레벨4.md
> +> "너 프론트 공부하냐? 같이 해커톤 ㄱㄱ?"
센트는 해커톤이 큰 계기였군요 !

2023-10-29 09:56 UTC, Leejin-Yang commented on 레벨4.md
> +지금까지 재미 주도 인생을 살아서 어쩌면 이 분야에 대한 흥미가 식는다면 개발자가 더 이상 내 꿈이 아니지 않을까 하는 생각도 든다.
저도 재미 없으면 하기 싫습니다 😂

2023-10-29 09:56 UTC, Leejin-Yang commented on 레벨4.md
> +앞으로 어떤 개발자가 되고 싶냐고 물어본다면 잘 모르겠다고 대답하겠지만, 지금 당장 어떤 개발자가 되고 싶냐고 물어본다면 내게 도움을 주셨던 다른 멋진 개발자 분들처럼 주변 사람들에게 도움을 줄 수 있을 만한 능력 있는 개발자가 되고 싶다고 답하고 싶다.
지금도 주변에 센트에게 도움 받은 사람이 많을거에요.! 멋진 꿈이네요 👍

2023-10-29 14:29 UTC, Songusika approved these changes
안녕하세요 센트! 
글 잘 읽었습니다!

아직 어떤 프로그래머가 되고 싶은지 없다고 하셨지만
'남들에게 도움이 될 수 있는 개발자' 로 볼 때 이미 어떤 개발자가 되고 싶으신건지 
알 것 같아요! 

이미 다른 리뷰어님들이 좋은 리뷰를 많이 남겨주셔서 간단한 리뷰만 남겼습니다!
우테코 마지막까지 화이팅입니다!

2023-10-29 14:29 UTC, Songusika commented on 레벨4.md
> +짧은 기간이었지만 뭔가 해본 걸 써볼 수 있겠다는 생각에 학생회 홈페이지 개발을 주제로 해커톤에 참가하게 되었다.
```suggestion
짧은 기간이었지만 뭔가 해본 걸 써볼 수 있다는 생각에 학생회 홈페이지 개발을 주제로 해커톤에 참가하게 되었다.
```

조금 더 읽기가 쉬운것 같아요!

2023-10-29 14:29 UTC, Songusika commented on 레벨4.md
> +앞으로 어떤 개발자가 되고 싶냐고 물어본다면 잘 모르겠다고 대답하겠지만, 지금 당장 어떤 개발자가 되고 싶냐고 물어본다면 내게 도움을 주셨던 다른 멋진 개발자 분들처럼 주변 사람들에게 도움을 줄 수 있을 만한 능력 있는 개발자가 되고 싶다고 답하고 싶다.
저는 이게 되게 큰 포인트라고 생각해요!
저희 또한 여러 유튜브, 블로그, 혹은 강의 들을 보면서 개발을 공부하였고
그들 때문에 여기까지 올 수 있었거든요!

'선한 영향력'을 줄 수 있는 꿈 응원합니다!👍👍

2023-10-29 17:19 UTC, SeongHoonC approved these changes
글쓰기 미션 고생 많으셨습니다!
화이팅!

2023-10-30 04:24 UTC, ki960213 approved these changes
리뷰 잘 반영하셔서 더 이상 리뷰할 게 없네요 👍
앞으로도 원하는 목표를 이루시길 바랍니다! 😊

2023-11-08 04:31 UTC, merged