[레벨 4 글쓰기 미션] 코건(김도엽) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #468
Opened 2023-10-23 07:09 UTC by DYGames

안뇽하세요~
리뷰 잘 부탁드립니다~!

2023-10-24 08:19 UTC, 2yunseong requested changes
안녕하세요 코건!
코건이 어떤 개발자가 되고 싶은지와 함께 어릴때부터 프로그래밍에 가진 관심등이 보이는 글이기도 해서 인상깊네요 ㅎㅎ
글 잘 읽었습니다! 몇 가지 질문 남겼으니 이야기해보시죠!

2023-10-24 08:19 UTC, 2yunseong commented on Level4.md
> +초등학교 5학년 쯤이었는데, 게임을 즐겨하던 나는 스스로 이를 만들어 보고싶다고 생각했다.
오 저도 그런생각을 했어요 ㅎㅎ

2023-10-24 08:19 UTC, 2yunseong commented on Level4.md
> +이러한 성취를 기반으로 반복해서 게임을 만들었고, 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
`계속해서`는 어떨까요? 개인적인 생각인데 반복이라는 의미는 무언가 같은 걸 반복하는 느낌이여서요!
`계속해서` 라는 문장으로 뒤에 따라오는 조금 점진적인 느낌을 살릴수 있지 않을까라고 생각했습니다!
극히 개인적인 의견이여서 고민해보시고 코건이 판단하시죵
```suggestion
이러한 성취를 기반으로 계속해서 게임을 만들었고, 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
```

2023-10-24 08:19 UTC, 2yunseong commented on Level4.md
> +하프라이프는 엄청난 인기를 얻었고, 여러 모드도 제작되었는데 이 중 카운터 스트라이크라는 모드가 인기를 얻고 개별 게임으로도 출시되었다.
카운터 스트라이크가 원래는 하프라이프라는 게임에 속해있었군요!

2023-10-24 08:19 UTC, 2yunseong commented on Level4.md
> +## 게임엔진연구회와 RoomPager
RoomPager는 어떤내용일까요? 디깅룸에 관련된 내용일까요??

2023-10-24 08:19 UTC, 2yunseong commented on Level4.md
> +제목은 거창하게 새로운 기술을 선도하고 적어놨지만 누구나 기술을 선도할 수 있는 것은 아닐 것이다.
문장이 어색하다고 생각합니다!

2023-10-24 12:11 UTC, tmdgh1592 requested changes
안녕하세요 코건!
글을 읽으면서 코건이 얼마나 게임에 관심이 많은지 알 수 있었습니다 😂
더불어, 이렇게 게임에 관심이 많은데 왜 안드로이드 개발자를 지망하는지도 작성해주시면 좋을 것 같아요.

2023-10-24 12:11 UTC, tmdgh1592 commented on Level4.md
> +사람들은 댓글과 좋아요 반응을 남겨주었고, 처음으로 제대로 된 성취감을 느꼈다.
`제대로 된` 라는 단어가 어색하게 느껴지네요.

2023-10-24 12:11 UTC, tmdgh1592 commented on Level4.md
> +이러한 성취를 기반으로 반복해서 게임을 만들었고, 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
`~고, ~고` 가 반복되어서 조금 부자연스럽게 읽히는 경향이 있습니다.
문장을 끊어보는 것도 좋을 것 같아요~

2023-10-24 12:11 UTC, tmdgh1592 commented on Level4.md
> +둠과 퀘이크를 만드는 과정에서 존 카맥이 새로운 엔진을 개발했는데, 그때 당시엔 존재하지 않던 렌더링, 네트워크 기법을 구상하고 구현하였다.
`둠` 과 `퀘이크` 가 무엇인지 조금이나마 설명해주시면 좋을 것 같아요!
처음 들어보는 개념이라 바로 이해하기가 어렵네요 🥲

2023-10-24 12:11 UTC, tmdgh1592 commented on Level4.md
> +이러한 기술을 기반으로 게임을 제작했고, 이는 사람들에게 새로운 충격과 즐거움을 제공했다.
`이러한`, `이를` 이 자주 반복되는 것 같아요!
위 단어를 제거하고 자연스럽게 문장을 만들어보는 도전을 해보는 것은 어떤가요?

2023-10-24 12:11 UTC, tmdgh1592 commented on Level4.md
> +하지만 분명히 내 선에서 만들 수 있는 작은 혁신은 있을 것이다. 나 뿐만 아니라 여러 사람이 동참하면 이는 더 큰 영향을 끼칠 것이다.
위와 비슷한 맥락의 리뷰입니다!
가능한 `나`, 내`, `나는` 등의 단어를 제거하고 문장을 자연스럽게 만들어보는 시도를 해보는 것도 좋은 경험이 될 것이라고 생각해요!

2023-10-24 12:11 UTC, tmdgh1592 commented on Level4.md
> +"작은 기술 혁신으로도 새로운 경험을 제공할 수 있는 개발자"가 되고싶다.
코건의 작은 혁신이 누군가에게는 큰 혁신으로 느껴질 수 있는 개발자가 되기를 소망합니다 😃

2023-10-26 07:37 UTC, D0Dam reviewed
안녕하세요 코건~! 뭔가 게임쪽에서 대단한 사람인 것 같군요... 과거에 다양한 걸 많이 하신 경험이 참 부럽네요..
코멘트 확인 부탁드립니다~!

2023-10-26 07:37 UTC, D0Dam commented on Level4.md
> +네이버 카페에 가입해 강좌를 듣고 조악하게나마 만든 게임들을 업로드했다.
헉 어떤 게임을 만드셨죠?? 들어보고 싶어요~!

2023-10-26 07:37 UTC, D0Dam commented on Level4.md
> +이러한 기술을 기반으로 게임을 제작했고, 이는 사람들에게 새로운 충격과 즐거움을 제공했다.
사람들이라고 하면 네이버 카페 사람들을 말하는걸까요?

2023-10-26 07:37 UTC, D0Dam commented on Level4.md
> +## 게임메이커와 둠, 카운터 스트라이크와 모드 커뮤니티
전체적으로 어떤 개발자가 되고 싶은지에 대한 서론이 길다고 느껴졌어요..!! 모르는 단어가 많아서 읽는데 흐름이 끊겨서 좀 더 알기 쉽게 축약해도 좋지 않을까 생각해봅니다..!!

2023-10-27 01:07 UTC, hum02 approved these changes
리뷰 늦어서 죄송합니다ㅠㅠ 잘봤습니다 코건
피드백은 자유롭게 반영해주세용

2023-10-27 01:07 UTC, hum02 commented on Level4.md
> +
둠이라는 책과 여러 게임에 대한 정보를 잘 읽었습니다.
그런데 이 글의 목적은 코건이 어떤 프로그래머로서의 삶을 살고 싶으냐인데, 많은 분량을 기술적인 정보를 서술하는데 쓰신 것 같아요!
이런 게임과 기술들 중 코건에게 어떤 영향을 미쳤는지에 관계된 게 아니라면 없어도 되는 세부내용은 생략해도 되지 않을까요?

2023-10-27 01:07 UTC, hum02 commented on Level4.md
> +대단히 많은 혁신이 있진 않았다. 하지만 나만의 작은 혁신을 위해 여러 시도를 하며 발걸음을 떼어나가며 많은 것을 배우고 느꼈다.
`많은 것을 배우고 느꼈다. `에서 어떤 것을 배우고 느꼈는지가 
코건이 게임엔진을 만들고 roompager를 만들었다는 서술보다 더 중요한 부분 아닐까요?
어떤 것을 배웠는지 궁금하네요!

2023-10-27 05:47 UTC, DYGames commented on Level4.md
> +이러한 성취를 기반으로 반복해서 게임을 만들었고, 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
생각해보니까 계속해서가 좋겠네요! 감사합니당

2023-10-27 05:48 UTC, DYGames commented on Level4.md
> +하프라이프는 엄청난 인기를 얻었고, 여러 모드도 제작되었는데 이 중 카운터 스트라이크라는 모드가 인기를 얻고 개별 게임으로도 출시되었다.
하프라이프의 모드중 하나였죠 ㅎ_ㅎ

2023-10-27 05:48 UTC, DYGames commented on Level4.md
> +## 게임엔진연구회와 RoomPager
RoomPager에 대한 내용을 추가하겠습니다.

2023-10-27 05:49 UTC, DYGames commented on Level4.md
> +제목은 거창하게 새로운 기술을 선도하고 적어놨지만 누구나 기술을 선도할 수 있는 것은 아닐 것이다.
오타가 있었네요.

`제목은 거창하게 새로운 기술을 선도한다고 적어놨지만 누구나 그럴 능력이 있는 것은 아니다.`

2023-10-27 05:49 UTC, DYGames commented on Level4.md
> +사람들은 댓글과 좋아요 반응을 남겨주었고, 처음으로 제대로 된 성취감을 느꼈다.
좀 어색하긴 하네요..

그냥 삭제하겠습니다.

2023-10-27 05:50 UTC, DYGames commented on Level4.md
> +이러한 성취를 기반으로 반복해서 게임을 만들었고, 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
```
사람들은 댓글과 좋아요 반응을 남겨주었는데, 이를 보며 처음으로 성취감을 느꼈다.
이러한 성취를 기반으로 계속해서 게임을 만들어 나갔다. 그러자 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
```

2023-10-27 05:52 UTC, DYGames commented on Level4.md
> +하지만 분명히 내 선에서 만들 수 있는 작은 혁신은 있을 것이다. 나 뿐만 아니라 여러 사람이 동참하면 이는 더 큰 영향을 끼칠 것이다.
저도 문장 전체적으로 나, 내를 없애려고 했는데 이 문단은 제목부터
`내 선에서 최선을`
이고, 나의 능력 안에서 혁신을 한다는 내용이기에 어쩔수 없다고 생각되네요.

2023-10-27 05:52 UTC, DYGames commented on Level4.md
> +"작은 기술 혁신으로도 새로운 경험을 제공할 수 있는 개발자"가 되고싶다.
감사합니다 부나님 하하

2023-10-27 05:54 UTC, DYGames commented on Level4.md
> +네이버 카페에 가입해 강좌를 듣고 조악하게나마 만든 게임들을 업로드했다.
저 시절 만든 게임은 소멸됐습니다.

가장 최근에 만든건 2017년작 Lotis Berry 네요 ㅎㅎ..

https://www.youtube.com/watch?v=feGyPshVzlU

2023-10-27 05:55 UTC, DYGames commented on Level4.md
> +이러한 기술을 기반으로 게임을 제작했고, 이는 사람들에게 새로운 충격과 즐거움을 제공했다.
저 당시 둠을 접했던 대중인데 표현이 애매하네요. 저 문단 전체를 수정해보겠습니다.

2023-10-27 05:55 UTC, DYGames commented on Level4.md
> +
저도 적으면서 고민했는데 좀 어렵네요. 전체적으로 축약하고 저 역사적 사실이 제 성장에 미친 영향 위주로 재작성 해보겠습니다.

2023-10-27 09:34 UTC, tmdgh1592 commented on Level4.md
> +이러한 성취를 기반으로 반복해서 게임을 만들었고, 점점 퀄리티가 상승하고 결과물을 만드는 과정 자체에 익숙해졌다.
좋습니다~~

2023-10-28 07:15 UTC, 2yunseong approved these changes
코건 마지막 미션까지 고생하셨습니다!!

2023-10-28 08:00 UTC, MoonJeWoong approved these changes
안녕하세요 코건~ 히이로입니다!

전반적으로 어릴때부터 지금까지 개발에 대한 열정이 쭉 이어져오고 있음이 확 느껴지는 글이었습니다. 큰 수정사항은 없어 approve 드리니 사소한 리뷰들만 참고해주시면 좋겠습니다.

긴 교육과정 달려오시느라 고생 많으셨습니다~ 😄

2023-10-28 12:07 UTC, tmdgh1592 approved these changes

2023-10-29 10:54 UTC, kevstevie approved these changes
안녕하세요 코건

글을 읽고 코건이 존경스러워졌어요
디깅룸도 굉장히 잘 만들었다고 생각했는데 이런 사람이 만들었군요..
빨리 유튜브샘플 제끼러 갑시다

2023-10-30 04:29 UTC, D0Dam commented on Level4.md
> +네이버 카페에 가입해 강좌를 듣고 조악하게나마 만든 게임들을 업로드했다.
아니 퀄 대박적이네요!!! 정말 머싯네요..👍

2023-10-30 04:29 UTC, D0Dam approved these changes

2023-11-08 04:31 UTC, merged