[레벨 4 글쓰기 미션] 에단(김석호) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #474
Opened 2023-10-23 07:19 UTC by cookienc

안녕하세요 하티, 세인, 매튜, 우기, 오잉, 엔델😄
글쓰기 1차 작성이 완료되어서 리뷰 요청드려요.
다들 바쁘실텐데 시간 내주셔서 감사합니다🙇‍♂️🙇🙇‍♀️

2023-10-23 07:23 UTC, junpakPark commented on level4.md
> +지금은 프로젝트가 작아 20명을 행복하게 하는 것으로 만족하고 있지만, 나중에 1,000명 10,000명이 이용하는 서비스가 된다면? 더 많은 사람이 행복해할 것이다.
구체적인 수치로 표현하니 더 멋있네요 👍👍

2023-10-23 08:50 UTC, SproutMJ approved these changes
안녕하세요 에단, 엔델입니다.
에단의 글을 읽어보니 저도 많은 사람들에게 기쁨을 주는 개발자가 되고 싶어지는 것 같습니다.
기본적으로 문맥상 흐름이나 맞춤법, 글쓰기 규칙에서 큰 문제점을 발견하지 못했습니다.
그래서, 충분히 깔끔한 글이라고 생각해 approve를 바로 하겠습니다.
좋은 개발자가 되시길 바라면서 우아한테크코스 잘 마무리하시길 기원합니다.
감사합니다.

2023-10-24 01:32 UTC, boogi-woogi commented on level4.md
> +결국엔 여차저차 해서 내가 하기로 결정되었다.
결국 졸업프로젝트에서 개발을 혼자 담당하게 되신건가요?? 

정말 암울하네요..

2023-10-24 01:43 UTC, boogi-woogi requested changes
졸업 프로젝트에서 처음 프로그래밍을 하신 것으로 이해했습니다! 

시작하신지 얼마 되지 않았는데 벌써 우테코에 합격하신 것을 보면 정말 많은 노력을 하셨을 거라고 생각합니다ㅎㅎ

정말 대단하다는 생각이 들고 앞으로 남은 기간도 화이팅!

2023-10-24 01:43 UTC, boogi-woogi commented on level4.md
> +결국엔 여차저차 해서 내가 하기로 결정되었다.
결국 졸업프로젝트에서의 개발을 혼자 담당하시게 되었나요??

정말 암울하네요 ㅠㅠ

2023-10-24 01:43 UTC, boogi-woogi commented on level4.md
> +결국엔 작품은 졸업 전시 한 번만 하고 분해되었으며 비싼 부품들은 팀 회식비가 되었다.
`작품`이라는 말이 앞에서 반복되어 이 문장에서는 없어도 의미가 잘 전달된다고 생각합니다!

2023-10-24 01:43 UTC, boogi-woogi commented on level4.md
> +이 과정을 통해 사용자가 불편하지 않게, 나아가 사용자를 어떻게 만족스럽게 할 수 있을까 하는 생각을 갖게 됐다.
마음속으로 한 말인 `사용자를 어떻게 만족스럽게 할 수 있을까?` 라는 문장을 작은 따옴표로 묶어주는 것은 어떨까요?

2023-10-24 01:43 UTC, boogi-woogi commented on level4.md
> +
사용자 수가 엄청나네요 ㄷㄷ

2023-10-24 08:34 UTC, kpeel5839 requested changes
에단! 당신은 필력까지 좋군요

너무 완벽합니다.

간단한 피드백 남겼어요!

간단하게 보시고, 반영할지 말지 결정해주시면 감사할 것 같아요!

2023-10-24 08:34 UTC, kpeel5839 commented on level4.md
> +실제로 프로그래밍을 해봤을 때 삽질의 연속이라 재미가 없었다.
프로그래밍을 해보니 로 바꾸어도 자연스러울 것 같아요!

2023-10-24 08:34 UTC, kpeel5839 commented on level4.md
> +책을 찾고 구글링하면서 연속된 삽질 끝에 프로젝트를 완성했지만, 별다른 애정을 갖지 못했다.
삽질이 반복되고 있어, 다른 표현을 사용해봐도 괜찮지 않을까요?

2023-10-24 08:34 UTC, kpeel5839 commented on level4.md
> +더 나아가 이들을 행복하게 만드는 사람이 되고 싶어졌다.
나아가?

2023-10-24 08:34 UTC, kpeel5839 commented on level4.md
> +글을 쓰는 지금, 가입자 수는 110명이 넘고 서비스를 통해 코드 리뷰를 받는 사람은 20명이 넘었다.
미뗬다... ㄸㄸ

2023-10-24 08:34 UTC, kpeel5839 commented on level4.md
> +나는 이렇게 사람들에게 기쁨을 주는 서비스를 만드는 사람이 되고 싶다.
마지막 문장 너무 멋져요 A단

2023-10-25 01:28 UTC, sujin9 reviewed
안녕하세요 에단!
저는 안드로이트 하티 🍵 라고 해요. 반갑습니다 ~

글이 잘 읽혀서 술술 읽었어요! 몇 가지 제안만 남겨드렸습니다 :)
프로젝트를 하며 사용자도 많고 피드백도 받고 많은 경험을 하셨네요 👍  (부럽습니당... ㅋㅋㅋㅋ)

2023-10-25 01:28 UTC, sujin9 commented on level4.md
> +이건 문법이 틀려서 안 되고, 저건 옛날 버전이어서 안 되고, 되는 이유는 없었지만, 안되는 이유가 수두룩했다.
문장을 중간에 끊어가도 좋을 것 같은데요? :)

2023-10-26 10:53 UTC, semnil5202 reviewed
안녕하세요 에단~ 세인입니다.

글쓰기 미션하시느라 고생많으셨습니다. 👍

전체적으로 글의 맥락이 잘 잡혀있어서 크게 리뷰드릴 것은 없었어요~ 몇 가지 코멘트 남겼습니다.

확인 후 리뷰 재요청 부탁드립니다.

2023-10-26 10:53 UTC, semnil5202 commented on level4.md
> +졸업 프로젝트를 할 때 프로그래밍할 사람이 필요했고, 모두 프로그래밍하기 매우 싫어했다.
`프로그래밍하기`보단 `프로그래밍을 하기`가 더 자연스러운 것 같아요~~

2023-10-26 10:53 UTC, semnil5202 commented on level4.md
> +결국엔 작품은 졸업 전시 한 번만 하고 분해되었으며 비싼 부품들은 팀 회식비가 되었다.
`졸업 전시 한 번만 하고`보다 `졸업 전시 때만 사용하고` 가 어떨까요??

2023-10-26 10:53 UTC, semnil5202 commented on level4.md
> +이와 더불어 다른 사람들과 좀 더 큰 프로젝트를 해보고 싶은 마음이 들어 우테코에 오게 되었다.
졸작 때 프로그래밍 이후 바로 우테코라.. 엄청난 실력자시군요.. 👀

2023-10-26 10:53 UTC, semnil5202 commented on level4.md
> +감사하게도 더 나은 서비스가 될 수 있도록 불편 사항도 직접 알려주는 사용자들도 있었다.
와우 불편사항 피드백.. 귀하군요..

2023-10-27 15:25 UTC, hanueleee approved these changes
안녕하세요 에단!!
오잉입니다 😆

`사람들에게 기쁨을 주는 사람`이라는 제목과
`나는 이렇게 사람들에게 기쁨을 주는 서비스를 만드는 사람이 되고 싶다.`라는 맺음말이 참 멋져요..
과연 나는 누군가에게 기쁨을 주거나 주려 했던 적이 있었나? 라는 생각이 드네요 ㅎㅎ

평소에 에단이 매일매일 아침 일찍 캠퍼스에 등교해 묵묵하게 공부를 해나가는 모습을 보고
정말 대단하다고 항상 생각했어요.
에단은 정말 성실하고 노력하는 멋진 개발자이기 때문에
먼 미래의 목표로 삼지 않더라도
지금 당장 에단의 `바톤`이 여러 사람에게 기쁨을 주고 있다고 생각합니다 ><

리뷰는 간단한 제안 사항 위주로 남겨두었습니다!!
남은 레벨5도 우리모두 화이팅해요~~~~~~👨‍🎤🧑‍🎤👩‍🎤

2023-10-27 15:25 UTC, hanueleee commented on level4.md
> +## 사람들에게 기쁨을 주는 사람
뭔가 몽글몽글하고 멋진 제목이에요..☺️

2023-10-27 15:25 UTC, hanueleee commented on level4.md
> +프로그래밍을 시작한 이유는 특별한 건 없다.
```suggestion
프로그래밍을 시작한 특별한 이유는 없다.
```
는 어떨까요 ㅎㅎ

2023-10-27 15:25 UTC, hanueleee commented on level4.md
> +이건 문법이 틀려서 안 되고, 저건 옛날 버전이어서 안 되고, 되는 이유는 없었지만, 안되는 이유가 수두룩했다.
```suggestion
이건 문법이 틀려서 안 되고, 저건 옛날 버전이어서 안 되고.
되는 이유는 없었지만, 안되는 이유는 수두룩했다.
```
이런식으로 줄바꿈을 하면 더 멋질 것 같아요 😆

2023-10-27 15:25 UTC, hanueleee commented on level4.md
> +졸업하기 위한 작품이었을 뿐 그 이상의 의미가 있는 작품이 아니었다.
```suggestion
졸업을 위한 작품이었을 뿐, 그 이상의 의미는 없었다.
```
는 어떨까요?! 조금 더 강조하기 위해ㅎㅎ

2023-10-27 15:25 UTC, hanueleee commented on level4.md
> +결국엔 작품은 졸업 전시 한 번만 하고 분해되었으며 비싼 부품들은 팀 회식비가 되었다.
오옹 비싼 부품들이 들어가는 졸업 작품이라면..?!
뜬금없지만 에단의 전공이 궁금해요 ㅎㅎ 기계공학과????🤖

2023-10-30 06:18 UTC, cookienc commented on level4.md
> +결국엔 여차저차 해서 내가 하기로 결정되었다.
네 맞아요ㅜㅜ

2023-10-30 06:18 UTC, cookienc commented on level4.md
> +더 나아가 이들을 행복하게 만드는 사람이 되고 싶어졌다.
갈고리 이모지 없는게 아쉽네요

2023-10-30 06:18 UTC, cookienc commented on level4.md
> +결국엔 작품은 졸업 전시 한 번만 하고 분해되었으며 비싼 부품들은 팀 회식비가 되었다.
전자공학과입니다~

2023-10-30 06:21 UTC, cookienc commented
안녕하세요👋 하티, 세인, 매튜, 우기, 오잉, 엔델😄
맛있는 리뷰 감사합니다🙇🙇‍♀️
리뷰 반영했습니다. 확인 부탁드립니다~

2023-10-30 06:31 UTC, semnil5202 approved these changes
안녕하세요 에단~ 피드백 드린 부분 수정사항 확인했습니다.

글쓰기 미션 고생많으셨습니다. 👍👍

2023-10-30 07:59 UTC, boogi-woogi approved these changes
안녕하세요 에단! 긴 기간동안 정말 고생 많으셨습니다ㅎㅎ

이제 정말 얼마 남지 않았네요!

마지막까지 화이팅하시구 원하는 결과 꼭 얻으실 수 있을거에요:smile:

2023-10-30 09:04 UTC, sujin9 approved these changes
안녕하세요 에단! :)
글들이 간결해져서 가독성이 좋네요! 👍 
글쓰기로 이렇게나마 만나 반가웠어요.
그간 고생 많으셨습니다 !! 🚀

2023-10-30 11:28 UTC, kpeel5839 commented
석호필... 저의 Approve 가 너무 늦었군요!

고생했어요 마이러브 석호필!

2023-10-31 07:45 UTC, kpeel5839 approved these changes

2023-11-08 04:31 UTC, merged