[레벨 4 글쓰기 미션] 레고(박정규) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #477
Opened 2023-10-23 07:31 UTC by regularPark

반가워요 제이, 아이크, 루루, 글로, 박스터, 첵스! 레고입니다!

벌써 레벨 4 글쓰기 미션을 하고있다니..시간이 참 빠르네요🥲
오후 세시 갬성으루다가 쓰다보니 글이 상당히 추상적이네요ㅎㅎ..😅

편하게 읽어주세요~

### [읽으러 가기](https://github.com/regularPark/woowa-writing-5/blob/regularpark/level4.md)

2023-10-23 08:37 UTC, eunkeeee approved these changes
레고 글 다 읽었슴당
맨날 장난만 치다가 글에서는 진지한 모습이 낯설지만 꿀잼이네요🌟

2023-10-23 11:47 UTC, ippnsj reviewed
글의 틀이 잘 짜여있고 재밌다고 생각합니다! 😉 👍

2023-10-23 11:47 UTC, ippnsj commented on level4.md
> +그렇게 나는 내가 걸어온 길을 뒤로 하고, **개발**이라는 새로운 방향을 택했다. 나는 남들보다 늦게 이 길에 들어섰다. 배우는 속도도 빠르지 않다. 하지만 나는 여태 그래왔듯 쉬지 않고 걷어왔다. 그게 낮이든 밤이든 어떤 날이든, 나는 걸었다.
> 걷어왔다

오타가 있어요!

2023-10-24 10:14 UTC, HyeryongChoi commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
고개를 숙이고 어떻게 앞만 보고 걷죠?

2023-10-24 10:24 UTC, HyeryongChoi requested changes
렉오의 글 재미나게 읽었습니다. 레고의 종착지를 살펴보니 저랑 비슷한 곳을 향해 가고있는 것 같아요.
앞으로도 계속 행복코딩하셨으면 좋겠습니다. 레고의 여정 응원할게요.👏👏👏

(글은 오타가 있는 부분만 수정해주시면 될 것 같아요)

2023-10-24 13:38 UTC, drunkenhw approved these changes
안녕하세요 레고
처음 뵙겠습니다
저도 늦게 시작해서 공감이 되는 부분이 많네요
잘 읽었습니다

2023-10-24 13:38 UTC, drunkenhw commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
어느날엔가 라는 문장이 저한텐 어색한 것 같아요
어느날 로만 해도 괜찮을 것 같은데 어떻게 생각하시뇨여?

2023-10-24 13:38 UTC, drunkenhw commented on level4.md
> +가야 할 길을 가리키는 나침반이 고장난 걸까, 아님 내가 내딛었던 발걸음의 방향이 잘못된 걸까. 내 발자취에서는 방향성이나 일관성 따위는 찾아볼 수 없었다. 분명 나는 순간순간 상황에 맞는 최선의 선택을 하기 위해 노력했다. 아니, 그렇게 생각했다. 내겐 고개를 들어 저 너머를 볼 여유가 없었다. 실제로 그랬다. 내 세상에서 내일, 내년보다 중요했던 것은
결국 지금 여기에 있다면, 지금 행복하다면 나침반도 정상이고 발걸음의 방향도 정확했던 것 아닐까요? 👍

2023-10-24 13:38 UTC, drunkenhw commented on level4.md
> +이 길에 들어선 후로 나보다 빠른 이들을 숱하게 봐왔다. 내가 그들처럼 달려 나갈 수 없음을 잘 안다. 나는 나만의 속도로 걸어가겠다고 오늘도 다짐한다. 그렇게 꾸준히 걷다 보면 도달하고자 했던 종착지에 도착하리라 믿기 때문이다.
저도 꾸준한게 최고인 것 같아요

2023-10-25 02:52 UTC, hafnium1923 approved these changes
스크의 멋진 레고!! 레고에겐 제게 없는 꾸준함이 있어서 부러워요..
함께 열심히 걸어가봐요!
글 이 너무 감명깊었던 것 같아요
마지막 미션까지 고생하셨습니다!

2023-10-25 02:52 UTC, hafnium1923 commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
> 나는 어느 날엔가 내 발끝이 아닌 저 너머를 보게 됐다
나는 이라는 말은 꼭 없어도 될 것 같아요!

2023-10-25 02:52 UTC, hafnium1923 commented on level4.md
> +이 길에 들어선 후로 나보다 빠른 이들을 숱하게 봐왔다. 내가 그들처럼 달려 나갈 수 없음을 잘 안다. 나는 나만의 속도로 걸어가겠다고 오늘도 다짐한다. 그렇게 꾸준히 걷다 보면 도달하고자 했던 종착지에 도착하리라 믿기 때문이다.
꾸준함이 가장 어려운데 어려운걸 레고는 가지고 있었네요! 부러워요

2023-10-25 02:52 UTC, hafnium1923 commented on level4.md
> +나는 **행복**하기 위해 프로그래밍을 한다. 최고의 개발자가 되고 싶은 마음도 없고, 또, 될 수도 없음을 잘 안다. 다른 이들과 비교하는 것에 집착하지 않는다. 프로그래밍하는 자체로 즐겁다. 변화무쌍한 개발이라는 길 위에서 방향을 잃지 않고 걸어나간다는 것만으로도 잘해내는 것이라고 생각한다.
제가 보기엔 레고는 최고의 개발자인데..

2023-10-25 02:52 UTC, hafnium1923 commented on level4.md
> +비록 나는 늦게 출발했지만, 나만의 속도로, 후회 없이 즐기며 나아가고 있다.
👏👏👏

2023-10-25 11:11 UTC, afds4567 approved these changes
안녕하세요 레고 ✋ 
본의아니게 앞에 글도 읽어버렸는데여... 잘 읽었습니다
언젠가 레고도, 저도 바라보던 종착지에서 웃으면서 얘기하는 순간 기대하겠습니다 😄 😄
남은 1달도 후회 안남게 화이팅입니다

2023-10-25 11:11 UTC, afds4567 commented on level4.md
> +이 길에 들어선 후로 나보다 빠른 이들을 숱하게 봐왔다. 내가 그들처럼 달려 나갈 수 없음을 잘 안다. 나는 나만의 속도로 걸어가겠다고 오늘도 다짐한다. 그렇게 꾸준히 걷다 보면 도달하고자 했던 종착지에 도착하리라 믿기 때문이다.
언젠간 레고도 저도 거기에 도착하길 바래요

2023-10-26 06:00 UTC, sosow0212 approved these changes
안녕하세요 레고! 글을 잘쓰셔서 읽기 편했습니다 :)
종착지에 도착할 멋진 레고가 되길 바라며 응원하겠습니다.

좋은 글 써주셔서 감사합니다 👍

2023-10-28 23:10 UTC, regularPark commented on level4.md
> +그렇게 나는 내가 걸어온 길을 뒤로 하고, **개발**이라는 새로운 방향을 택했다. 나는 남들보다 늦게 이 길에 들어섰다. 배우는 속도도 빠르지 않다. 하지만 나는 여태 그래왔듯 쉬지 않고 걷어왔다. 그게 낮이든 밤이든 어떤 날이든, 나는 걸었다.
수정하였습니다🥲

2023-10-28 23:11 UTC, regularPark commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
저항하려 했지만 제가 봐도 어색하여 수정 완.

> 꽤 오랫동안 고개를 숙인 채 걸었다. 쉬지 않고 내 발끝만 보고 걸었다.

2023-10-28 23:15 UTC, regularPark commented on level4.md
> +하지만 고개를 들어 저 너머를 내다 본 **어느 날**, 바로 그날, 오늘보다 내일이 더 중요해졌다. 오래 걸어왔다고 해서 내가 원하지 않는 길을 계속 걸어간다면 종착지에 후회만이 있을 것 같았다.
<img src="https://github.com/woowacourse/woowa-writing-5/assets/90092440/b2294632-d08c-458e-81f0-3005508386f1" width=300/>

저는 곧 죽겠군요😇😇

2023-10-28 23:16 UTC, regularPark commented on level4.md
> +개발자라는 길에서 어디에 도달하고 싶냐고 묻는다면, 꽤나 진부하지만 바로 나의 **행복**이다.
첵스와 생각이 같다니 기분이 정말 좋네요🤥

2023-10-28 23:17 UTC, regularPark commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
수정해보았습니다! 요건 어떨까요?🤔

> **문득** 내 발끝이 아닌 저 너머를 보게 됐다.

2023-10-28 23:18 UTC, regularPark commented on level4.md
> +가야 할 길을 가리키는 나침반이 고장난 걸까, 아님 내가 내딛었던 발걸음의 방향이 잘못된 걸까. 내 발자취에서는 방향성이나 일관성 따위는 찾아볼 수 없었다. 분명 나는 순간순간 상황에 맞는 최선의 선택을 하기 위해 노력했다. 아니, 그렇게 생각했다. 내겐 고개를 들어 저 너머를 볼 여유가 없었다. 실제로 그랬다. 내 세상에서 내일, 내년보다 중요했던 것은
좋은 말씀 감사합니다 🤗

2023-10-28 23:19 UTC, regularPark commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
수정 완!🫡

> **문득** 내 발끝이 아닌 저 너머를 보게 됐다.

2023-10-28 23:22 UTC, regularPark commented on level4.md
> +나는 **행복**하기 위해 프로그래밍을 한다. 최고의 개발자가 되고 싶은 마음도 없고, 또, 될 수도 없음을 잘 안다. 다른 이들과 비교하는 것에 집착하지 않는다. 프로그래밍하는 자체로 즐겁다. 변화무쌍한 개발이라는 길 위에서 방향을 잃지 않고 걸어나간다는 것만으로도 잘해내는 것이라고 생각한다.
최고의 개발자는 루루가 아닐까요...🤔

2023-10-28 23:24 UTC, regularPark commented on level4.md
> +꽤 오랫동안 고개를 숙인 채 그저 앞만 보고 걸었다. 그렇게 쉬지 않고 내 발끝만 보고 걸었다. 그 길에서 나름 자리를 잡아가고 있을 때쯤, 나는 **어느 날**엔가 내 발끝이 아닌 저 너머를 보게 됐다. 지금 내가 가는 길이 어디로 향하고 있는지를 말이다. 그곳엔 내가 원하는 모습이 없었다. 나는 그제야 가던 길을 멈추고 고개를 들어 내가 걸어온 자취를
서윗한 말 고마워요 아이크🤗

2023-10-28 23:27 UTC, regularPark commented on level4.md
> +하지만 고개를 들어 저 너머를 내다 본 **어느 날**, 바로 그날, 오늘보다 내일이 더 중요해졌다. 오래 걸어왔다고 해서 내가 원하지 않는 길을 계속 걸어간다면 종착지에 후회만이 있을 것 같았다.
저랑 가치관이 비슷하시다니 정말 좋네요! 😄

2023-10-29 06:06 UTC, ippnsj approved these changes
마지막 글쓰기 미션까지 수고했어요~👏

2023-10-30 06:38 UTC, HyeryongChoi commented on level4.md
> +개발자라는 길에서 어디에 도달하고 싶냐고 묻는다면, 꽤나 진부하지만 바로 나의 **행복**이다.
영혼 담아주세요 레고~

2023-10-30 06:39 UTC, HyeryongChoi approved these changes

2023-11-08 04:31 UTC, merged