[레벨 4 글쓰기 미션] 윤생(이윤성) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #501
Opened 2023-10-23 11:04 UTC by 2yunseong

안녕하세요!

글쓰기 제출합니다! 감사합니다!

2023-10-24 01:28 UTC, DYGames requested changes
안녕하세요 윤생~! 반갑습니다.

저도 게임 개발로 프로그래밍을 접했어서 반갑네요.

몇가지 코멘트 남겼으니 확인 부탁드릴게요.

2023-10-24 01:28 UTC, DYGames commented on level4.md
> +그러면서 컴퓨터로는 플래시 게임이라는게 유행하였다.
`컴퓨터로는`
현실과 온라인, 디지털 환경을 대조하고 싶어 나온 문장 같습니다.

`컴퓨터 환경에선`, `디지털 환경에선` 등이 어떨까요?

2023-10-24 01:28 UTC, DYGames commented on level4.md
> +플래시 365라는 플랫폼 안에서 유저들이 만든 플래시 게임들을 하곤 했었다.
저도 플래시 365에 게임 업로드를 했었는데 반갑네요 ㅎ_ㅎ

2023-10-24 01:28 UTC, DYGames commented on level4.md
> +하지만 그리 만만치 않았다. 결국 만들어진 결과물은 간단히 몬스터만 잡으면 돈이 올라가는 그런 게임이였다.
`돈이 올라가는` 이라는 표현이 어색한데, `자금을 획득하는` 정도가 어떨까요?

2023-10-24 01:28 UTC, DYGames commented on level4.md
> +(이후 이야기는 너무 길어지는거 같아 생략한다.)
생략한다는 문장보다는, 최종적으로 컴퓨터 공학과에 진학했다는 내용으로 문단을 마무리 짓는게 깔끔하겠네요.

2023-10-24 01:28 UTC, DYGames commented on level4.md
> +이제 내가 앞으로 살아가야 할 삶은 남이 원하는 가치를 소프트웨어로 바꿔주는 사람이 될 것이다.
`남이 원하는 가치를 소프트웨어로 바꿔주는 사람`이 되겠다고 결심한 계기나 구체적인 사례가 있을까요?

2023-10-24 01:28 UTC, DYGames commented on level4.md
> +하지만 언젠가의 나는 할 수 있으리라 다짐하며 이 글을 마친다.
'그런 상충관계'를 어떻게 '중재' 할 수 있을지 고민했거나 생각해본 방안이 있을까요?

2023-10-24 11:31 UTC, tmdgh1592 requested changes
안녕하세요 윤생!
글 재미나게 잘 읽었습니다~
전반적으로 글에 `내가`, `나` 등의 자신의 칭하는 단어가 많이 포함되어 있는 것 같아요 😃
LMS에서 명시해준 것처럼 위 단어들을 제외하는 문장을 만들어보는 것은 어떨까 싶습니다!

2023-10-24 11:31 UTC, tmdgh1592 commented on level4.md
> +그 때는 한창 친구들끼리 공책게임이 유행하던 때였다.
`친구들끼리` 라는 단어가 없어도 읽기 매끄러울 것 같아요!

2023-10-24 11:31 UTC, tmdgh1592 commented on level4.md
> +돈으로 뭘 할수도 없는 게임이였다. 하지만 나는 애정이 있었던걸까? 재미있었다.
맞춤법 검사기를 돌려보면 좋을 것 같아요!
`뭘 할수도` -> `뭘 할 수도`

2023-10-24 11:31 UTC, tmdgh1592 commented on level4.md
> +그러던 도중 친구가 중등 올림피아드 준비를 같이 하자며 권유했다. 한문제만 풀면 수상이라고.
`한문제만 풀면 수상이라고.` 를 이전 문장에 포함시키는 것은 어떤가요?

2023-10-26 07:17 UTC, D0Dam reviewed
안녕하세요 윤생~! 글 잘읽었습니다! 전체적으로 담백하니 좋았던 것 같아요!
코멘트 확인해주세요~!

2023-10-26 07:17 UTC, D0Dam commented on level4.md
> +그 때는 한창 친구들끼리 공책게임이 유행하던 때였다.
공책 게임은 무슨 게임이죠? 궁금하네요 ㅎㅎ

2023-10-26 07:17 UTC, D0Dam commented on level4.md
> +하지만 그리 만만치 않았다. 결국 만들어진 결과물은 간단히 몬스터만 잡으면 돈이 올라가는 그런 게임이였다.
원래 단순할수록 재밋는법! 윤생의 처음 개발은 게임이었군요!

2023-10-26 07:17 UTC, D0Dam commented on level4.md
> +그래서인지 마음속에 컴퓨터공학과에 간다면 잘 해낼것 같다! 라는 확신이 들었다.
앞의 내용을 여기서 쇼로록 회수하는군요! 글이 잘 읽혀서 좋네요~!

2023-10-27 00:53 UTC, hum02 approved these changes
리뷰 늦어서 죄송합니다ㅠㅠ
경험담을 읽을 수 있어서 재미있었네요. 리뷰 자유롭게 반영해주세용

2023-10-27 00:53 UTC, hum02 commented on level4.md
> +프로그래밍과 처음 접한 시절은 초등학교 때이다.
프로그래밍`을` 은 어떤가요?

2023-10-27 00:53 UTC, hum02 commented on level4.md
> +(이후 이야기는 너무 길어지는거 같아 생략한다.)
경험담 재미있게 읽었습니다! 그런데 `내 삶에서 프로그래밍이란?` 이라는 소제목보다 더 어울리는 소제목이 있을 것 같아요.
프로그래밍과의 만남과 시작? 같은 제목이 나으려나요

2023-10-27 00:53 UTC, hum02 commented on level4.md
> +지금까지는 내가 원하는 가치를 위해 했다면 이제부터는 남이 원하는 가치를 전달하려는 사람이 되어야 된다 생각했기 때문이다.
가치를 위해 '프로그래밍을' 한 걸까요?

2023-10-28 07:20 UTC, 2yunseong commented on level4.md
> +그러면서 컴퓨터로는 플래시 게임이라는게 유행하였다.
좋은 제안 감사합니다!
코건 코멘트에 조금 더 다듬어, `그러면서 컴퓨터로 하는 게임은 플래시 게임이 유행하였다.`로 변경해보겠습니다 :)

2023-10-28 07:24 UTC, 2yunseong commented on level4.md
> +(이후 이야기는 너무 길어지는거 같아 생략한다.)
훨씬 더 깔끔하네요 ㅎㅎ 감사합니다

2023-10-28 07:25 UTC, 2yunseong commented on level4.md
> +그러던 도중 친구가 중등 올림피아드 준비를 같이 하자며 권유했다. 한문제만 풀면 수상이라고.
무언가 도치법처럼 작성해버렸네요 ㅋㅋ 코멘트 감사합니다!!

2023-10-28 07:26 UTC, 2yunseong commented on level4.md
> +그 때는 한창 친구들끼리 공책게임이 유행하던 때였다.
초등학교 시절 공책에 그려서 하는 게임이 있었습니다 ㅎㅎ

2023-10-28 07:33 UTC, 2yunseong commented on level4.md
> +(이후 이야기는 너무 길어지는거 같아 생략한다.)
오 한번 고민해보겠습니다!! 감사합니다 :D

2023-10-28 07:42 UTC, 2yunseong commented on level4.md
> +이제 내가 앞으로 살아가야 할 삶은 남이 원하는 가치를 소프트웨어로 바꿔주는 사람이 될 것이다.
결국 사람은 일을 하면서 살아야 하는데, 프로그래밍을 하는 이유도 결국 일이라고 생각이 들었어요.
이 일이라는 건은 결국 남이 원하는 가치를 소프트웨어로 바꿔주고 저는 그에 맞는 다른 혜택을 얻는다고 생각합니다!!

2023-10-28 07:42 UTC, 2yunseong commented on level4.md
> +하지만 언젠가의 나는 할 수 있으리라 다짐하며 이 글을 마친다.
아직은 잘 모르겠네요 ..!! 실제로 무언가 남이 원하는 가치를 해주고 해보기 보다는, 지금까지는 제가 원하는 쪽으로만 고민해본 것 같아요. 남은 인생에서 잘 고민해보겠습니다!

2023-10-28 07:44 UTC, 2yunseong commented on level4.md
> +지금까지는 내가 원하는 가치를 위해 했다면 이제부터는 남이 원하는 가치를 전달하려는 사람이 되어야 된다 생각했기 때문이다.
문장이 어색한 느낌이 있네요! 수정하였습니다 !

2023-10-28 12:08 UTC, tmdgh1592 approved these changes

2023-10-29 06:25 UTC, MoonJeWoong approved these changes
안녕하세요 윤생 히이로입니다!

어렸을 때부터 지금까지의 삶이 어떤 생각과 경험들로 선택되어 이뤄져 온 것인지 알 수 있는 글이었습니다. 저희가 프로그래머를 업으로 삼고 남이 원하는 가치를 실현하기 위해 일한다고 하더라도 궁극적으로 윤생이 스스로 이루고 싶은 가치가 생기신다면, 또 그걸 위해 노력해볼 수도 있지 않을까요? ㅎㅎ 앞으로 개발자로 살아가시면서 어떤 길을 선택하든 응원하겠습니다.

긴 교육기간 달려오시느라 정말 고생 많으셨어요!

2023-10-29 06:25 UTC, MoonJeWoong commented on level4.md
> +앞으로 살아가야 할 삶은 남이 원하는 가치를 소프트웨어로 바꿔주는 사람이 될 것이다.
요 문장이 윤생이 앞으로 어떤 프로그래머가 되고 싶은지에 대한 내용인데 이에 대한 서사나 이유가 드러나지 않아 살짝 아쉽습니다... 여유가 되신다면 조금 더 부가 설명을 추가해보시는 것도 좋을 것 같아요~

2023-10-29 06:25 UTC, MoonJeWoong commented on level4.md
> +그런 상충관계 속에서 적당히 중재할 수 있는 프로그래머가 되고 싶다.
```suggestion
그런 상충관계 속에서 적당히 중재하는 역할을 할 수 있는 프로그래머가 되고 싶다.
```
요렇게 바꿔보시는 건 어떤지 제안드려봅니다!

2023-10-29 06:25 UTC, MoonJeWoong commented on level4.md
> +그 때 친구는 우리에게 C언어를 알려주었다.
중학교 때부터 c언어와 알고리즘을... 엘리트한 유년 시기를 보내셨군요 ㅎㅎ 👍

2023-10-29 06:25 UTC, MoonJeWoong commented on level4.md
> +프로그래머를 업으로 삼는다면 하고싶지 않은 일을 해야할수도 있고, 또 내가 생각하는 방향과는 다르게 흘러갈수도 있다.
```suggestion
프로그래머를 업으로 삼는다면, 하고 싶지 않은 일을 하게 되거나 생각하는 것과는 정반대의 방향으로 일하게 될 수도 있다.
```
요렇게 수정해보시는 건 어떤지 제안드려봐용!

2023-10-29 10:51 UTC, kevstevie approved these changes
안녕하세요 윤생!

굉장히 어릴적부터 프로그래밍을 접했군요! 부럽습니다
굉장히 잘 쓴 자서전의 프롤로그를 보는 듯한 기분이네요
잘 읽었습니다!

2023-10-29 15:07 UTC, DYGames approved these changes

2023-10-30 04:26 UTC, D0Dam approved these changes

2023-10-30 05:24 UTC, 2yunseong commented on level4.md
> +그런 상충관계 속에서 적당히 중재할 수 있는 프로그래머가 되고 싶다.
좀 더 주체적인 의미를 살리고 싶어서 기존의 중재할 수로 가겠습니다~! 의견 감사해요 :)

2023-10-30 05:25 UTC, 2yunseong commented on level4.md
> +프로그래머를 업으로 삼는다면 하고싶지 않은 일을 해야할수도 있고, 또 내가 생각하는 방향과는 다르게 흘러갈수도 있다.
오오 좋습니다!!

2023-11-08 04:32 UTC, merged