[레벨 4 글쓰기 미션] 베로(김은솔) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #523
Opened 2023-10-23 13:21 UTC by Cyma-s

안녕하세요 센트, 베르, 파워, 황펭, 블랙캣, 토마스!
주제인 꿈꾸는 프로그래머의 삶은 거의 안 나오는 글이기는 하네요 😂 사실상 왜 개발을 하고 싶은지에 대해 적은 것 같습니다. 

부족한 글을 읽으러 와주셔서 감사합니다.
사소한 부분이라도 괜찮으니 편하게 코멘트 남겨주세요. 감사합니다!

2023-10-23 14:43 UTC, carsago approved these changes

2023-10-23 14:43 UTC, carsago commented on level4.md
> +> 내가 좋아하는 것만큼은 잘할 수 있다.
이거 난데

2023-10-25 01:25 UTC, thdwoqor approved these changes
안녕하세요. 베로!
글 너무 재밌게 잘 읽었습니다.

리뷰는 필요하다고 생각하시면 반영해 주세요

2023-10-25 01:25 UTC, thdwoqor commented on level4.md
> +그저 그런 생각만으로 왜 살아가야 하는지 고민하게 되었던 고등학교 1학년, 나는 동아리의 구석 자리의 뭣도 아닌 컴퓨터 속의 고양이 하나에 매료되었다.
스크래치를 접해보지 않은 사람이면 부연 설명이 필요할 수도 있겠다는 생각이 들었어요

2023-10-25 01:25 UTC, thdwoqor commented on level4.md
> +> 내가 좋아하는 것만큼은 잘할 수 있다.
개발 이전에 좋아하는(잘하는) 것은 무엇이었는지 궁금하네요
(진짜 궁금함,,)

2023-10-25 01:25 UTC, thdwoqor commented on level4.md
> +동아리에 들어가서 선배들이랑 간단한 게임도 만들고, 대학교 MOOC 강의도 들어봤다. 수능 공부할 시간을 쪼개 C언어를 공부했고, 주말에도 앱을 만들러 전남대학교에 갔다. 잠이
> MOOC
언제 어디서나 대학 강의를 들을 수 있는 대규모 온라인 공개강좌다

고등학교때부터 멋지네요 👍

2023-10-25 01:37 UTC, Cyma-s commented on level4.md
> +> 내가 좋아하는 것만큼은 잘할 수 있다.
저는 아직도 개발 말고는 좋아하는 것이 없습니다 😅 
그래서 좋아하는 것을 찾고 싶어했고, 지금 개발에도 올인할 수 있는 이유인 것 같아요 😄

2023-10-25 01:38 UTC, Cyma-s commented on level4.md
> +그저 그런 생각만으로 왜 살아가야 하는지 고민하게 되었던 고등학교 1학년, 나는 동아리의 구석 자리의 뭣도 아닌 컴퓨터 속의 고양이 하나에 매료되었다.
사실 조금은 두루뭉술하게 표현하려고 의도하긴 했습니다 ㅋㅋㅋ 이야기해주신 것처럼 잘 모르는 사람도 쉽게 이해되도록 바꿔볼게요!

2023-10-28 12:39 UTC, ki960213 requested changes
반갑습니다, 베르!
베르의 생각을 표현하시는 방법이 독특해서 인상깊었고 재밌게 읽었습니다. 👍 
몇 가지 코멘트를 남겼습니다.
공감되지 않는 코멘트는 무시하셔도 괜찮습니다 😊

2023-10-28 12:39 UTC, ki960213 commented on level4.md
> +그저 그런 생각만으로 왜 살아가야 하는지 고민하게 되었던 고등학교 1학년, 나는 동아리의 구석 자리의 뭣도 아닌 컴퓨터 속의 고양이 하나에 매료되었다.
고등학교 1학년 때부터 깊은 고민을 하셨군요 👍

2023-10-28 12:39 UTC, ki960213 commented on level4.md
> +동아리에 들어가서 선배들이랑 간단한 게임도 만들고, 대학교 MOOC 강의도 들어봤다. 수능 공부할 시간을 쪼개 C언어를 공부했고, 주말에도 앱을 만들러 전남대학교에 갔다. 잠이
대단하시네요 👍

2023-10-28 12:39 UTC, ki960213 commented on level4.md
> +"내가 하는 게 정말 뭐지?"
```suggestion
"내가 하고 있는 게 뭐지?"
```
"정말"이란 단어가 없어도 괜찮을 것 같아요.

2023-10-28 12:39 UTC, ki960213 commented on level4.md
> +"잘 공부하고 있는 걸까?"
메타 인지를 하려고 노력하시는 모습을 보니 곧 원하는 것을 찾을 수 있을 것 같아요 👍

2023-10-28 12:39 UTC, ki960213 commented on level4.md
> +태양은 드높아도, 가는 길이 재밌으니까. 그거면 됐다.
위의 글을 읽고, 개발을 좋아해서 컴퓨터 공학과에 진학했지만 공부를 해도 실력이 잘 늘지 않는 것 같은데 이미 잘 하는 사람들이 많아서 심적으로 힘들었다는 내용이라고 파악했습니다.
그런데 이 글을 보면 우테코에 와보니 프로그래밍을 하고 다른 사람들과 같이 성장하는 과정이 재미있어서 결과는 상관없다는 내용이 적혀있네요.
혹시 대학교 다닐 때는 프로그래밍하고 다른 사람들과 같이 성장하지 않았나요? (정말 궁금해서 여쭤봅니다.)
그래서
```
우테코에 와보니, 결국 그저 좋아하는 것을 하고 싶었을 뿐이라는 사실을 깨달았다.
```
이 문장이 조금 설득력이 없다고 생각이 드네요 😢

2023-10-28 14:05 UTC, Cyma-s commented on level4.md
> +태양은 드높아도, 가는 길이 재밌으니까. 그거면 됐다.
대학교에서 다른 사람들과 함께 성장하기도 했지만, 마찬가지로 경쟁이 있기도 했습니다. 물론 제가 재미있어서 선택한 학과이지만, 그런 상황 속에서 스트레스를 받았던 것 같아요. 이런 내용들이 글에는 생략되어 있어 조금 부자연스러웠을 수도 있겠네요!

2023-10-29 06:34 UTC, kyw0716 approved these changes
글 정말 재밌게 잘 읽었습니다!! 세상에 기여하는 서비스를 만들며 즐거워 하는 개발자가 되시도록 응원할게요 👍

2023-10-29 06:34 UTC, kyw0716 commented on level4.md
> +"이렇게 하면 정말로 세상에 기여할 수 있는 서비스를 만들 수 있을까?"
정말 멋진 고민이네요 👍

2023-10-29 06:34 UTC, kyw0716 commented on level4.md
> +태양은 드높아도, 가는 길이 재밌으니까. 그거면 됐다.
마무리가 정말 인상깊네요! 화이팅입니다!!

2023-10-29 10:13 UTC, Leejin-Yang approved these changes
안녕하세요 베로!
베로의 고민부터 우테코 하면서 어떻게 생각이 바뀌었는지 비유를 너무 잘해주어서 재밌게 읽을 수 있었습니다
남은 기간 그리고 앞으로도 파이팅입니다 👍

2023-10-29 10:13 UTC, Leejin-Yang commented on level4.md
> +어렸을 때부터 항상 주위의 누군가 물어보던 "넌 앞으로 뭘 하고 싶어?" 라는 질문에 대답하는 게 가장 힘들었으니 말이다.
진짜 제일 어려운 질문 인정합니다..

2023-10-29 10:13 UTC, Leejin-Yang commented on level4.md
> +그때 정했다. 나는 프로그래머가 되어야겠다고.
앞에 내용이 프로그래머가 되기 위한 좋은 계기였네요 👍

2023-10-29 10:13 UTC, Leejin-Yang commented on level4.md
> +열정도 체력도 고갈된 나는 그렇게 추락했다. 바다로.
이카로스로 비유를 너무 잘했는데요?! 감탄하고 갑니다👍

2023-10-29 10:13 UTC, Leejin-Yang commented on level4.md
> +앞서가는 사람들의 존재도 지금은 그렇게 위협적이지 않다. 오히려 그들과 **함께** 날고 싶다.
멋있습니다 👍

2023-10-29 11:34 UTC, Cyma-s commented on level4.md
> +열정도 체력도 고갈된 나는 그렇게 추락했다. 바다로.
감사합니다 🙌

2023-10-29 14:16 UTC, Songusika approved these changes
안녕하세요 베로! 블랙캣입니다 🐈‍⬛

베로가 원하는 프로그래머의 삶 잘봤습니다!
글을 너무 잘쓰시네요! 간단한 리뷰남겨봤는데
베로가 원하시면 반영해주세요~~

우테코 마지막까지 화이팅입니다!

2023-10-29 14:16 UTC, Songusika commented on level4.md
> +사람들이 물어보던 질문이 정말로 궁금해서 물어보는 게 아니었다는 걸 알게 될 때쯤, 난 "계속 공부를 하고 싶다" 라는 두루뭉술한 대외적 답변을 하나 준비했다. 질문에 대답할
`두루뭉술` 도 표준어인 걸 이번에 배우네요! 👍

2023-10-29 14:16 UTC, Songusika commented on level4.md
> +하지만 그때도 몰랐다. 프로그래머도 여전히 막연한 목표였다는 걸.
그때도 모르신다는건 지금도 고민을 하고 계신거군요!
저도 그러는데 😭

2023-10-29 14:16 UTC, Songusika commented on level4.md
> +"서비스로 세상에 기여하는 개발자"라는 태양은 태양이란 게 무엇인지 정확히 몰랐던 내게도 아름다워 보였다.
```suggestion
'서비스로 세상에 기여하는 개발자'라는 태양은 태양이란 게 무엇인지 정확히 몰랐던 내게도 아름다워 보였다.  
```
윗 줄과 통일이 되면 좋을 것 같아요!

2023-10-29 14:16 UTC, Songusika commented on level4.md
> +막연한 목표로 향하기만 하는 사람이 아니라, 과정 자체를 즐길 줄 아는 사람이 되고 싶다.
베로가 원하는 프로그래머의 삶 응원합니다!

2023-10-29 17:17 UTC, SeongHoonC approved these changes
안녕하세요 베로..!! 
리뷰 늦어서 죄송합니다ㅜㅜ 다 한 줄 알았어요..

글의 기승전결이 너무 맘에 드네요! 
개인적으로 제 감성이랑 잘 맞아서 더 좋았습니다!

태양열이 날개를 녹여 없어지더라도
태양열을 연료로 날 수 있는 베로가 되길 응원합니다!

레벨 5 화이팅입니다!

2023-10-29 17:17 UTC, SeongHoonC commented on level4.md
> +*태양 가까이 날면 위험해, 이카로스.*
태양 가까이 날아 밀랍으로 된 날개가 녹았죠.. 앞으로의 글이 기대가 되네요!

2023-10-29 17:17 UTC, SeongHoonC commented on level4.md
> +사람들이 물어보던 질문이 정말로 궁금해서 물어보는 게 아니었다는 걸 알게 될 때쯤, 난 "계속 공부를 하고 싶다" 라는 두루뭉술한 대외적 답변을 하나 준비했다. 질문에 대답할
저도 이런 생각을 하면서 살았었어요..!!

2023-10-29 17:17 UTC, SeongHoonC commented on level4.md
> +힘들었지만, 겨우겨우 일어나서 프리코스를 했다. 정말 운이 좋게도, 다시 파도에 떠밀려 우테코에 올 수 있었다.
바다에 떨어진 후 내용을 예상치 못했는데 짜임새가 대단하네요..

2023-10-30 04:20 UTC, ki960213 approved these changes
리뷰 잘 반영하셔서 더 이상 리뷰할 게 없네요 👍 
앞으로도 원하는 목표를 이루시길 바랍니다! 😊

2023-10-30 04:53 UTC, Cyma-s commented on level4.md
> +하지만 좋아하는 것을 찾는 것이 더 어려운 일이었다.
`하지만 좋아하는 걸 찾는 것 자체가 어려운 일이었다.` 이렇게 바꿔봤습니다 👍🏻

2023-10-30 04:53 UTC, Cyma-s commented on level4.md
> +하지만 그때도 몰랐다. 프로그래머도 여전히 막연한 목표였다는 걸.
아직도 정확하게 '어떤 것이 되고 싶다' 라는 건 잘 모르겠어요. 다만 그 목표를 찾아가는 길을 즐겨보려 합니다 :)

2023-10-30 04:54 UTC, Cyma-s commented on level4.md
> +막연한 목표로 향하기만 하는 사람이 아니라, 과정 자체를 즐길 줄 아는 사람이 되고 싶다.
블랙캣도 파이팅입니다 😄

2023-10-30 04:54 UTC, Cyma-s commented on level4.md
> +사람들이 물어보던 질문이 정말로 궁금해서 물어보는 게 아니었다는 걸 알게 될 때쯤, 난 "계속 공부를 하고 싶다" 라는 두루뭉술한 대외적 답변을 하나 준비했다. 질문에 대답할
그래서 베르의 글에 공감이 많이 됐나봅니다 😄👍

2023-11-08 04:33 UTC, merged