[레벨 4 글쓰기 미션] 블랙캣(송우석) 미션 제출합니다.
woowacourse/woowa-writing-5 pull request #541
Opened 2023-10-23 14:24 UTC by Songusika

안녕하세요! 센트, 베르, 파워, 황펭, 베로, 토마스 👋

레벨 4 글쓰기 미션 제출합니다!
급하게 쓴거라 어색한 문장도 많고, 내용도 다소 부실하네요 ㅜㅠ
피드백 반영하면서 리팩터링 해야겠습니다.

그래도 이번 미션을 하면서
제가 진정으로 원하는 개발자의 모습을 다시 한번 고민할 수 있었어서 좋네요 😊

리뷰 감사합니다! 🙇‍♂️

[레벨4 글쓰기 미션 리뷰 범위](https://github.com/woowacourse/woowa-writing-5/pull/541/commits/ad615856531f72f849bfb3da2b52ceac37a39855)
[레벨 4 글 편하게 보러가기](https://github.com/Songusika/woowa-writing-5/blob/level4/level4.md)

2023-10-24 06:22 UTC, SeongHoonC requested changes
안녕하세요 블랙캣! 베르입니다.
저도 좋은 개발자가 어떤 개발자인지 고민했었는데
우테코를 통해서 얻은 경험이 잘 보여서 좋았습니다.
글이 정말 잘 읽히네요ㅎㅎ

내가 꿈꾸는 개발자는 좋은 개발자이다.
라는 것이 글에 잘 드러나지 않는다고 생각해요!

2023-10-24 06:22 UTC, SeongHoonC commented on level4.md
> +하지만 곧 그런 크루들에 의해서 '경쟁'이라는 키워드는 한순간에 사라졌다.
저는 크루들끼리 보이지 않는 경쟁이 남아있다고 생각해요!
하지만 선한 경쟁이라고 생각합니다!

2023-10-24 06:22 UTC, SeongHoonC commented on level4.md
> +## interface 좋은 개발자
저도 좋은 개발자가 무엇인지에 대한 생각은 매번 바뀌네요.
interface 라고 표현한 것이 마음에 들어요ㅎㅎ

2023-10-28 12:00 UTC, ki960213 requested changes
반갑습니다, 블랙캣!
블랙캣의 글 잘 읽었습니다.
저도 공유를 잘 하고 싶네요.
글을 너무 잘 쓰셔서 리뷰할 게 많이 보이지 않네요. 👍

2023-10-28 13:45 UTC, Cyma-s approved these changes
안녕하세요 블랙캣 :) 블랙캣의 생각이 담긴 글 잘 봤습니다!
우리는 언제나 좋은 개발자가 되고 싶어하죠. 그렇지만 좋은 개발자가 무엇인지에 대해 리마인드 하는 시간이 필요하다고 생각해요.
블랙캣은 현재 자신이 좋은 개발자라고 생각하시나요? 우아한테크코스를 진행하면서 좋은 개발자의 길에 한 발자국 더 다가갈 수 있었는지, 많이 성장했다고 여기시는지 궁금하네요 ㅎㅎ 
저는 남이 정의하는 좋은 개발자 대신, 자신이 정의하는 좋은 개발자가 되기 위해 노력하는 모든 사람들을 응원합니다 :) 블랙캣도 앞으로 개발하면서 행복하시길 바랄게요 😄

글쓰기 미션 수고 많으셨습니다 ~

2023-10-28 13:45 UTC, Cyma-s commented on level4.md
> +나는 왜 좋은 개발자 무엇인지 알고 싶었을까?
```suggestion
나는 왜 좋은 개발자가 무엇인지 알고 싶었을까?
```

조금 더 자연스럽게 바꿔봤습니다 👍🏻

2023-10-28 13:45 UTC, Cyma-s commented on level4.md
> +나도 모르게 '좋은 개발자'의 구체화를 배웠다.
```suggestion
하지만 수료를 앞둔 이 시점에서 지난 9개월을 돌아본 지금,
나도 모르게 '좋은 개발자'란 무엇인지 구체화할 수 있게 되었다.
```

이렇게 적어보시는 건 어떠신지요 😄

2023-10-28 13:45 UTC, Cyma-s commented on level4.md
> +당장 슬랙 채널에만 가봐도 누군가의 기술적 고민에 쏟아지는 댓글을 볼 수 있다.
인정합니다 👍🏻 저는 지식은 나눌수록 커진다는 말을 우테코에서 몸으로 익혔다고 생각해요 :)

2023-10-28 13:45 UTC, Cyma-s commented on level4.md
> +'기술적 역량', '비즈니스에 대한 이해', '사용자 중심 사고' 는 필수 소양이라고 생각한다.
필수 소양이라고 생각하시는 이유도 궁금하네요 😄

2023-10-29 06:54 UTC, kyw0716 approved these changes
글 정말 재미있게 잘 읽었습니다! 소프트웨어 생태계에 긍적적인 영향을 주는 멋진 개발자가 되시길 응원하겠습니다!!

2023-10-29 06:54 UTC, kyw0716 commented on level4.md
> +이제 나도 나의 팀, 나의 조직 그리고 소프트웨어 생태계에 긍정적인 변화를 가져올 수 있는 개발자가 되는 것,
멋지네요 👍

2023-10-29 06:54 UTC, kyw0716 commented on level4.md
> +당장 슬랙 채널에만 가봐도 누군가의 기술적 고민에 쏟아지는 댓글을 볼 수 있다.
이게 우테코의 가장 좋은 점 중 하나가 아닐까 싶네요 😀

2023-10-29 10:22 UTC, Leejin-Yang approved these changes
블랙캣 안녕하세요.!
우테코 자소서에 작성한 것을 실현했네요 😊
우테코 남은기간 그리고 앞으로도 파이팅입니다 👍

2023-10-29 10:22 UTC, Leejin-Yang commented on level4.md
> +그래서 우아한테크코스를 통해 그 답을 찾아보고 싶습니다.
빌드업이 완벽하군요!

2023-10-29 10:22 UTC, Leejin-Yang commented on level4.md
> +혹은 자신의 트러블 슈팅 경험을 다른 크루들을 위해서 공유하는 모습을 자주 볼 수 있다.
맞아요 서로서로 공유할 수 있는 자리가 있어 좋았습니다 😊

2023-10-30 05:22 UTC, thdwoqor approved these changes
안녕하세요 블랙캣
리뷰 남겼다고생각했는데 Pending 상태로 였네요,, 🥲
잘 반영해주셔서 바로 어프루브 하겠습니다!

2023-10-30 05:56 UTC, Songusika commented on level4.md
> +다른 개발자의 성장을 돕기 위해서 교육자의 길을 걷는 선택을 하셨다.
어차피 없었다고 생각합니다..😭

2023-10-30 05:58 UTC, Songusika commented on level4.md
> +나도 모르게 '좋은 개발자'의 구체화를 배웠다.
베로 정말 글을 잘 쓰시는 군요 역시..!👍👍

2023-10-30 05:58 UTC, Songusika commented on level4.md
> +당장 슬랙 채널에만 가봐도 누군가의 기술적 고민에 쏟아지는 댓글을 볼 수 있다.
이제 우테코가 끝나가는 시점에서 이제는 어디서 이런 경험을 할 수 있을까가 고민이네요..😭

2023-10-30 06:09 UTC, Songusika commented on level4.md
> +'기술적 역량', '비즈니스에 대한 이해', '사용자 중심 사고' 는 필수 소양이라고 생각한다.
해당 라인 위에 바로 추가해봤습니다!

2023-10-30 07:55 UTC, SeongHoonC approved these changes
리뷰 반영까지 고생많으셨어요! 화이팅입니다!

2023-10-30 08:20 UTC, ki960213 approved these changes
리뷰 잘 반영하셔서 더 이상 리뷰할 게 없네요 👍
앞으로도 원하는 목표를 이루시길 바랍니다! 😊

2023-11-08 04:33 UTC, merged